/*
	.\Panel\colorMappingGamutMatrix.h
	Color Mapping Gamut Matrix data generated by Display Editor
	Panel LM240WU4_SLB1
	Gamma: 2.2
	Temperature: 6500K
 */

/******************************************************************************
Color Mapping Gamut Matrix for Gamma 2.2,6500K, 10 bits
Provided by Display Editor
******************************************************************************/

WORD ROM COLOR_MAPPING_GAMUT_MATRIX_AdobeRGB98_6500K_LM240WU4_SLB1[9]=
{
   // R, G, B
	829, 38, 4,
	13, 719, 17,
	6, 15, 1001
}; //Size = 9

