/*
	.\Panel\colorMappingGamutMatrix.h
	Color Mapping Gamut Matrix data generated by Display Editor
	Panel LM240WU4_SLB1
	Gamma: 2.2
	Temperature: 6500K
 */

/******************************************************************************
Color Mapping Gamut Matrix for Gamma 2.2,6500K, 10 bits
Provided by Display Editor
******************************************************************************/

WORD ROM COLOR_MAPPING_GAMUT_MATRIX_AdobeRGB98_7500K_LM240WU4_SLB1[9]=
{
   // R, G, B
	697, 32, 3,
	11, 612, 14,
	6, 15, 1005
}; //Size = 9

