/*
	.\Panel\colorMappingGamutMatrix.h
	Color Mapping Gamut Matrix data generated by Genesis Display Editor
	Panel LM240WU4_SLB1
	Gamma: 2.2
	Temperature: 6500K
 */

/******************************************************************************
Color Mapping Gamut Matrix for Gamma 2.2,6500K, 10 bits
Provided by Genesis Display Editor
******************************************************************************/

WORD ROM COLOR_MAPPING_GAMUT_MATRIX_DICOM_6500K_LM240WU4_SLB1[9]=
{
	1024,    0,    0, // 1004, 16, 4, 
	   0, 1024,    0, // 5, 1001, 12, 
	   0,    0, 1024, // 10, 1, 1006
}; //Size = 9

