;//================================================================
;//
;// MODULE:      Define.Inc
;//
;// USAGE :      definitions for dual bank flash size and firmware version
;//
;//******************************************************************
; dual bank flash size
FLASH_BANK_SIZE EQU 200000h	; // ROM_SIZE_2MB: 200000h / ROM_SIZE_4MB: 400000h

; firmware version
FW_VER_MAJOR     EQU 1
FW_VER_MINOR     EQU 1 
FW_VER_BUILD     EQU 0

