////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef NVTABLE_H_DEFINED
#define NVTABLE_H_DEFINED

#ifndef WB_NVRAM_STRUCTURE_VERSION
#define WB_NVRAM_STRUCTURE_VERSION		0xb52d
#endif //WB_NVRAM_STRUCTURE_VERSION

// Block ID Enum
typedef enum 
{
	NVRAM_TOTAL_BLOCKS
} NVBLOCK_ID;

// Block ID Enum
#define NVRAM_TOTAL_MULTIPLE_ENTRIES		0x0000
#define NVRAM_TOTAL_ENTRIES		0x0000
extern gmt_BLOCKINFO ROM gmc_RomDirectory[];

extern BYTE ROM gmv_Size_RomDirectory;

#define USE_NVRAM_DIRECTORY		0
#define USE_ROM_DIRECTORY		0

#endif  // ifndef NVTABLE_H_DEFINED
