////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_DAT_H_DEFINED
#define OSD_DAT_H_DEFINED

// User Events defenition

extern BYTE ROM gmc_OE_EnterState;
extern BYTE ROM gmc_OE_ExitState;
extern BYTE ROM gmc_OE_NoSync_Main;
extern BYTE ROM gmc_OE_TransitionComplete;
extern BYTE ROM gmc_OE_ValidMode_Main;
extern BYTE ROM gmc_OET_OSD_Timeout;
extern BYTE ROM gmc_OE_IspStatusChanged;
extern BYTE ROM gmc_OE_NoCable_Main;
extern BYTE ROM gmc_OE_RemoveOSD;
extern BYTE ROM gmc_OE_OutOfRange_Main;
extern BYTE ROM gmc_OE_InvalidMode_Main;
extern BYTE ROM gmc_OE_PseudoMode_Main;
extern BYTE ROM gmc_OE_OutOfRange_Pip;
extern BYTE ROM gmc_OE_NoSync_Pip;
extern BYTE ROM gmc_OE_ValidMode_Pip;
extern BYTE ROM gmc_OE_SyncDetected_Main;
extern BYTE ROM gmc_OE_NoCable_Pip;
extern BYTE ROM gmc_OE_EnterPowerDeepSleep;
extern BYTE ROM gmc_OE_RemoveMenu_Main;
extern BYTE ROM gmc_OE_AutoAdjustCompleted;
extern BYTE ROM gmc_OE_ModeUnstable_Main;
extern BYTE ROM gmc_OE_PseudoMode_Pip;
extern BYTE ROM gmc_OE_ExitPowerDeepSleep;
extern BYTE ROM gmc_OE_InvalidMode_Pip;
extern BYTE ROM gmc_OE_OsdTimeout;
extern BYTE ROM gmc_OE_AutoAdjustStart;
extern BYTE ROM gmc_OE_SplashScreen;
extern BYTE ROM gmc_OE_AutoColorCompleted;
extern BYTE ROM gmc_OE_WakeUp;
extern BYTE ROM gmc_OE_DisplayOn;
extern BYTE ROM gmc_OE_ExitPowerSaving;
extern BYTE ROM gmc_OE_UpdateMuteIcon;
extern BYTE ROM gmc_OE_AutoColorFailed;
extern BYTE ROM gmc_OE_ForcePowerSaving;
extern BYTE ROM gmc_OE_IspAutoDetected;
extern BYTE ROM gmc_OE_MinuteUpdate;
extern BYTE ROM gmc_OE_ModeUnstable_Pip;
extern BYTE ROM gmc_OE_NoSignal_Pip;
extern BYTE ROM gmc_OE_PIPIconHide;
extern BYTE ROM gmc_OE_PowerUp;
extern BYTE ROM gmc_OE_SystemStartUp;
extern BYTE ROM gmc_OE_UnFreeze;
extern BYTE ROM gmc_OE_ADCCalibrationCompleted;
extern BYTE ROM gmc_OE_AnalogInput_Main;
extern BYTE ROM gmc_OE_AnalogInput_Pip;
extern BYTE ROM gmc_OE_AnyEvent;
extern BYTE ROM gmc_OE_AspectRatioUpdate;
extern BYTE ROM gmc_OE_AudioMute;
extern BYTE ROM gmc_OE_AudioOn;
extern BYTE ROM gmc_OE_AudioPCM_Message;
extern BYTE ROM gmc_OE_AudioSourceChanged;
extern BYTE ROM gmc_OE_AudioTypeChanged;
extern BYTE ROM gmc_OE_AutoAdjustComplete;
extern BYTE ROM gmc_OE_AutoAdjustFailed;
extern BYTE ROM gmc_OE_BrightnessGray;
extern BYTE ROM gmc_OE_CEC_Command_Failed;
extern BYTE ROM gmc_OE_CEC_Command_OK;
extern BYTE ROM gmc_OE_CEC_Command_Pwr_Off;
extern BYTE ROM gmc_OE_CEC_Command_Pwr_On;
extern BYTE ROM gmc_OE_CEC_DevDataBaseChange;
extern BYTE ROM gmc_OE_CEC_NewDeviceDetected;
extern BYTE ROM gmc_OE_CEC_Text4UserReady;
extern BYTE ROM gmc_OE_ChangeInputToHDMI;
extern BYTE ROM gmc_OE_ChangeInputToHDMI2;
extern BYTE ROM gmc_OE_ChangeInputToHDMI3;
extern BYTE ROM gmc_OE_CloseCaptionOff;
extern BYTE ROM gmc_OE_CloseCaptionOn;
extern BYTE ROM gmc_OE_Decoder_Main;
extern BYTE ROM gmc_OE_Decoder_Pip;
extern BYTE ROM gmc_OE_DigitalInput_Main;
extern BYTE ROM gmc_OE_DigitalInput_Pip;
extern BYTE ROM gmc_OE_DisplayBlockedChannelNum;
extern BYTE ROM gmc_OE_DisplayOff;
extern BYTE ROM gmc_OE_DrawVolumeSlider;
extern BYTE ROM gmc_OE_EraseBlockedChannelNum;
extern BYTE ROM gmc_OE_GoingToSleep;
extern BYTE ROM gmc_OE_HardPowerUp_Main;
extern BYTE ROM gmc_OE_HardPowerUp_Pip;
extern BYTE ROM gmc_OE_HideCECString;
extern BYTE ROM gmc_OE_Idle;
extern BYTE ROM gmc_OE_LowPower_Main;
extern BYTE ROM gmc_OE_LowPower_Pip;
extern BYTE ROM gmc_OE_MultiPipOff;
extern BYTE ROM gmc_OE_NoSignal_Main;
extern BYTE ROM gmc_OE_NoneKey;
extern BYTE ROM gmc_OE_OSDPort_4kx2k;
extern BYTE ROM gmc_OE_OverlappedMode_Main;
extern BYTE ROM gmc_OE_OverlappedMode_Pip;
extern BYTE ROM gmc_OE_Overlapped_Main;
extern BYTE ROM gmc_OE_Overlapped_Pip;
extern BYTE ROM gmc_OE_PipIsNotAllowed;
extern BYTE ROM gmc_OE_PowerDownNow;
extern BYTE ROM gmc_OE_PowerSaveBegin;
extern BYTE ROM gmc_OE_PowerSaveEnd;
extern BYTE ROM gmc_OE_PowerSavingNow;
extern BYTE ROM gmc_OE_RemoveMenu_Pip;
extern BYTE ROM gmc_OE_RemoveSplashScreen;
extern BYTE ROM gmc_OE_ScanFinished;
extern BYTE ROM gmc_OE_ShowCECString;
extern BYTE ROM gmc_OE_StartPowerDown;
extern BYTE ROM gmc_OE_StartPowerSaving;
extern BYTE ROM gmc_OE_SundBox_OSD_Disable;
extern BYTE ROM gmc_OE_SundBox_OSD_Eanble;
extern BYTE ROM gmc_OE_SyncDetected_Pip;
extern BYTE ROM gmc_OE_SyncPresent_Main;
extern BYTE ROM gmc_OE_SyncPresent_Pip;
extern BYTE ROM gmc_OE_SystemAudioStatusChanged;
extern BYTE ROM gmc_OE_TV_AutoScanCompleted;
extern BYTE ROM gmc_OE_TV_AutoScanStart;
extern BYTE ROM gmc_OE_TV_ChannelBlocked;
extern BYTE ROM gmc_OE_TV_ChannelChanged;
extern BYTE ROM gmc_OE_TV_ChannelUnBlocked;
extern BYTE ROM gmc_OE_TV_ManualScanCompleted;
extern BYTE ROM gmc_OE_TV_ManualScanStart;
extern BYTE ROM gmc_OE_TV_ProgramBlocked;
extern BYTE ROM gmc_OE_TV_ProgramUnBlocked;
extern BYTE ROM gmc_OE_TeletextOff;
extern BYTE ROM gmc_OE_TtxStatusDisplayOn;
extern BYTE ROM gmc_OE_USBUpStreamChange;
extern BYTE ROM gmc_OE_UpdateMultiPipChannel;
extern BYTE ROM gmc_OE_VPort_Main;
extern BYTE ROM gmc_OE_VPort_Pip;
extern BYTE ROM gmc_OE_VWD_Enable;
extern BYTE ROM gmc_OE_VWD_Lost;

typedef enum 
{
	// OE_None = 0,
	OE_EnterState = 1,
	OE_ExitState = 2,
	OEK_KEY_LOGICAL_RIGHT = 3,
	OEK_KEY_LOGICAL_MENU = 4,
	OEK_KEY_LOGICAL_DOWN = 5,
	OEK_KEY_LOGICAL_UP = 6,
	OEK_KEY_LOGICAL_ENTER = 7,
	OEK_KEY_LOGICAL_LEFT = 8,
	OEK_KEY_LOGICAL_SOURCE = 9,
	OEK_KEY_LOGICAL_POWER = 10,
	OET_OsdCustomTimer = 11,
	OE_NoSync_Main = 12,// Cable connected but not sync signal
	OE_TransitionComplete = 13,
	OE_ValidMode_Main = 14,// Valid detected from mode table
	OET_OSDRedrawTimer = 15,
	OET_InfoTimer = 16,
	OET_OSD_Timeout = 17,
	OEK_KEY_LOGICAL_MENU_RELEASE = 18,
	OE_IspStatusChanged = 19,
	OE_NoCable_Main = 20,// Cable disconnected
	OET_OSDCustomPIPTimer = 21,
	OEK_KEY_LOGICAL_EXIT = 22,
	OEK_KEY_LOGICAL_ENTER_RELEASE = 23,
	OEK_KEY_LOGICAL_SOURCE_RELEASE = 24,
	OE_RemoveOSD = 25,
	OE_OutOfRange_Main = 26,// Out of HW support mode
	OE_CMD_PowerSwitch = 27,
	OE_HardLock = 28,
	OE_InvalidMode_Main = 29,// Invalid input mode
	OEK_KEY_LOGICAL_ASPECTRATIOPIP = 30,
	OEK_KEY_LOGICAL_FREEZE = 31,
	OEK_KEY_LOGICAL_YPbPr = 32,
	OE_PseudoMode_Main = 33,// Estimated mode
	OEK_KEY_LOGICAL_MUTE = 34,
	OE_OutOfRange_Pip = 35,// Out of HW support mode
	OET_InputIconTimer = 36,
	OE_NoSync_Pip = 37,// Cable connected but not sync signal
	OE_ValidMode_Pip = 38,// Valid detected from mode table
	OEK_KEY_LOGICAL_PIP = 39,
	OE_EnterFactoryMenu = 40,
	OE_SyncDetected_Main = 41,
	OEK_KEY_LOGICAL_PreMode = 42,
	OE_BoardIDStart = 43,
	OE_NoCable_Pip = 44,// Cable disconnected
	OE_ShowInfo = 45,
	OEK_KEY_LOGICAL_AV = 46,
	OEK_KEY_LOGICAL_AV2 = 47,
	OE_Auto_Pressed = 48,
	OE_EnterPowerDeepSleep = 49,// Enter deep sleep
	OE_RemoveMenu_Main = 50,
	OEK_KEY_LOGICAL_VOL_DOWN = 51,
	OEK_KEY_LOGICAL_VOL_UP = 52,
	OEK_KEY_LOGICAL_DISPLAY = 53,
	OEK_KEY_LOGICAL_DP = 54,
	OEK_KEY_LOGICAL_HDMI = 55,
	OEK_KEY_LOGICAL_UP_RELEASE = 56,
	OEK_KEY_LOGICAL_VGA = 57,
	OE_AutoAdjustCompleted = 58,// Auto adjust completed
	OEK_KEY_LOGICAL_AUTO = 59,
	OET_AlertTimer = 60,
	OE_DiagnosticTestPattern = 61,
	OEK_KEY_LOGICAL_DOWN_AR1 = 62,
	OEK_KEY_LOGICAL_DVI = 63,
	OE_ModeUnstable_Main = 64,// Input mode unstable or mode change
	OE_PseudoMode_Pip = 65,// Estimated mode
	OEK_KEY_LOGICAL_PIP_SOURCE = 66,
	OEK_KEY_LOGICAL_SWAP = 67,
	OET_DiagnosticTestPatternTimer = 68,
	OE_ExitPowerDeepSleep = 69,// Exit deep sleep
	OE_HaveCable_Main = 70,// Cable is detected for main channel
	OE_InvalidMode_Pip = 71,// Invalid input mode
	OE_OsdTimeout = 72,
	OE_AutoAdjustStart = 73,// Auto adjust start
	OE_NoCableTimer = 74,
	OE_PIPIconShow = 75,
	OE_PIPMHide = 76,
	OE_SplashScreen = 77,// Start Splash Screen
	OET_LCDConditionTimer = 78,
	OET_OSD_IconShow = 79,
	OET_OSD_IconShow_PIP = 80,
	OET_OSD_MsgShow_PIP = 81,
	OET_PIPMUpdateTimer = 82,
	OE_AutoColorCompleted = 83,
	OE_WakeUp = 84,// Wake alarm is going off
	POE_OsdStartup = 85,
	OEK_KEY_LOGICAL_DOWN_RELEASE = 86,
	OEK_KEY_LOGICAL_SPLIT = 87,
	OET_NoSyncTimer = 88,
	OET_OsdHardLockTimer = 89,
	OE_AnyKey = 90,
	OE_DisplayOn = 91,// Turn on display
	OE_Enter_Pressed = 92,
	OE_ExitPowerSaving = 93,// System return to normal operation
	OE_IconShow = 94,
	OE_OSDTimeout = 95,
	OE_StopLCDCondition = 96,
	OE_UpdateMuteIcon = 97,
	OEK_KEY_LOGICAL_EIGHT = 98,
	OEK_KEY_LOGICAL_MENU_DELAY = 99,
	OET_AutoConfigTimer = 100,
	OE_AutoColorFailed = 101,
	OE_BoardIDEnd = 102,
	OE_ExitFactoryMenu = 103,
	OE_ForcePowerSaving = 104,
	OE_IconHide = 105,
	OE_IspAutoDetected = 106,
	OE_MinuteUpdate = 107,// RTC interrupt on every minute change
	OE_ModeUnstable_Pip = 108,// Input mode unstable or mode change
	OE_NoSignal_Pip = 109,// Video mode selected but no proper signal detected
	OE_PIPIconHide = 110,
	OE_PIPMShow = 111,
	OE_PIPMessages = 112,
	OE_PowerUp = 113,// System Power up from power down
	OE_SystemStartUp = 114,// System Power up first time
	OE_UnFreeze = 115,// Turn off Freeze on the main channel
	OE_UpdateEnergyStar = 116,
	OE_ADCCalibrationCompleted = 117,// Informs OSD to update displayed ADC calibration parameters
	OE_AnalogInput_Main = 118,
	OE_AnalogInput_Pip = 119,
	OE_AnyEvent = 120,
	OE_AspectRatioUpdate = 121,// AspectRatio is to be updated
	OE_AudioMute = 122,// Audio Mute
	OE_AudioOn = 123,// Audio on back from Mute
	OE_AudioPCM_Message = 124,
	OE_AudioSourceChanged = 125,// Audio source changed (MAIN, SAP)
	OE_AudioTypeChanged = 126,// Audio type changed (Mono, Stereo)
	OE_AutoAdjustComplete = 127,// Sent by the mode handler when the auto adjust process started by the mode handler is complete
	OE_AutoAdjustFailed = 128,// Auto adjust failed
	OE_BrightnessGray = 129,
	OE_CEC_Command_Failed = 130,
	OE_CEC_Command_OK = 131,
	OE_CEC_Command_Pwr_Off = 132,
	OE_CEC_Command_Pwr_On = 133,
	OE_CEC_DevDataBaseChange = 134,
	OE_CEC_NewDeviceDetected = 135,
	OE_CEC_Text4UserReady = 136,
	OE_ChangeInputToHDMI = 137,
	OE_ChangeInputToHDMI2 = 138,
	OE_ChangeInputToHDMI3 = 139,
	OE_CloseCaptionOff = 140,// Turn off CC
	OE_CloseCaptionOn = 141,// Turn on CC
	OE_Decoder_Main = 142,
	OE_Decoder_Pip = 143,
	OE_DigitalInput_Main = 144,
	OE_DigitalInput_Pip = 145,
	OE_DisplayBlockedChannelNum = 146,// parental blocked channel number display
	OE_DisplayOff = 147,// Turn off display only (e.g. Audio is still on)
	OE_DrawVolumeSlider = 148,
	OE_EraseBlockedChannelNum = 149,// parental blocked channel number display
	OE_GoingToSleep = 150,// Sleep alarm is going off
	OE_HardPowerUp_Main = 151,
	OE_HardPowerUp_Pip = 152,
	OE_HideCECString = 153,
	OE_Idle = 154,
	OE_LowPower_Main = 155,
	OE_LowPower_Pip = 156,
	OE_MultiPipOff = 157,// Turn off Multi pip
	OE_NoSignal_Main = 158,// Video mode selected but no proper signal detected
	OE_NoneKey = 159,
	OE_OSDPort_4kx2k = 160,
	OE_OverlappedMode_Main = 161,
	OE_OverlappedMode_Pip = 162,
	OE_Overlapped_Main = 163,// Input timing overlapped
	OE_Overlapped_Pip = 164,// Input timing overlapped
	OE_PipIsNotAllowed = 165,// due to bandwith restriction or other reason PIP is not allowed in current condition
	OE_PowerDownNow = 166,// System power now
	OE_PowerSaveBegin = 167,// Sent when the system enters the power saving mode
	OE_PowerSaveEnd = 168,// Sent when the system exists power saving mode
	OE_PowerSavingNow = 169,// System in power saving mode now
	OE_RemoveMenu_Pip = 170,
	OE_RemoveSplashScreen = 171,
	OE_ScanFinished = 172,
	OE_ShowCECString = 173,
	OE_StartPowerDown = 174,// System about to enter power down
	OE_StartPowerSaving = 175,// System about to enter power saving
	OE_SundBox_OSD_Disable = 176,
	OE_SundBox_OSD_Eanble = 177,
	OE_SyncDetected_Pip = 178,
	OE_SyncPresent_Main = 179,// Sync present but not stable timing
	OE_SyncPresent_Pip = 180,// Sync present but not stable timing
	OE_SystemAudioStatusChanged = 181,
	OE_TV_AutoScanCompleted = 182,// TV tuner auto channel scan end
	OE_TV_AutoScanStart = 183,// TV tuner auto channel scan start
	OE_TV_ChannelBlocked = 184,// Channel always blocked - independent of XDS data
	OE_TV_ChannelChanged = 185,// TV tuner channel number changed
	OE_TV_ChannelUnBlocked = 186,// Unblock Blocked Channel - independent of XDS data
	OE_TV_ManualScanCompleted = 187,
	OE_TV_ManualScanStart = 188,
	OE_TV_ProgramBlocked = 189,// Used with TV Rating when channel is blocked
	OE_TV_ProgramUnBlocked = 190,// Unblock the display after changing channel from a blocked channel to an unblocked channel
	OE_TeletextOff = 191,
	OE_TtxStatusDisplayOn = 192,
	OE_USBUpStreamChange = 193,
	OE_UpdateMultiPipChannel = 194,// Update multi pip channel number for a specific window
	OE_VPort_Main = 195,
	OE_VPort_Pip = 196,
	OE_VWD_Enable = 197,
	OE_VWD_Lost = 198
} UserEvents;



#ifdef WB_ENABLE_DEBUG_INFO_EVENTS
char ROM* ROM ROM WB_DEBUG_INFO_EVENTS[];
#endif //WB_ENABLE_DEBUG_INFO_EVENTS

#define EVENT_OE_EnterState_DECLARED 
#define EVENT_OE_ExitState_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_RIGHT_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_MENU_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_DOWN_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_UP_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_ENTER_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_LEFT_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_SOURCE_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_POWER_DECLARED 
#define EVENT_OET_OsdCustomTimer_DECLARED 
#define EVENT_OE_NoSync_Main_DECLARED 
#define EVENT_OE_TransitionComplete_DECLARED 
#define EVENT_OE_ValidMode_Main_DECLARED 
#define EVENT_OET_OSDRedrawTimer_DECLARED 
#define EVENT_OET_InfoTimer_DECLARED 
#define EVENT_OET_OSD_Timeout_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_MENU_RELEASE_DECLARED 
#define EVENT_OE_IspStatusChanged_DECLARED 
#define EVENT_OE_NoCable_Main_DECLARED 
#define EVENT_OET_OSDCustomPIPTimer_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_EXIT_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_ENTER_RELEASE_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_SOURCE_RELEASE_DECLARED 
#define EVENT_OE_RemoveOSD_DECLARED 
#define EVENT_OE_OutOfRange_Main_DECLARED 
#define EVENT_OE_CMD_PowerSwitch_DECLARED 
#define EVENT_OE_HardLock_DECLARED 
#define EVENT_OE_InvalidMode_Main_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_ASPECTRATIOPIP_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_FREEZE_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_YPbPr_DECLARED 
#define EVENT_OE_PseudoMode_Main_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_MUTE_DECLARED 
#define EVENT_OE_OutOfRange_Pip_DECLARED 
#define EVENT_OET_InputIconTimer_DECLARED 
#define EVENT_OE_NoSync_Pip_DECLARED 
#define EVENT_OE_ValidMode_Pip_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_PIP_DECLARED 
#define EVENT_OE_EnterFactoryMenu_DECLARED 
#define EVENT_OE_SyncDetected_Main_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_PreMode_DECLARED 
#define EVENT_OE_BoardIDStart_DECLARED 
#define EVENT_OE_NoCable_Pip_DECLARED 
#define EVENT_OE_ShowInfo_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_AV_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_AV2_DECLARED 
#define EVENT_OE_Auto_Pressed_DECLARED 
#define EVENT_OE_EnterPowerDeepSleep_DECLARED 
#define EVENT_OE_RemoveMenu_Main_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_VOL_DOWN_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_VOL_UP_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_DISPLAY_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_DP_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_HDMI_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_UP_RELEASE_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_VGA_DECLARED 
#define EVENT_OE_AutoAdjustCompleted_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_AUTO_DECLARED 
#define EVENT_OET_AlertTimer_DECLARED 
#define EVENT_OE_DiagnosticTestPattern_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_DOWN_AR1_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_DVI_DECLARED 
#define EVENT_OE_ModeUnstable_Main_DECLARED 
#define EVENT_OE_PseudoMode_Pip_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_PIP_SOURCE_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_SWAP_DECLARED 
#define EVENT_OET_DiagnosticTestPatternTimer_DECLARED 
#define EVENT_OE_ExitPowerDeepSleep_DECLARED 
#define EVENT_OE_HaveCable_Main_DECLARED 
#define EVENT_OE_InvalidMode_Pip_DECLARED 
#define EVENT_OE_OsdTimeout_DECLARED 
#define EVENT_OE_AutoAdjustStart_DECLARED 
#define EVENT_OE_NoCableTimer_DECLARED 
#define EVENT_OE_PIPIconShow_DECLARED 
#define EVENT_OE_PIPMHide_DECLARED 
#define EVENT_OE_SplashScreen_DECLARED 
#define EVENT_OET_LCDConditionTimer_DECLARED 
#define EVENT_OET_OSD_IconShow_DECLARED 
#define EVENT_OET_OSD_IconShow_PIP_DECLARED 
#define EVENT_OET_OSD_MsgShow_PIP_DECLARED 
#define EVENT_OET_PIPMUpdateTimer_DECLARED 
#define EVENT_OE_AutoColorCompleted_DECLARED 
#define EVENT_OE_WakeUp_DECLARED 
#define EVENT_POE_OsdStartup_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_DOWN_RELEASE_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_SPLIT_DECLARED 
#define EVENT_OET_NoSyncTimer_DECLARED 
#define EVENT_OET_OsdHardLockTimer_DECLARED 
#define EVENT_OE_AnyKey_DECLARED 
#define EVENT_OE_DisplayOn_DECLARED 
#define EVENT_OE_Enter_Pressed_DECLARED 
#define EVENT_OE_ExitPowerSaving_DECLARED 
#define EVENT_OE_IconShow_DECLARED 
#define EVENT_OE_OSDTimeout_DECLARED 
#define EVENT_OE_StopLCDCondition_DECLARED 
#define EVENT_OE_UpdateMuteIcon_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_EIGHT_DECLARED 
#define EVENT_OEK_KEY_LOGICAL_MENU_DELAY_DECLARED 
#define EVENT_OET_AutoConfigTimer_DECLARED 
#define EVENT_OE_AutoColorFailed_DECLARED 
#define EVENT_OE_BoardIDEnd_DECLARED 
#define EVENT_OE_ExitFactoryMenu_DECLARED 
#define EVENT_OE_ForcePowerSaving_DECLARED 
#define EVENT_OE_IconHide_DECLARED 
#define EVENT_OE_IspAutoDetected_DECLARED 
#define EVENT_OE_MinuteUpdate_DECLARED 
#define EVENT_OE_ModeUnstable_Pip_DECLARED 
#define EVENT_OE_NoSignal_Pip_DECLARED 
#define EVENT_OE_PIPIconHide_DECLARED 
#define EVENT_OE_PIPMShow_DECLARED 
#define EVENT_OE_PIPMessages_DECLARED 
#define EVENT_OE_PowerUp_DECLARED 
#define EVENT_OE_SystemStartUp_DECLARED 
#define EVENT_OE_UnFreeze_DECLARED 
#define EVENT_OE_UpdateEnergyStar_DECLARED 
#define EVENT_OE_ADCCalibrationCompleted_DECLARED 
#define EVENT_OE_AnalogInput_Main_DECLARED 
#define EVENT_OE_AnalogInput_Pip_DECLARED 
#define EVENT_OE_AnyEvent_DECLARED 
#define EVENT_OE_AspectRatioUpdate_DECLARED 
#define EVENT_OE_AudioMute_DECLARED 
#define EVENT_OE_AudioOn_DECLARED 
#define EVENT_OE_AudioPCM_Message_DECLARED 
#define EVENT_OE_AudioSourceChanged_DECLARED 
#define EVENT_OE_AudioTypeChanged_DECLARED 
#define EVENT_OE_AutoAdjustComplete_DECLARED 
#define EVENT_OE_AutoAdjustFailed_DECLARED 
#define EVENT_OE_BrightnessGray_DECLARED 
#define EVENT_OE_CEC_Command_Failed_DECLARED 
#define EVENT_OE_CEC_Command_OK_DECLARED 
#define EVENT_OE_CEC_Command_Pwr_Off_DECLARED 
#define EVENT_OE_CEC_Command_Pwr_On_DECLARED 
#define EVENT_OE_CEC_DevDataBaseChange_DECLARED 
#define EVENT_OE_CEC_NewDeviceDetected_DECLARED 
#define EVENT_OE_CEC_Text4UserReady_DECLARED 
#define EVENT_OE_ChangeInputToHDMI_DECLARED 
#define EVENT_OE_ChangeInputToHDMI2_DECLARED 
#define EVENT_OE_ChangeInputToHDMI3_DECLARED 
#define EVENT_OE_CloseCaptionOff_DECLARED 
#define EVENT_OE_CloseCaptionOn_DECLARED 
#define EVENT_OE_Decoder_Main_DECLARED 
#define EVENT_OE_Decoder_Pip_DECLARED 
#define EVENT_OE_DigitalInput_Main_DECLARED 
#define EVENT_OE_DigitalInput_Pip_DECLARED 
#define EVENT_OE_DisplayBlockedChannelNum_DECLARED 
#define EVENT_OE_DisplayOff_DECLARED 
#define EVENT_OE_DrawVolumeSlider_DECLARED 
#define EVENT_OE_EraseBlockedChannelNum_DECLARED 
#define EVENT_OE_GoingToSleep_DECLARED 
#define EVENT_OE_HardPowerUp_Main_DECLARED 
#define EVENT_OE_HardPowerUp_Pip_DECLARED 
#define EVENT_OE_HideCECString_DECLARED 
#define EVENT_OE_Idle_DECLARED 
#define EVENT_OE_LowPower_Main_DECLARED 
#define EVENT_OE_LowPower_Pip_DECLARED 
#define EVENT_OE_MultiPipOff_DECLARED 
#define EVENT_OE_NoSignal_Main_DECLARED 
#define EVENT_OE_NoneKey_DECLARED 
#define EVENT_OE_OSDPort_4kx2k_DECLARED 
#define EVENT_OE_OverlappedMode_Main_DECLARED 
#define EVENT_OE_OverlappedMode_Pip_DECLARED 
#define EVENT_OE_Overlapped_Main_DECLARED 
#define EVENT_OE_Overlapped_Pip_DECLARED 
#define EVENT_OE_PipIsNotAllowed_DECLARED 
#define EVENT_OE_PowerDownNow_DECLARED 
#define EVENT_OE_PowerSaveBegin_DECLARED 
#define EVENT_OE_PowerSaveEnd_DECLARED 
#define EVENT_OE_PowerSavingNow_DECLARED 
#define EVENT_OE_RemoveMenu_Pip_DECLARED 
#define EVENT_OE_RemoveSplashScreen_DECLARED 
#define EVENT_OE_ScanFinished_DECLARED 
#define EVENT_OE_ShowCECString_DECLARED 
#define EVENT_OE_StartPowerDown_DECLARED 
#define EVENT_OE_StartPowerSaving_DECLARED 
#define EVENT_OE_SundBox_OSD_Disable_DECLARED 
#define EVENT_OE_SundBox_OSD_Eanble_DECLARED 
#define EVENT_OE_SyncDetected_Pip_DECLARED 
#define EVENT_OE_SyncPresent_Main_DECLARED 
#define EVENT_OE_SyncPresent_Pip_DECLARED 
#define EVENT_OE_SystemAudioStatusChanged_DECLARED 
#define EVENT_OE_TV_AutoScanCompleted_DECLARED 
#define EVENT_OE_TV_AutoScanStart_DECLARED 
#define EVENT_OE_TV_ChannelBlocked_DECLARED 
#define EVENT_OE_TV_ChannelChanged_DECLARED 
#define EVENT_OE_TV_ChannelUnBlocked_DECLARED 
#define EVENT_OE_TV_ManualScanCompleted_DECLARED 
#define EVENT_OE_TV_ManualScanStart_DECLARED 
#define EVENT_OE_TV_ProgramBlocked_DECLARED 
#define EVENT_OE_TV_ProgramUnBlocked_DECLARED 
#define EVENT_OE_TeletextOff_DECLARED 
#define EVENT_OE_TtxStatusDisplayOn_DECLARED 
#define EVENT_OE_USBUpStreamChange_DECLARED 
#define EVENT_OE_UpdateMultiPipChannel_DECLARED 
#define EVENT_OE_VPort_Main_DECLARED 
#define EVENT_OE_VPort_Pip_DECLARED 
#define EVENT_OE_VWD_Enable_DECLARED 
#define EVENT_OE_VWD_Lost_DECLARED 

/*

Begin block defined in libs

#define SAT_CB_00_EVT_SHIFT		0x0003
#define SAT_CB_10_EVT_SHIFT		0x0002
#define SAT_CB_11_MAC_SHIFT		0x0002

#define SAT_CB_00_EVT_MASK		(BIT3 | BIT4 | BIT5)
#define SAT_CB_00_ACT_MASK		(BIT0 | BIT1 | BIT2)

#define SAT_CB_10_EVT_MASK		(BIT2 | BIT3 | BIT4 | BIT5)
#define SAT_CB_10_CND_MASK		(BIT0 | BIT1)

#define SAT_CB_11_MAC_MASK		(BIT2 | BIT3 | BIT4)
#define SAT_CB_11_CND_MASK		(BIT0 | BIT1)
#define SAT_CB_11_ATREF		(BIT5)
#define SAT_CB_11_ATREF_MASK		(BIT4 | BIT3 | BIT2 | BIT1 | BIT0)

#define SAT_CB_MASK		(BIT7 | BIT6)

#define Fit_00(Event,Action)		(((Event) << SAT_CB_00_EVT_SHIFT) | (Action))
#define Fit_10(Event,CndCtrl)		(((Event) << SAT_CB_10_EVT_SHIFT) | (CndCtrl))
#define Fit_11(CndCtrl, MultiActn)		(((MultiActn) << SAT_CB_11_MAC_SHIFT) | (CndCtrl))



End block defined in libs*/

#define OSD_WB_USED		
#define NO_OPERAND		0

// States enum definition
typedef enum 
{
	SID_DefaultState = 0,// SID_DefaultState
	SID_ValidMode_State = 1,// SID_ValidMode_State
	SID_PowerDeepSleepState = 2,// SID_PowerDeepSleepState
	SID_PowerSavingState = 3,// SID_PowerSavingState
	SID_ForcePowerSavingState = 4,// SID_ForcePowerSavingState
	SID_BurnInModeState = 5,// SID_BurnInModeState
	SID_PowerOffState = 6,// SID_PowerOffState
	SID_SplashScreenAthena = 7,// SID_SplashScreenAthena
	SID_Main_Dialog = 8,// SID_Main_Dialog
	SID_Control_Dialog = 9,// SID_Control_Dialog
	SID_PortChange_Dialog = 10,// SID_PortChange_Dialog
	SID_MessagesDialog = 11,// SID_MessagesDialog
	SID_LockDialog = 12,// SID_LockDialog
	SID_FlyingDialog = 13,// SID_FlyingDialog
	SID_LogoFlyDialog = 14,// SID_LogoFlyDialog
	SID_NoFlyingDialog = 15,// SID_NoFlyingDialog
	SID_LCDCondition = 16,// SID_LCDCondition
	SID_PBPMainMessages = 17,// SID_PBPMainMessages
	SID_FactoryModeDialog = 18,// SID_FactoryModeDialog
	SID_DiagnosticTestPatternDialog = 19,// SID_DiagnosticTestPatternDialog
	SID_InfoDisplay = 20,// SID_InfoDisplay
	SID_PipModeStates = 21,// SID_PipModeStates
	SID_YesNoStateDlg = 22,// SID_YesNoStateDlg
	SID_TransitionToDefaultState = 23,// SID_TransitionToDefaultState
	SID_TransferOsdState = 24,// SID_TransferOsdState
	SID_PIPWaitState = 25,// SID_PIPWaitState
	SID_PIPOnScreenState = 26,// SID_PIPOnScreenState
	SID_VideoOnScreenState = 27,// SID_VideoOnScreenState
	SID_VideoWaitState = 28,// SID_VideoWaitState
	SID_LanguageUpdateState = 29,// SID_LanguageUpdateState
	SID_FlyWindowWaitState = 30,// SID_FlyWindowWaitState
	SID_FactoryResetState = 31,// SID_FactoryResetState
	SID_WBUpdateState = 32,// SID_WBUpdateState
	SID_LCDConditionUpdate = 33,// SID_LCDConditionUpdate
	SID_ImageResetState = 34,// SID_ImageResetState
	SID_AudioResetState = 35,// SID_AudioResetState
	SID_DiagnosticTestPatternState = 36,// SID_DiagnosticTestPatternState
	SID_AutoReturnWaitForSi71C65A88 = 37,// SID_AutoReturnWaitForSignalReady
	SID_RedrawPIPInfoWaitState = 38,// SID_RedrawPIPInfoWaitState
	SID_NoSyncTemp = 39,// SID_NoSyncTemp
	SID_InvLOGO_ZDT = 40,// SID_InvLOGO_ZDT
	SID_SplashScreenBmp = 41,// SID_SplashScreenBmp
	SID_TopLeftBmp = 42,// SID_TopLeftBmp
	SID_TopRightBmp = 43,// SID_TopRightBmp
	SID_BottomLeftBmp = 44,// SID_BottomLeftBmp
	SID_BottomRightBmp = 45,// SID_BottomRightBmp
	SID_SubmenuBGTectLeft = 46,// SID_SubmenuBGTectLeft
	SID_SubmenuBGRectTop = 47,// SID_SubmenuBGRectTop
	SID_SubmenuBGRectBottom = 48,// SID_SubmenuBGRectBottom
	SID_ButtomBGTect = 49,// SID_ButtomBGTect
	SID_MainMenu = 50,// SID_MainMenu
	SID_MiddleLeftBmp = 51,// SID_MiddleLeftBmp
	SID_MiddleBmp = 52,// SID_MiddleBmp
	SID_MiddleRightBmp = 53,// SID_MiddleRightBmp
	SID_Project_CustomNameTxt = 54,// SID_Project_CustomNameTxt
	SID_TimingInfo_Pxp = 55,// SID_TimingInfo_Pxp
	SID_ButtomLineRect = 56,// SID_ButtomLineRect
	SID_ImageButtonBmp = 57,// SID_ImageButtonBmp
	SID_DisplayButtonBmp = 58,// SID_DisplayButtonBmp
	SID_PxpSettingBmp = 59,// SID_PxpSettingBmp
	SID_AudioButtonBmp = 60,// SID_AudioButtonBmp
	SID_SetupButtonBmp = 61,// SID_SetupButtonBmp
	SID_FacctoryModeBtn = 62,// SID_FacctoryModeBtn
	SID_MainSourceText = 63,// SID_MainSourceText
	SID_Main_VGABmp = 64,// SID_Main_VGABmp
	SID_Main_DVIBmp = 65,// SID_Main_DVIBmp
	SID_Main_DPBmp = 66,// SID_Main_DPBmp
	SID_Main_HDMIBmp = 67,// SID_Main_HDMIBmp
	SID_Main_CVBSBmp = 68,// SID_Main_CVBSBmp
	SID_Main_YPbPrBmp = 69,// SID_Main_YPbPrBmp
	SID_TimingInfo_Main = 70,// SID_TimingInfo_Main
	SID_PxpSourceText = 71,// SID_PxpSourceText
	SID_Pxp_VGA_Bmp = 72,// SID_Pxp_VGA_Bmp
	SID_Pxp_DVIBmp = 73,// SID_Pxp_DVIBmp
	SID_Pxp_DPBmp = 74,// SID_Pxp_DPBmp
	SID_Pxp_HDMIBmp = 75,// SID_Pxp_HDMIBmp
	SID_Pxp_CVBSBmp = 76,// SID_Pxp_CVBSBmp
	SID_Pxp_YPbPrBmp = 77,// SID_Pxp_YPbPrBmp
	SID_ImageTitleTxt = 78,// SID_ImageTitleTxt
	SID_ImageMenuState = 79,// SID_ImageMenuState
	SID_AdvancedVideoCentri3B615A36 = 80,// SID_AdvancedVideoCentricMenuState
	SID_AdvancedPCCentricMenuState = 81,// SID_AdvancedPCCentricMenuState
	SID_ColorMenuState = 82,// SID_ColorMenuState
	SID_ColorTempMenuState = 83,// SID_ColorTempMenuState
	SID_ColorTempState = 84,// SID_ColorTempState
	SID_ColorTempUserMenuState = 85,// SID_ColorTempUserMenuState
	SID_ColorSpaceMenuState = 86,// SID_ColorSpaceMenuState
	SID_Color6axisSaruration = 87,// SID_Color6axisSaruration
	SID_AutoAdjustmentButton = 88,// SID_AutoAdjustmentButton
	SID_BrightnessButton = 89,// SID_BrightnessButton
	SID_ContrastButton = 90,// SID_ContrastButton
	SID_SharpnessButton = 91,// SID_SharpnessButton
	SID_PresetModeButton = 92,// SID_PresetModeButton
	SID_GeometricButton = 93,// SID_GeometricButton
	SID_AutoAdjArrow = 94,// SID_AutoAdjArrow
	SID_ColorArrow = 95,// SID_ColorArrow
	SID_GeometricArrow = 96,// SID_GeometricArrow
	SID_BrightnessSlider = 97,// SID_BrightnessSlider
	SID_BrightnessLV = 98,// SID_BrightnessLV
	SID_ContrastSlider = 99,// SID_ContrastSlider
	SID_ContrastLV = 100,// SID_ContrastLV
	SID_SharpnessSlider = 101,// SID_SharpnessSlider
	SID_SharpnessLV = 102,// SID_SharpnessLV
	SID_AutoAdjustmentLeftBmp = 103,// SID_AutoAdjustmentLeftBmp
	SID_AutoAdjustmentRightBmp = 104,// SID_AutoAdjustmentRightBmp
	SID_BrightnessLeftBmp = 105,// SID_BrightnessLeftBmp
	SID_BrightnessRightBmp = 106,// SID_BrightnessRightBmp
	SID_ContrastLeftBmp = 107,// SID_ContrastLeftBmp
	SID_ContrastRightBmp = 108,// SID_ContrastRightBmp
	SID_SharpnessLeftBmp = 109,// SID_SharpnessLeftBmp
	SID_SharpnessRightBmp = 110,// SID_SharpnessRightBmp
	SID_ColorLeftBmp = 111,// SID_ColorLeftBmp
	SID_ColorRightBmp = 112,// SID_ColorRightBmp
	SID_GeometricLeftBmp = 113,// SID_GeometricLeftBmp
	SID_GeometricRightBmp = 114,// SID_GeometricRightBmp
	SID_NoiseReductionButton = 115,// SID_NoiseReductionButton
	SID_FleshToneButton = 116,// SID_FleshToneButton
	SID_DynamicContrastButton = 117,// SID_DynamicContrastButton
	SID_FleshToneSettingDButton = 118,// SID_FleshToneSettingDButton
	SID_DynamicConstrastSettingLV = 119,// SID_DynamicConstrastSettingLV
	SID_NoiseReductionArrow = 120,// SID_NoiseReductionArrow
	SID_DynamicContrastSettingArrow = 121,// SID_DynamicContrastSettingArrow
	SID_FleshToneSettingArrow = 122,// SID_FleshToneSettingArrow
	SID_NoiseReductionLeftBmp = 123,// SID_NoiseReductionLeftBmp
	SID_NoisdeReductionRightBmp = 124,// SID_NoisdeReductionRightBmp
	SID_FleshToneLeftBmp = 125,// SID_FleshToneLeftBmp
	SID_FleshToneRightBmp = 126,// SID_FleshToneRightBmp
	SID_PCCentricLeftBmp = 127,// SID_PCCentricLeftBmp
	SID_PCCentricRightBmp = 128,// SID_PCCentricRightBmp
	SID_FleshToneSettingLeftBmp = 129,// SID_FleshToneSettingLeftBmp
	SID_FleshToneSettingRightBmp = 130,// SID_FleshToneSettingRightBmp
	SID_DynamicContrastSett30770878 = 131,// SID_DynamicContrastSettingLeftBmp
	SID_DynamicContrastSett7D4EF9C2 = 132,// SID_DynamicContrastSettingRightBmp
	SID_HStartButton = 133,// SID_HStartButton
	SID_HStartSlider = 134,// SID_HStartSlider
	SID_HStartLV = 135,// SID_HStartLV
	SID_VStartButton = 136,// SID_VStartButton
	SID_VStartSlider = 137,// SID_VStartSlider
	SID_VStartLV = 138,// SID_VStartLV
	SID_ClocksButton = 139,// SID_ClocksButton
	SID_ClocksLineSlider = 140,// SID_ClocksLineSlider
	SID_ClocksLineLV = 141,// SID_ClocksLineLV
	SID_PhaseButton = 142,// SID_PhaseButton
	SID_PhaseSlider = 143,// SID_PhaseSlider
	SID_PhaseLV = 144,// SID_PhaseLV
	SID_HStartLeftBmp = 145,// SID_HStartLeftBmp
	SID_HStartRightBmp = 146,// SID_HStartRightBmp
	SID_ClocksLeftBmp = 147,// SID_ClocksLeftBmp
	SID_ClocksRightBmp = 148,// SID_ClocksRightBmp
	SID_ClocksLeftBmp1 = 149,// SID_ClocksLeftBmp1
	SID_ClocksRightBmp1 = 150,// SID_ClocksRightBmp1
	SID_PhaseLeftBmp = 151,// SID_PhaseLeftBmp
	SID_PhaseRightBmp = 152,// SID_PhaseRightBmp
	SID_Color6axisSaturationButton = 153,// SID_Color6axisSaturationButton
	SID_Color6axisHueButton = 154,// SID_Color6axisHueButton
	SID_Color6axisSaturationArrow = 155,// SID_Color6axisSaturationArrow
	SID_Color6axisHueArrow = 156,// SID_Color6axisHueArrow
	SID_Color6axisSaturationLeftBmp = 157,// SID_Color6axisSaturationLeftBmp
	SID_Color6axisSaturatioD4D39F31 = 158,// SID_Color6axisSaturationRightBmp
	SID_Color6axisHueLeftBmp = 159,// SID_Color6axisHueLeftBmp
	SID_Color6axisHueRightBmp = 160,// SID_Color6axisHueRightBmp
	SID_PresetModeBtn = 161,// SID_PresetModeBtn
	SID_Standard_Btn = 162,// SID_Standard_Btn
	SID_ColorTemp = 163,// SID_ColorTemp
	SID_UserButton = 164,// SID_UserButton
	SID_ColorTempArrow = 165,// SID_ColorTempArrow
	SID_UserColorArrow = 166,// SID_UserColorArrow
	SID_ColorTempLeftBmp1 = 167,// SID_ColorTempLeftBmp1
	SID_ColorTempRightBmp1 = 168,// SID_ColorTempRightBmp1
	SID_Standard_BtnLeftBmp = 169,// SID_Standard_BtnLeftBmp
	SID_Standard_BtnRightBmp = 170,// SID_Standard_BtnRightBmp
	SID_ColorTempLeftBmp2 = 171,// SID_ColorTempLeftBmp2
	SID_ColorTempRightBmp2 = 172,// SID_ColorTempRightBmp2
	SID_UserLeftBmp = 173,// SID_UserLeftBmp
	SID_UserRightBmp = 174,// SID_UserRightBmp
	SID_ColorTempBtn = 175,// SID_ColorTempBtn
	SID_CT_6500KButton = 176,// SID_CT_6500KButton
	SID_CT_9300KButton = 177,// SID_CT_9300KButton
	SID_CT_10000KButton = 178,// SID_CT_10000KButton
	SID_ColorTempLeftBmp11 = 179,// SID_ColorTempLeftBmp11
	SID_ColorTempRightBmp11 = 180,// SID_ColorTempRightBmp11
	SID_6500KLeftBmp = 181,// SID_6500KLeftBmp
	SID_6500KRightBmp = 182,// SID_6500KRightBmp
	SID_9300KLeftBmp = 183,// SID_9300KLeftBmp
	SID_9300KRightBmp = 184,// SID_9300KRightBmp
	SID__10000KLeftBmp = 185,// SID__10000KLeftBmp
	SID__10000KRightBmp = 186,// SID__10000KRightBmp
	SID_RedGainButton = 187,// SID_RedGainButton
	SID_GreenGainButton = 188,// SID_GreenGainButton
	SID_BlueGainButton = 189,// SID_BlueGainButton
	SID_RedOffButton = 190,// SID_RedOffButton
	SID_GreenOffButton = 191,// SID_GreenOffButton
	SID_BlueOffButton = 192,// SID_BlueOffButton
	SID_RedGainSlider = 193,// SID_RedGainSlider
	SID_RedGainLV = 194,// SID_RedGainLV
	SID_GreenGainSlider = 195,// SID_GreenGainSlider
	SID_GreenGainLV = 196,// SID_GreenGainLV
	SID_BlueGainSlider = 197,// SID_BlueGainSlider
	SID_BlueGainLV = 198,// SID_BlueGainLV
	SID_RedOffSlider = 199,// SID_RedOffSlider
	SID_RedOffLV = 200,// SID_RedOffLV
	SID_GreenOffSlider = 201,// SID_GreenOffSlider
	SID_GreenOffLV = 202,// SID_GreenOffLV
	SID_BlueOffSlider = 203,// SID_BlueOffSlider
	SID_BlueOffLV = 204,// SID_BlueOffLV
	SID_RedLeftBmp = 205,// SID_RedLeftBmp
	SID_RedRightBmp = 206,// SID_RedRightBmp
	SID_GreenLeftBmp = 207,// SID_GreenLeftBmp
	SID_GreenRightBmp = 208,// SID_GreenRightBmp
	SID_BlueLeftBmp = 209,// SID_BlueLeftBmp
	SID_BlueRightBmp = 210,// SID_BlueRightBmp
	SID_RedLeftBmp1 = 211,// SID_RedLeftBmp1
	SID_RedRightBmp1 = 212,// SID_RedRightBmp1
	SID_GreenLeftBmp1 = 213,// SID_GreenLeftBmp1
	SID_GreenRightBmp1 = 214,// SID_GreenRightBmp1
	SID_BlueLeftBmp1 = 215,// SID_BlueLeftBmp1
	SID_BlueRightBmp1 = 216,// SID_BlueRightBmp1
	SID_ColorSpacButtonTitle = 217,// SID_ColorSpacButtonTitle
	SID_sRGBBtn = 218,// SID_sRGBBtn
	SID_Adobe98 = 219,// SID_Adobe98
	SID_ColorSpacButtonTitleBmpLeft = 220,// SID_ColorSpacButtonTitleBmpLeft
	SID_ColorSpacButtonTitl4218E8C0 = 221,// SID_ColorSpacButtonTitleBmpRight
	SID_UserLeftBmp1 = 222,// SID_UserLeftBmp1
	SID_UserRightBmp1 = 223,// SID_UserRightBmp1
	SID_User98LeftBmp = 224,// SID_User98LeftBmp
	SID_UserRigh98tBmp = 225,// SID_UserRigh98tBmp
	SID_SaturationTitle = 226,// SID_SaturationTitle
	SID_RedSaturationButton = 227,// SID_RedSaturationButton
	SID_GreenSaturationButton = 228,// SID_GreenSaturationButton
	SID_BlueSaturationButton = 229,// SID_BlueSaturationButton
	SID_YellowSaturationButton = 230,// SID_YellowSaturationButton
	SID_MagentaSaturationButton = 231,// SID_MagentaSaturationButton
	SID_CyanSaturationButton = 232,// SID_CyanSaturationButton
	SID_ColorSpacButtonTitlA5C373BB = 233,// SID_ColorSpacButtonTitleBmpLeft1
	SID_ColorSpacButtonTitl13C102A7 = 234,// SID_ColorSpacButtonTitleBmpRight1
	SID_RedLeftBmp2 = 235,// SID_RedLeftBmp2
	SID_RedRightBmp2 = 236,// SID_RedRightBmp2
	SID_GreenLeftBmp2 = 237,// SID_GreenLeftBmp2
	SID_GreenRightBmp2 = 238,// SID_GreenRightBmp2
	SID_BlueLeftBmp2 = 239,// SID_BlueLeftBmp2
	SID_BlueRightBmp2 = 240,// SID_BlueRightBmp2
	SID_YellowLeftBmp = 241,// SID_YellowLeftBmp
	SID_YellowRightBmp = 242,// SID_YellowRightBmp
	SID_MagentaLeftBmp = 243,// SID_MagentaLeftBmp
	SID_MagentaRightBmp = 244,// SID_MagentaRightBmp
	SID_CyanSaturationLeftBmp = 245,// SID_CyanSaturationLeftBmp
	SID_CyanSaturationRightBmp = 246,// SID_CyanSaturationRightBmp
	SID_DisplayTitleTxt = 247,// SID_DisplayTitleTxt
	SID_DisplayMenuState = 248,// SID_DisplayMenuState
	SID_PanelProtectButton = 249,// SID_PanelProtectButton
	SID_PanelProtectSettingButton = 250,// SID_PanelProtectSettingButton
	SID_NoiseReductionButton1 = 251,// SID_NoiseReductionButton1
	SID_DynamicNRModeSettingButton = 252,// SID_DynamicNRModeSettingButton
	SID_ImageRorateButton = 253,// SID_ImageRorateButton
	SID_ImageRotateSettingButton = 254,// SID_ImageRotateSettingButton
	SID_OSDRotateButton = 255,// SID_OSDRotateButton
	SID_OSDRotateSettingButton = 256,// SID_OSDRotateSettingButton
	SID_PanelProtectArrow = 257,// SID_PanelProtectArrow
	SID_TNRArrow = 258,// SID_TNRArrow
	SID_ImageRotateArrow = 259,// SID_ImageRotateArrow
	SID_OSDRotateArrow = 260,// SID_OSDRotateArrow
	SID_PanelProtectLeftBmp = 261,// SID_PanelProtectLeftBmp
	SID_PanelProtectRightBmp = 262,// SID_PanelProtectRightBmp
	SID_PanelProtectSettingLeftBmp = 263,// SID_PanelProtectSettingLeftBmp
	SID_PanelProtectSettingRightBmp = 264,// SID_PanelProtectSettingRightBmp
	SID_PanelProtectOFF = 265,// SID_PanelProtectOFF
	SID_PanelProtectON = 266,// SID_PanelProtectON
	SID_NoiseReductionLeftBmp1 = 267,// SID_NoiseReductionLeftBmp1
	SID_NoiseReductionRightBmp = 268,// SID_NoiseReductionRightBmp
	SID_DynamicNRModeSettingLeftBmp = 269,// SID_DynamicNRModeSettingLeftBmp
	SID_DynamicNRModeSettin6F11100C = 270,// SID_DynamicNRModeSettingRightBmp
	SID_PictureFreezeLeftBmp = 271,// SID_PictureFreezeLeftBmp
	SID_PictureFreezeRightBmp = 272,// SID_PictureFreezeRightBmp
	SID_ImageRotateSettingLeftBmp = 273,// SID_ImageRotateSettingLeftBmp
	SID_ImageRotateSettingRightBmp = 274,// SID_ImageRotateSettingRightBmp
	SID_Non_Rotation = 275,// SID_Non_Rotation
	SID_H_Rotatiion = 276,// SID_H_Rotatiion
	SID_V_Rotation = 277,// SID_V_Rotation
	SID_HV_Rotationn = 278,// SID_HV_Rotationn
	SID_ImageSizeLeftBmp = 279,// SID_ImageSizeLeftBmp
	SID_ImageSizeRightBmp = 280,// SID_ImageSizeRightBmp
	SID_OSDRotateSettingLeftBmp = 281,// SID_OSDRotateSettingLeftBmp
	SID_OSDRotateSettingRightBmp = 282,// SID_OSDRotateSettingRightBmp
	SID_Non_Rotation1 = 283,// SID_Non_Rotation1
	SID_OSD_90 = 284,// SID_OSD_90
	SID_OSD_180 = 285,// SID_OSD_180
	SID_OSD_270 = 286,// SID_OSD_270
	SID_PxpSettingTxt = 287,// SID_PxpSettingTxt
	SID_PIPMenuState = 288,// SID_PIPMenuState
	SID_PIPModeButton = 289,// SID_PIPModeButton
	SID_PIPModeSettingButton = 290,// SID_PIPModeSettingButton
	SID_PIPPositionButton = 291,// SID_PIPPositionButton
	SID_PIPPositionSettingButton = 292,// SID_PIPPositionSettingButton
	SID_PipSourceButton = 293,// SID_PipSourceButton
	SID_PipSourceSettingButton = 294,// SID_PipSourceSettingButton
	SID_Pxp_ContrastBtn = 295,// SID_Pxp_ContrastBtn
	SID_Pxp_ContrastSlider = 296,// SID_Pxp_ContrastSlider
	SID_Pxp_ContrastLV = 297,// SID_Pxp_ContrastLV
	SID_Pxp_BlendBtn = 298,// SID_Pxp_BlendBtn
	SID_Pxp_BlendSlider = 299,// SID_Pxp_BlendSlider
	SID_Pxp_BlendLV = 300,// SID_Pxp_BlendLV
	SID_PipModeSettingArrow = 301,// SID_PipModeSettingArrow
	SID_PipPositionSettingArrow = 302,// SID_PipPositionSettingArrow
	SID_PipSourceSettingArrow = 303,// SID_PipSourceSettingArrow
	SID_PIPModeLeftBmp = 304,// SID_PIPModeLeftBmp
	SID_PIPModeRightBmp = 305,// SID_PIPModeRightBmp
	SID_PIPModeSettingLeftBmp = 306,// SID_PIPModeSettingLeftBmp
	SID_PIPModeSettingRightBmp = 307,// SID_PIPModeSettingRightBmp
	SID_Mode_NoPxp = 308,// SID_Mode_NoPxp
	SID_Mode_Small = 309,// SID_Mode_Small
	SID_Mode_Large = 310,// SID_Mode_Large
	SID_Mode_SideBySide = 311,// SID_Mode_SideBySide
	SID_Mode_SideBySideTall = 312,// SID_Mode_SideBySideTall
	SID_Mode_Medium = 313,// SID_Mode_Medium
	SID_Mode_Huge = 314,// SID_Mode_Huge
	SID_Mode_Flexible = 315,// SID_Mode_Flexible
	SID_PxpInfoRect = 316,// SID_PxpInfoRect
	SID_PIPPositionLeftBmp = 317,// SID_PIPPositionLeftBmp
	SID_PIPPositionRightBmp = 318,// SID_PIPPositionRightBmp
	SID_PIPPositionSettingLeftBmp = 319,// SID_PIPPositionSettingLeftBmp
	SID_PIPPositionSettingRightBmp = 320,// SID_PIPPositionSettingRightBmp
	SID_Pxp_PosTL = 321,// SID_Pxp_PosTL
	SID_Pxp_PosTR = 322,// SID_Pxp_PosTR
	SID_Pxp_PosBL = 323,// SID_Pxp_PosBL
	SID_Pxp_PosBR = 324,// SID_Pxp_PosBR
	SID_Pxp_PosFlexible = 325,// SID_Pxp_PosFlexible
	SID_PipSourceLeftBmp = 326,// SID_PipSourceLeftBmp
	SID_PipSourceRightBmp = 327,// SID_PipSourceRightBmp
	SID_PIPModeSettingLeftBmp1 = 328,// SID_PIPModeSettingLeftBmp1
	SID_PIPModeSettingRightBmp1 = 329,// SID_PIPModeSettingRightBmp1
	SID_VGA = 330,// SID_VGA
	SID_DVI = 331,// SID_DVI
	SID_HDMI = 332,// SID_HDMI
	SID_DP1 = 333,// SID_DP1
	SID_Component = 334,// SID_Component
	SID_CVBS1 = 335,// SID_CVBS1
	SID_CVBS2 = 336,// SID_CVBS2
	SID_AspectRatioLeftBmp = 337,// SID_AspectRatioLeftBmp
	SID_AspectRatioRightBmp = 338,// SID_AspectRatioRightBmp
	SID_AspectRatioLeftBmp1 = 339,// SID_AspectRatioLeftBmp1
	SID_AspectRatioRightBmp1 = 340,// SID_AspectRatioRightBmp1
	SID_AudioTitleTxt = 341,// SID_AudioTitleTxt
	SID_AudioMenuState = 342,// SID_AudioMenuState
	SID_MuteButton = 343,// SID_MuteButton
	SID_VolumeButton = 344,// SID_VolumeButton
	SID_AudionputButton = 345,// SID_AudionputButton
	SID_AudioOutputButton = 346,// SID_AudioOutputButton
	SID_MuteSettingArrow = 347,// SID_MuteSettingArrow
	SID_VolumeLV = 348,// SID_VolumeLV
	SID_AudioMainInputSettingArrow = 349,// SID_AudioMainInputSettingArrow
	SID_AudioMainoutputSettingArrow = 350,// SID_AudioMainoutputSettingArrow
	SID_MuteSettingButton = 351,// SID_MuteSettingButton
	SID_VolumeSlider = 352,// SID_VolumeSlider
	SID_MainInputSettingButton = 353,// SID_MainInputSettingButton
	SID_MainOutputSettingButton = 354,// SID_MainOutputSettingButton
	SID_AudioMuteLeftBmp = 355,// SID_AudioMuteLeftBmp
	SID_AudioMuteRightBmp = 356,// SID_AudioMuteRightBmp
	SID_VolumeLeftBmp = 357,// SID_VolumeLeftBmp
	SID_VolumeRightBmp = 358,// SID_VolumeRightBmp
	SID_MILeftBmp = 359,// SID_MILeftBmp
	SID_MIRightBmp = 360,// SID_MIRightBmp
	SID_MOLeftBmp = 361,// SID_MOLeftBmp
	SID_MORightBmp = 362,// SID_MORightBmp
	SID_MuteSettingLeftBmp = 363,// SID_MuteSettingLeftBmp
	SID_MuteSettingRightBmp = 364,// SID_MuteSettingRightBmp
	SID_MISettingLeftBmp = 365,// SID_MISettingLeftBmp
	SID_MISettingRightBmp = 366,// SID_MISettingRightBmp
	SID_AudInput_MainAuto = 367,// SID_AudInput_MainAuto
	SID_AudInput_LineIn = 368,// SID_AudInput_LineIn
	SID_AudInput_PipAuto = 369,// SID_AudInput_PipAuto
	SID_MOSettingLeftBmp = 370,// SID_MOSettingLeftBmp
	SID_MOSettingRightBmp = 371,// SID_MOSettingRightBmp
	SID_AudOutput_LineOut = 372,// SID_AudOutput_LineOut
	SID_Audoutput_HP = 373,// SID_Audoutput_HP
	SID_SetupTitleTxt = 374,// SID_SetupTitleTxt
	SID_SetupMenuState = 375,// SID_SetupMenuState
	SID_Setup_WithoutLock = 376,// SID_Setup_WithoutLock
	SID_LanguageButton = 377,// SID_LanguageButton
	SID_LanguageSettingButton = 378,// SID_LanguageSettingButton
	SID_OSDTimerButton = 379,// SID_OSDTimerButton
	SID_OSDBlendButton = 380,// SID_OSDBlendButton
	SID_DPSwitchButton = 381,// SID_DPSwitchButton
	SID_DPSwitchButtonSettingButton = 382,// SID_DPSwitchButtonSettingButton
	SID_FactoryResetButton = 383,// SID_FactoryResetButton
	SID_FactoryResetSettingButton = 384,// SID_FactoryResetSettingButton
	SID_OSDTimer_SliderButton = 385,// SID_OSDTimer_SliderButton
	SID_OSDTimer_LongValue = 386,// SID_OSDTimer_LongValue
	SID_OSDBlend_SliderButton = 387,// SID_OSDBlend_SliderButton
	SID_OSDBlend_LongValue = 388,// SID_OSDBlend_LongValue
	SID_LanguageArrow = 389,// SID_LanguageArrow
	SID_DPSwitchButtonSettingArrow = 390,// SID_DPSwitchButtonSettingArrow
	SID_FactoryResetSettingArrow = 391,// SID_FactoryResetSettingArrow
	SID_LanguageLeftBmp = 392,// SID_LanguageLeftBmp
	SID_LanguageRightBmp = 393,// SID_LanguageRightBmp
	SID_LanguageSettingLeftBmp = 394,// SID_LanguageSettingLeftBmp
	SID_LanguageSettingRightBmp = 395,// SID_LanguageSettingRightBmp
	SID_OSDTimerLeftBmp = 396,// SID_OSDTimerLeftBmp
	SID_OSDTimerRightBmp = 397,// SID_OSDTimerRightBmp
	SID_PIPLeftBmp = 398,// SID_PIPLeftBmp
	SID_PIPRightBmp = 399,// SID_PIPRightBmp
	SID_DPSLeftBmp = 400,// SID_DPSLeftBmp
	SID_DPSRightBmp = 401,// SID_DPSRightBmp
	SID_DPSwitchButtonSettiA07A122B = 402,// SID_DPSwitchButtonSettingLeftBmp
	SID_DPSwitchButtonSetti1B42403D = 403,// SID_DPSwitchButtonSettingRightBmp
	SID_FactoryResetLeftBmp = 404,// SID_FactoryResetLeftBmp
	SID_FactoryResetRightBmp = 405,// SID_FactoryResetRightBmp
	SID_FactoryResetSettingLeftBmp = 406,// SID_FactoryResetSettingLeftBmp
	SID_FactoryResetSettingRightBmp = 407,// SID_FactoryResetSettingRightBmp
	SID_FR_Yes = 408,// SID_FR_Yes
	SID_FR_No = 409,// SID_FR_No
	SID_FactoryTitleTxt = 410,// SID_FactoryTitleTxt
	SID_FactoryMode = 411,// SID_FactoryMode
	SID_IspThruVidoMenuState = 412,// SID_IspThruVidoMenuState
	SID_EnterFactoryButton = 413,// SID_EnterFactoryButton
	SID_LogoCtrlButton = 414,// SID_LogoCtrlButton
	SID_UartSelectButton = 415,// SID_UartSelectButton
	SID_UartBaudRateButton = 416,// SID_UartBaudRateButton
	SID_IspThruDisplayButton = 417,// SID_IspThruDisplayButton
	SID_LogoCtrl_SettingButton = 418,// SID_LogoCtrl_SettingButton
	SID_UartSelect_Setting = 419,// SID_UartSelect_Setting
	SID_UartBaudRate_Setting = 420,// SID_UartBaudRate_Setting
	SID_FactoryModeArrow = 421,// SID_FactoryModeArrow
	SID_IspThruDisplayArrow1 = 422,// SID_IspThruDisplayArrow1
	SID_LOGO_ON = 423,// SID_LOGO_ON
	SID_LOGO_OFF = 424,// SID_LOGO_OFF
	SID_UartSel_Uart0 = 425,// SID_UartSel_Uart0
	SID_UartSel_Uart1 = 426,// SID_UartSel_Uart1
	SID_UartBR_9600 = 427,// SID_UartBR_9600
	SID_UartBR_19200 = 428,// SID_UartBR_19200
	SID_UartBR_38400 = 429,// SID_UartBR_38400
	SID_UartBR_57600 = 430,// SID_UartBR_57600
	SID_UartBR_115200 = 431,// SID_UartBR_115200
	SID_PressKeyToExit = 432,// SID_PressKeyToExit
	SID_IspStep1 = 433,// SID_IspStep1
	SID_IspStep2 = 434,// SID_IspStep2
	SID_IspStep3 = 435,// SID_IspStep3
	SID_IspStep4 = 436,// SID_IspStep4
	SID_IspStep5 = 437,// SID_IspStep5
	SID_IspStep51 = 438,// SID_IspStep51
	SID_InputVersion = 439,// SID_InputVersion
	SID_VTxt1 = 440,// SID_VTxt1
	SID_MajorVerionLV1 = 441,// SID_MajorVerionLV1
	SID_DotTxt1 = 442,// SID_DotTxt1
	SID_MinorVerLv1 = 443,// SID_MinorVerLv1
	SID_RCTxt1 = 444,// SID_RCTxt1
	SID_RCLv1 = 445,// SID_RCLv1
	SID_Confirm2UpdateFw = 446,// SID_Confirm2UpdateFw
	SID_IspStep6 = 447,// SID_IspStep6
	SID_IspStep7 = 448,// SID_IspStep7
	SID_IspStep7_Percent = 449,// SID_IspStep7_Percent
	SID_IspStep7_PercentMark = 450,// SID_IspStep7_PercentMark
	SID_IspStepResult1 = 451,// SID_IspStepResult1
	SID_IspStepResult2 = 452,// SID_IspStepResult2
	SID_IspStepResult3 = 453,// SID_IspStepResult3
	SID_IspStepResult4 = 454,// SID_IspStepResult4
	SID_IspStepResult5 = 455,// SID_IspStepResult5
	SID_IspStepResult51 = 456,// SID_IspStepResult51
	SID_IspStepResult6 = 457,// SID_IspStepResult6
	SID_IspStepResult7 = 458,// SID_IspStepResult7
	SID_IspStepFinal_Sucess = 459,// SID_IspStepFinal_Sucess
	SID_IspStepFinal_Failed = 460,// SID_IspStepFinal_Failed
	SID_PressKeyToRestart = 461,// SID_PressKeyToRestart
	SID_Yes = 462,// SID_Yes
	SID_No = 463,// SID_No
	SID_WaitForRelease = 464,// SID_WaitForRelease
	SID_Control_Dialog_Valid = 465,// SID_Control_Dialog_Valid
	SID_MainBGRect = 466,// SID_MainBGRect
	SID_TopLeftBmp1 = 467,// SID_TopLeftBmp1
	SID_BottomLeftBmp1 = 468,// SID_BottomLeftBmp1
	SID_TopRightBmp1 = 469,// SID_TopRightBmp1
	SID_BottomRightBmp1 = 470,// SID_BottomRightBmp1
	SID_SubmenuBGRect = 471,// SID_SubmenuBGRect
	SID_BrightnessControlState = 472,// SID_BrightnessControlState
	SID_ContrastControlState = 473,// SID_ContrastControlState
	SID_HueControlState = 474,// SID_HueControlState
	SID_SaturationControlState = 475,// SID_SaturationControlState
	SID_SharpnessControlState = 476,// SID_SharpnessControlState
	SID_VolumeControlState = 477,// SID_VolumeControlState
	SID_ACM3SaturationRedCoEE14D710 = 478,// SID_ACM3SaturationRedControlState
	SID_ACM3SaturationGreenC17A2DDA = 479,// SID_ACM3SaturationGreenControlState
	SID_ACM3SaturationBlueCC729AAF3 = 480,// SID_ACM3SaturationBlueControlState
	SID_ACM3SaturationYelloB4832B63 = 481,// SID_ACM3SaturationYellowControlState
	SID_ACM3SaturationMagen1ED11B5F = 482,// SID_ACM3SaturationMagentaControlState
	SID_ACM3SaturationCyanC172CF1C2 = 483,// SID_ACM3SaturationCyanControlState
	SID_ACM3HueRedControlState = 484,// SID_ACM3HueRedControlState
	SID_ACM3HueGreenControlState = 485,// SID_ACM3HueGreenControlState
	SID_ACM3HueBlueControlState = 486,// SID_ACM3HueBlueControlState
	SID_ACM3HueYellowControlState = 487,// SID_ACM3HueYellowControlState
	SID_ACM3HueMagentaControlState = 488,// SID_ACM3HueMagentaControlState
	SID_ACM3HueCyanControlState = 489,// SID_ACM3HueCyanControlState
	SID_ACM3LumaRedControlState = 490,// SID_ACM3LumaRedControlState
	SID_ACM3LumaGreenControlState = 491,// SID_ACM3LumaGreenControlState
	SID_ACM3LumaBlueControlState = 492,// SID_ACM3LumaBlueControlState
	SID_ACM3LumaYellowControlState = 493,// SID_ACM3LumaYellowControlState
	SID_ACM3LumaMagentaControlState = 494,// SID_ACM3LumaMagentaControlState
	SID_ACM3LumaCyanControlState1 = 495,// SID_ACM3LumaCyanControlState1
	SID_BrightnessControlButton = 496,// SID_BrightnessControlButton
	SID_BrightnessControlSlider = 497,// SID_BrightnessControlSlider
	SID_BrightnessControlLV = 498,// SID_BrightnessControlLV
	SID_ContrastControlButton = 499,// SID_ContrastControlButton
	SID_ContrastControlSlider = 500,// SID_ContrastControlSlider
	SID_ContrastControlLV = 501,// SID_ContrastControlLV
	SID_HueControlButton = 502,// SID_HueControlButton
	SID_HueControlSlider = 503,// SID_HueControlSlider
	SID_HueControlLV = 504,// SID_HueControlLV
	SID_SaturationControlButton = 505,// SID_SaturationControlButton
	SID_SaturationControlSlider = 506,// SID_SaturationControlSlider
	SID_SaturationControlLV = 507,// SID_SaturationControlLV
	SID_SharpnessControlButton = 508,// SID_SharpnessControlButton
	SID_SharpnessControlSlider = 509,// SID_SharpnessControlSlider
	SID_SharpnessControlLV = 510,// SID_SharpnessControlLV
	SID_VolumeControlButton = 511,// SID_VolumeControlButton
	SID_VolumeControlSlider = 512,// SID_VolumeControlSlider
	SID_VolumeControlLV = 513,// SID_VolumeControlLV
	SID_ACMSaturationTxt = 514,// SID_ACMSaturationTxt
	SID_ACMSaturationRedConBDFA2A90 = 515,// SID_ACMSaturationRedControlButton
	SID_ACMSaturationRedCon80B2E369 = 516,// SID_ACMSaturationRedControlSlider
	SID_ACMSaturationRedControlLV = 517,// SID_ACMSaturationRedControlLV
	SID_ACMSaturationTxt1 = 518,// SID_ACMSaturationTxt1
	SID_ACMSaturationGreenC51837157 = 519,// SID_ACMSaturationGreenControlButton
	SID_ACMSaturationGreenC448E0F6B = 520,// SID_ACMSaturationGreenControlSlider
	SID_ACMSaturationGreenControlLV = 521,// SID_ACMSaturationGreenControlLV
	SID_ACMSaturationTxt2 = 522,// SID_ACMSaturationTxt2
	SID_ACMSaturationBlueCoB937C20F = 523,// SID_ACMSaturationBlueControlButton
	SID_ACMSaturationBlueCoA29652CF = 524,// SID_ACMSaturationBlueControlSlider
	SID_ACMSaturationBlueControlLV = 525,// SID_ACMSaturationBlueControlLV
	SID_ACMSaturationTxt3 = 526,// SID_ACMSaturationTxt3
	SID_ACMSaturationYellowEDCC3954 = 527,// SID_ACMSaturationYellowControlButton
	SID_ACMSaturationYellow33167B48 = 528,// SID_ACMSaturationYellowControlSlider
	SID_ACMSaturationYellow2475C9D3 = 529,// SID_ACMSaturationYellowControlLV
	SID_ACMSaturationTxt4 = 530,// SID_ACMSaturationTxt4
	SID_ACMSaturationMagent9FB731DA = 531,// SID_ACMSaturationMagentaControlButton
	SID_ACMSaturationMagent96AB8628 = 532,// SID_ACMSaturationMagentaControlSlider
	SID_ACMSaturationMagent836BBCBA = 533,// SID_ACMSaturationMagentaControlLV
	SID_ACMSaturationTxt5 = 534,// SID_ACMSaturationTxt5
	SID_ACMSaturationCyanCo06501B77 = 535,// SID_ACMSaturationCyanControlButton
	SID_ACMSaturationCyanCoD9C79FB3 = 536,// SID_ACMSaturationCyanControlSlider
	SID_ACMSaturationCyanControlLV = 537,// SID_ACMSaturationCyanControlLV
	SID_ACMHueTxt = 538,// SID_ACMHueTxt
	SID_ACMHueRedControlButton = 539,// SID_ACMHueRedControlButton
	SID_ACMHueRedControlSlider = 540,// SID_ACMHueRedControlSlider
	SID_ACMHueRedControlLV = 541,// SID_ACMHueRedControlLV
	SID_ACMHueTxt1 = 542,// SID_ACMHueTxt1
	SID_ACMHueGreenControlButton = 543,// SID_ACMHueGreenControlButton
	SID_ACMHueGreenControlSlider = 544,// SID_ACMHueGreenControlSlider
	SID_ACMHueGreenControlLV = 545,// SID_ACMHueGreenControlLV
	SID_ACMHueTxt2 = 546,// SID_ACMHueTxt2
	SID_ACMHueBlueControlButton = 547,// SID_ACMHueBlueControlButton
	SID_ACMHueBlueControlSlider = 548,// SID_ACMHueBlueControlSlider
	SID_ACMHueBlueControlLV = 549,// SID_ACMHueBlueControlLV
	SID_ACMHueTxt3 = 550,// SID_ACMHueTxt3
	SID_ACMHueYellowControlButton = 551,// SID_ACMHueYellowControlButton
	SID_ACMHueYellowControlSlider = 552,// SID_ACMHueYellowControlSlider
	SID_ACMHueYellowControlLV = 553,// SID_ACMHueYellowControlLV
	SID_ACMHueTxt4 = 554,// SID_ACMHueTxt4
	SID_ACMHueMagentaControlButton = 555,// SID_ACMHueMagentaControlButton
	SID_ACMHueMagentaControlSlider = 556,// SID_ACMHueMagentaControlSlider
	SID_ACMHueMagentaControlLV = 557,// SID_ACMHueMagentaControlLV
	SID_ACMHueTxt5 = 558,// SID_ACMHueTxt5
	SID_ACMHueCyanControlButton = 559,// SID_ACMHueCyanControlButton
	SID_ACMHueCyanControlSlider = 560,// SID_ACMHueCyanControlSlider
	SID_ACMHueCyanControlLV = 561,// SID_ACMHueCyanControlLV
	SID_ACMLumaTxt = 562,// SID_ACMLumaTxt
	SID_ACMLumaRedControlButton = 563,// SID_ACMLumaRedControlButton
	SID_ACMLumaRedControlSlider = 564,// SID_ACMLumaRedControlSlider
	SID_ACMLumaRedControlLV = 565,// SID_ACMLumaRedControlLV
	SID_ACMLumaTxt1 = 566,// SID_ACMLumaTxt1
	SID_ACMLumaGreenControlButton = 567,// SID_ACMLumaGreenControlButton
	SID_ACMLumaGreenControlSlider = 568,// SID_ACMLumaGreenControlSlider
	SID_ACMLumaGreenControlLV = 569,// SID_ACMLumaGreenControlLV
	SID_ACMLumaTxt2 = 570,// SID_ACMLumaTxt2
	SID_ACMLumaBlueControlButton = 571,// SID_ACMLumaBlueControlButton
	SID_ACMLumaBlueControlSlider = 572,// SID_ACMLumaBlueControlSlider
	SID_ACMLumaBlueControlLV = 573,// SID_ACMLumaBlueControlLV
	SID_ACMLumaTxt3 = 574,// SID_ACMLumaTxt3
	SID_ACMLumaYellowControlButton = 575,// SID_ACMLumaYellowControlButton
	SID_ACMLumaYellowControlSlider = 576,// SID_ACMLumaYellowControlSlider
	SID_ACMLumaYellowControlLV = 577,// SID_ACMLumaYellowControlLV
	SID_ACMLumaTxt4 = 578,// SID_ACMLumaTxt4
	SID_ACMLumaMagentaControlButton = 579,// SID_ACMLumaMagentaControlButton
	SID_ACMLumaMagentaControlSlider = 580,// SID_ACMLumaMagentaControlSlider
	SID_ACMLumaMagentaControlLV = 581,// SID_ACMLumaMagentaControlLV
	SID_ACMLumaTxt5 = 582,// SID_ACMLumaTxt5
	SID_ACMLumaCyanControlButton = 583,// SID_ACMLumaCyanControlButton
	SID_ACMLumaCyanControlSlider = 584,// SID_ACMLumaCyanControlSlider
	SID_ACMLumaCyanControlLV = 585,// SID_ACMLumaCyanControlLV
	SID_PortChangeTopRightBmp = 586,// SID_PortChangeTopRightBmp
	SID_PortChangeBottomtBmp = 587,// SID_PortChangeBottomtBmp
	SID_PortChangeDividerLeftBmp = 588,// SID_PortChangeDividerLeftBmp
	SID_PortChangeDividerMiddleBmp = 589,// SID_PortChangeDividerMiddleBmp
	SID_PortChangeDividerRightBmp = 590,// SID_PortChangeDividerRightBmp
	SID_TopRect = 591,// SID_TopRect
	SID_BGLeftBmp = 592,// SID_BGLeftBmp
	SID_PortChange = 593,// SID_PortChange
	SID_Port_VGABtn = 594,// SID_Port_VGABtn
	SID_Port_DPBtn = 595,// SID_Port_DPBtn
	SID_Port_DVIBtn = 596,// SID_Port_DVIBtn
	SID_Port_HDMIBtn = 597,// SID_Port_HDMIBtn
	SID_Port_YPbPrBtn = 598,// SID_Port_YPbPrBtn
	SID_Port_CVBS1 = 599,// SID_Port_CVBS1
	SID_Port_CVBS2 = 600,// SID_Port_CVBS2
	SID_PortChangeArrowUpBmp = 601,// SID_PortChangeArrowUpBmp
	SID_PortChangeArrowDownBmp = 602,// SID_PortChangeArrowDownBmp
	SID_MainPortChangeTitleTxt = 603,// SID_MainPortChangeTitleTxt
	SID_PxpPortChangeTitleTxt = 604,// SID_PxpPortChangeTitleTxt
	SID_PortChangeLeftBmp = 605,// SID_PortChangeLeftBmp
	SID_PortChangeRightBmp = 606,// SID_PortChangeRightBmp
	SID_InvPortChange = 607,// SID_InvPortChange
	SID_PortChangeLeftBmp1 = 608,// SID_PortChangeLeftBmp1
	SID_PortChangeRightBmp1 = 609,// SID_PortChangeRightBmp1
	SID_InvPortChange1 = 610,// SID_InvPortChange1
	SID_PortChangeLeftBmp2 = 611,// SID_PortChangeLeftBmp2
	SID_PortChangeRightBmp2 = 612,// SID_PortChangeRightBmp2
	SID_InvPortChange2 = 613,// SID_InvPortChange2
	SID_PortChangeLeftBmp3 = 614,// SID_PortChangeLeftBmp3
	SID_PortChangeRightBmp3 = 615,// SID_PortChangeRightBmp3
	SID_InvPortChange3 = 616,// SID_InvPortChange3
	SID_PortChangeLeftBmp4 = 617,// SID_PortChangeLeftBmp4
	SID_PortChangeRightBmp4 = 618,// SID_PortChangeRightBmp4
	SID_InvPortChange4 = 619,// SID_InvPortChange4
	SID_PortChangeLeftBmp5 = 620,// SID_PortChangeLeftBmp5
	SID_PortChangeRightBmp5 = 621,// SID_PortChangeRightBmp5
	SID_InvPortChange5 = 622,// SID_InvPortChange5
	SID_PortChangeLeftBmp6 = 623,// SID_PortChangeLeftBmp6
	SID_PortChangeRightBmp6 = 624,// SID_PortChangeRightBmp6
	SID_InvPortChange6 = 625,// SID_InvPortChange6
	SID_MesInvState = 626,// SID_MesInvState
	SID_BackRectangle = 627,// SID_BackRectangle
	SID_CenterBackgroundRectangle = 628,// SID_CenterBackgroundRectangle
	SID_OutOfRangeInvisibleState = 629,// SID_OutOfRangeInvisibleState
	SID_NoSignalInvisibleState = 630,// SID_NoSignalInvisibleState
	SID_AutoAdjustment = 631,// SID_AutoAdjustment
	SID_EnteringPowerSavein51D3EC9B = 632,// SID_EnteringPowerSaveinvisibleState
	SID_PowerSavePCMessageState = 633,// SID_PowerSavePCMessageState
	SID_PowerSaveVideoMessageState = 634,// SID_PowerSaveVideoMessageState
	SID_InputSource = 635,// SID_InputSource
	SID_PIPInvisibleState = 636,// SID_PIPInvisibleState
	SID_PIPNotAvailableInviB661D755 = 637,// SID_PIPNotAvailableInvisibleState
	SID_PIPNotAvailableMainB6C51062 = 638,// SID_PIPNotAvailableMainMenuInvisibleState
	SID_AutoColorNGState = 639,// SID_AutoColorNGState
	SID_AutoColorOKState = 640,// SID_AutoColorOKState
	SID_TopLeftBmp2 = 641,// SID_TopLeftBmp2
	SID_TopRightBmp2 = 642,// SID_TopRightBmp2
	SID_ChooseInputInvisibleState = 643,// SID_ChooseInputInvisibleState
	SID_VGAInputInvisibleState = 644,// SID_VGAInputInvisibleState
	SID_DVI1InputInvisibleState = 645,// SID_DVI1InputInvisibleState
	SID_DisplayPortInvisibleState = 646,// SID_DisplayPortInvisibleState
	SID_DisplayPort3InvisibleState = 647,// SID_DisplayPort3InvisibleState
	SID_HDMIInvisibleState = 648,// SID_HDMIInvisibleState
	SID_NoInputSignalInvisibleState = 649,// SID_NoInputSignalInvisibleState
	SID_NoSignalText = 650,// SID_NoSignalText
	SID_VGABitmap = 651,// SID_VGABitmap
	SID_NoSignalText1 = 652,// SID_NoSignalText1
	SID_DVIBitmap = 653,// SID_DVIBitmap
	SID_NoSignalStaticText = 654,// SID_NoSignalStaticText
	SID_DPBitmap = 655,// SID_DPBitmap
	SID_NoSignalText2 = 656,// SID_NoSignalText2
	SID_DP3Bitmap = 657,// SID_DP3Bitmap
	SID_NoSignalStaticText1 = 658,// SID_NoSignalStaticText1
	SID_HDMIBitmap = 659,// SID_HDMIBitmap
	SID_MessageText = 660,// SID_MessageText
	SID_NosiText = 661,// SID_NosiText
	SID_Nosi2Text = 662,// SID_Nosi2Text
	SID_Nosi3Text = 663,// SID_Nosi3Text
	SID_Nosi4Text = 664,// SID_Nosi4Text
	SID_VGABitmapButton = 665,// SID_VGABitmapButton
	SID_DVIBitmapButton = 666,// SID_DVIBitmapButton
	SID_DisplayPortBitmapButton = 667,// SID_DisplayPortBitmapButton
	SID_DP3BitmapButton = 668,// SID_DP3BitmapButton
	SID_HDMIBitmapButton = 669,// SID_HDMIBitmapButton
	SID_CompositeBitmap = 670,// SID_CompositeBitmap
	SID_ComponentBitmap = 671,// SID_ComponentBitmap
	SID_AutoAdjustmentText = 672,// SID_AutoAdjustmentText
	SID_AutoAdjustmentState = 673,// SID_AutoAdjustmentState
	SID_AutoTuneState = 674,// SID_AutoTuneState
	SID_EnteringPowerText = 675,// SID_EnteringPowerText
	SID_VGABitmap1 = 676,// SID_VGABitmap1
	SID_DVIBitmap1 = 677,// SID_DVIBitmap1
	SID_DPBitmap1 = 678,// SID_DPBitmap1
	SID_DP3Bitmap1 = 679,// SID_DP3Bitmap1
	SID_HDMIBitmap1 = 680,// SID_HDMIBitmap1
	SID_CompositeBitmap1 = 681,// SID_CompositeBitmap1
	SID_ComponentBitmap1 = 682,// SID_ComponentBitmap1
	SID_NosiText1 = 683,// SID_NosiText1
	SID_Nosi2Text1 = 684,// SID_Nosi2Text1
	SID_Nosi3Text1 = 685,// SID_Nosi3Text1
	SID_Nosi4Text1 = 686,// SID_Nosi4Text1
	SID_VGABitmap2 = 687,// SID_VGABitmap2
	SID_DVIBitmap2 = 688,// SID_DVIBitmap2
	SID_DPBitmap2 = 689,// SID_DPBitmap2
	SID_DP3Bitmap2 = 690,// SID_DP3Bitmap2
	SID_HDMIBitmap2 = 691,// SID_HDMIBitmap2
	SID_CompositeBitmap2 = 692,// SID_CompositeBitmap2
	SID_ComponentBitmap2 = 693,// SID_ComponentBitmap2
	SID_NosiText2 = 694,// SID_NosiText2
	SID_Nosi2Text11 = 695,// SID_Nosi2Text11
	SID_Nosi3Text11 = 696,// SID_Nosi3Text11
	SID_CompositeBitmap3 = 697,// SID_CompositeBitmap3
	SID_ComponentBitmap3 = 698,// SID_ComponentBitmap3
	SID_VGAInvisibleState = 699,// SID_VGAInvisibleState
	SID_DVIInvisibleState = 700,// SID_DVIInvisibleState
	SID_DPInvisibleState = 701,// SID_DPInvisibleState
	SID_DP3InvisibleState = 702,// SID_DP3InvisibleState
	SID_HDMIInvisibleState1 = 703,// SID_HDMIInvisibleState1
	SID_VGAStaticText = 704,// SID_VGAStaticText
	SID_VGABitmap3 = 705,// SID_VGABitmap3
	SID_DVIStaticText = 706,// SID_DVIStaticText
	SID_DVIStaticText_Dell2609 = 707,// SID_DVIStaticText_Dell2609
	SID_DVIBitmap3 = 708,// SID_DVIBitmap3
	SID_DPStaticText = 709,// SID_DPStaticText
	SID_DPBitmap3 = 710,// SID_DPBitmap3
	SID_DP3StaticText = 711,// SID_DP3StaticText
	SID_DP3Bitmap3 = 712,// SID_DP3Bitmap3
	SID_HDMIStaticText = 713,// SID_HDMIStaticText
	SID_HDMIBitmap3 = 714,// SID_HDMIBitmap3
	SID_PBPOFFInvisibleState = 715,// SID_PBPOFFInvisibleState
	SID_PIPONInvisibleState = 716,// SID_PIPONInvisibleState
	SID_PBPONInvisibleState = 717,// SID_PBPONInvisibleState
	SID_OFFStaticText = 718,// SID_OFFStaticText
	SID_PIPONStaticText = 719,// SID_PIPONStaticText
	SID_PBPStaticText = 720,// SID_PBPStaticText
	SID_PipNotAvailableStaticText = 721,// SID_PipNotAvailableStaticText
	SID_PipNotAvailableStaticText1 = 722,// SID_PipNotAvailableStaticText1
	SID_NGTextButton = 723,// SID_NGTextButton
	SID_OKTextButton = 724,// SID_OKTextButton
	SID_HardLockinvisibleState = 725,// SID_HardLockinvisibleState
	SID_HardUnLockinvisibleState = 726,// SID_HardUnLockinvisibleState
	SID_LockState = 727,// SID_LockState
	SID_UnLockState = 728,// SID_UnLockState
	SID_LockBitmap = 729,// SID_LockBitmap
	SID_UnLockBitmap = 730,// SID_UnLockBitmap
	SID_LockBitmap1 = 731,// SID_LockBitmap1
	SID_UnLockBitmap1 = 732,// SID_UnLockBitmap1
	SID_FlyInvState = 733,// SID_FlyInvState
	SID_MesFlyState = 734,// SID_MesFlyState
	SID_BackgroundRectangle = 735,// SID_BackgroundRectangle
	SID_CenterBackgroundRectangle1 = 736,// SID_CenterBackgroundRectangle1
	SID_MesFlyWithCD = 737,// SID_MesFlyWithCD
	SID_TopLeftBmp3 = 738,// SID_TopLeftBmp3
	SID_BottomLeftBmp2 = 739,// SID_BottomLeftBmp2
	SID_TopRightBmp3 = 740,// SID_TopRightBmp3
	SID_BottomRightBmp2 = 741,// SID_BottomRightBmp2
	SID_NoCableVGAText = 742,// SID_NoCableVGAText
	SID_NoCableDVIText = 743,// SID_NoCableDVIText
	SID_NoCableDPText = 744,// SID_NoCableDPText
	SID_NoCableDP3Text = 745,// SID_NoCableDP3Text
	SID_NoCableHDMIText = 746,// SID_NoCableHDMIText
	SID_VGANoSignalBitmap = 747,// SID_VGANoSignalBitmap
	SID_DVINoSignalBitmap = 748,// SID_DVINoSignalBitmap
	SID_DPNoSignalBitmap = 749,// SID_DPNoSignalBitmap
	SID_DP3NoSignalBitmap = 750,// SID_DP3NoSignalBitmap
	SID_HDMINoSignalBitmap = 751,// SID_HDMINoSignalBitmap
	SID_CountDownText = 752,// SID_CountDownText
	SID_CountDownText_Hazro = 753,// SID_CountDownText_Hazro
	SID_NoCablePowerDownSlider = 754,// SID_NoCablePowerDownSlider
	SID_LogoFly = 755,// SID_LogoFly
	SID_InvLOGO_ZDT1 = 756,// SID_InvLOGO_ZDT1
	SID_SplashScreenBmp1 = 757,// SID_SplashScreenBmp1
	SID_NoFlyMesInvState = 758,// SID_NoFlyMesInvState
	SID_TempState = 759,// SID_TempState
	SID_BackgroundRectangle1 = 760,// SID_BackgroundRectangle1
	SID_CenterBackgroundRectangle2 = 761,// SID_CenterBackgroundRectangle2
	SID_NoCableVGAText1 = 762,// SID_NoCableVGAText1
	SID_NoCableDVIText1 = 763,// SID_NoCableDVIText1
	SID_NoCableDPText1 = 764,// SID_NoCableDPText1
	SID_NoCableDP3Text1 = 765,// SID_NoCableDP3Text1
	SID_NoCableHDMIText1 = 766,// SID_NoCableHDMIText1
	SID_VGANoSignalBitmap1 = 767,// SID_VGANoSignalBitmap1
	SID_DVINoSignalBitmap1 = 768,// SID_DVINoSignalBitmap1
	SID_DPNoSignalBitmap1 = 769,// SID_DPNoSignalBitmap1
	SID_DP3NoSignalBitmap1 = 770,// SID_DP3NoSignalBitmap1
	SID_HDMINoSignalBitmap1 = 771,// SID_HDMINoSignalBitmap1
	SID_NoCableVGAText11 = 772,// SID_NoCableVGAText11
	SID_NoCableDVIText11 = 773,// SID_NoCableDVIText11
	SID_NoCableDPText11 = 774,// SID_NoCableDPText11
	SID_NoCableDP3Text11 = 775,// SID_NoCableDP3Text11
	SID_NoCableHDMIText11 = 776,// SID_NoCableHDMIText11
	SID_VGANoSignalBitmap11 = 777,// SID_VGANoSignalBitmap11
	SID_DVINoSignalBitmap11 = 778,// SID_DVINoSignalBitmap11
	SID_DPNoSignalBitmap11 = 779,// SID_DPNoSignalBitmap11
	SID_DP3NoSignalBitmap11 = 780,// SID_DP3NoSignalBitmap11
	SID_HDMINoSignalBitmap11 = 781,// SID_HDMINoSignalBitmap11
	SID_TopLeftBmp4 = 782,// SID_TopLeftBmp4
	SID_BottomLeftBmp3 = 783,// SID_BottomLeftBmp3
	SID_TopRightBmp4 = 784,// SID_TopRightBmp4
	SID_BottomRightBmp3 = 785,// SID_BottomRightBmp3
	SID_BackRectangle1 = 786,// SID_BackRectangle1
	SID_LCDCond1 = 787,// SID_LCDCond1
	SID_LCDCond2 = 788,// SID_LCDCond2
	SID_LCDCoditingUpdateState = 789,// SID_LCDCoditingUpdateState
	SID_PBPMainMessagesState = 790,// SID_PBPMainMessagesState
	SID_BackRectangle2 = 791,// SID_BackRectangle2
	SID_CenterBackgroundRectangle3 = 792,// SID_CenterBackgroundRectangle3
	SID_OutOfRangeInvisibleState1 = 793,// SID_OutOfRangeInvisibleState1
	SID_PowerSavePCInvisibleState = 794,// SID_PowerSavePCInvisibleState
	SID_PowerSaveVideoInvis213D5D50 = 795,// SID_PowerSaveVideoInvisibleState
	SID_AutoAdjustment1 = 796,// SID_AutoAdjustment1
	SID_EnteringPowerSavein9135C3D6 = 797,// SID_EnteringPowerSaveinvisibleState1
	SID_TopLeftBmp5 = 798,// SID_TopLeftBmp5
	SID_TopRightBmp5 = 799,// SID_TopRightBmp5
	SID_NosiText3 = 800,// SID_NosiText3
	SID_Nosi2Text2 = 801,// SID_Nosi2Text2
	SID_Nosi3Text2 = 802,// SID_Nosi3Text2
	SID_Nosi4Text2 = 803,// SID_Nosi4Text2
	SID_VGABitmap4 = 804,// SID_VGABitmap4
	SID_DVIBitmap4 = 805,// SID_DVIBitmap4
	SID_DPBitmap4 = 806,// SID_DPBitmap4
	SID_DP3Bitmap4 = 807,// SID_DP3Bitmap4
	SID_HDMIBitmap4 = 808,// SID_HDMIBitmap4
	SID_CompositeBitmap4 = 809,// SID_CompositeBitmap4
	SID_ComponentBitmap4 = 810,// SID_ComponentBitmap4
	SID_NosiText4 = 811,// SID_NosiText4
	SID_Nosi2Text12 = 812,// SID_Nosi2Text12
	SID_Nosi3Text12 = 813,// SID_Nosi3Text12
	SID_CompositeBitmap5 = 814,// SID_CompositeBitmap5
	SID_ComponentBitmap5 = 815,// SID_ComponentBitmap5
	SID_AutoAdjustmentText1 = 816,// SID_AutoAdjustmentText1
	SID_AutoAdjustmentState1 = 817,// SID_AutoAdjustmentState1
	SID_AutoTuneState1 = 818,// SID_AutoTuneState1
	SID_EnteringPowerText1 = 819,// SID_EnteringPowerText1
	SID_VGABitmap5 = 820,// SID_VGABitmap5
	SID_DVIBitmap5 = 821,// SID_DVIBitmap5
	SID_DPBitmap5 = 822,// SID_DPBitmap5
	SID_DP3Bitmap5 = 823,// SID_DP3Bitmap5
	SID_HDMIBitmap5 = 824,// SID_HDMIBitmap5
	SID_CompositeBitmap6 = 825,// SID_CompositeBitmap6
	SID_ComponentBitmap6 = 826,// SID_ComponentBitmap6
	SID_ISBackgroundRectangle = 827,// SID_ISBackgroundRectangle
	SID_TopInfoBackRect = 828,// SID_TopInfoBackRect
	SID_BottomRectangle = 829,// SID_BottomRectangle
	SID_LeftRectangle = 830,// SID_LeftRectangle
	SID_FactoryMode2ndState = 831,// SID_FactoryMode2ndState
	SID_FactoryMode1 = 832,// SID_FactoryMode1
	SID_FW_Date = 833,// SID_FW_Date
	SID_FW_VersionStaticText = 834,// SID_FW_VersionStaticText
	SID_FW_Version = 835,// SID_FW_Version
	SID_PanelNameStaticText = 836,// SID_PanelNameStaticText
	SID_PanelText = 837,// SID_PanelText
	SID_BoardIDStaticTxt = 838,// SID_BoardIDStaticTxt
	SID_BoardIDDynamicText = 839,// SID_BoardIDDynamicText
	SID_DP_speed = 840,// SID_DP_speed
	SID_DPspeedLinkText = 841,// SID_DPspeedLinkText
	SID_DPspeedLaneText = 842,// SID_DPspeedLaneText
	SID_ColorSpace = 843,// SID_ColorSpace
	SID_Infoframe = 844,// SID_Infoframe
	SID_AudioPacket = 845,// SID_AudioPacket
	SID_Audiopacket_Text = 846,// SID_Audiopacket_Text
	SID_SerialNoText = 847,// SID_SerialNoText
	SID_SerialNoDynamic2Text = 848,// SID_SerialNoDynamic2Text
	SID_ExitBtn = 849,// SID_ExitBtn
	SID_AudioSelectBtn = 850,// SID_AudioSelectBtn
	SID_BurninModeBtn = 851,// SID_BurninModeBtn
	SID_AutoColorBtn = 852,// SID_AutoColorBtn
	SID_T10000KBtn = 853,// SID_T10000KBtn
	SID_T9300KText = 854,// SID_T9300KText
	SID_T7500KText = 855,// SID_T7500KText
	SID_T7200KText = 856,// SID_T7200KText
	SID_T6500KText = 857,// SID_T6500KText
	SID_T5700KText = 858,// SID_T5700KText
	SID_T5000KText = 859,// SID_T5000KText
	SID_sRGBText = 860,// SID_sRGBText
	SID_AdobeRGBText = 861,// SID_AdobeRGBText
	SID_BriBaseText = 862,// SID_BriBaseText
	SID_Offset1StaticText = 863,// SID_Offset1StaticText
	SID_Offset2StaticText = 864,// SID_Offset2StaticText
	SID_GainStaticText = 865,// SID_GainStaticText
	SID_EDID_WPText = 866,// SID_EDID_WPText
	SID_BackLightOnTime = 867,// SID_BackLightOnTime
	SID_PanelSSCText = 868,// SID_PanelSSCText
	SID_DCRText = 869,// SID_DCRText
	SID_ResetTimerbuttonText = 870,// SID_ResetTimerbuttonText
	SID_UartSelectBtn = 871,// SID_UartSelectBtn
	SID_ClearUserText = 872,// SID_ClearUserText
	SID_ColorTempTxt = 873,// SID_ColorTempTxt
	SID_AudioSelectTextButton = 874,// SID_AudioSelectTextButton
	SID_BurnOff_OnTextButton = 875,// SID_BurnOff_OnTextButton
	SID_AutoColorOKText = 876,// SID_AutoColorOKText
	SID_T10000K_RCustomTextButton = 877,// SID_T10000K_RCustomTextButton
	SID_T10000K_GCustomTextButton = 878,// SID_T10000K_GCustomTextButton
	SID_T10000K_BCustomTextButton = 879,// SID_T10000K_BCustomTextButton
	SID_T9300K_RCustomTextButton = 880,// SID_T9300K_RCustomTextButton
	SID_T9300K_GCustomTextButton = 881,// SID_T9300K_GCustomTextButton
	SID_T9300K_BCustomTextButton = 882,// SID_T9300K_BCustomTextButton
	SID_T7500K_RCustomTextButton = 883,// SID_T7500K_RCustomTextButton
	SID_T7500K_GCustomTextButton = 884,// SID_T7500K_GCustomTextButton
	SID_T7500K_BCustomTextButton = 885,// SID_T7500K_BCustomTextButton
	SID_T7200K_RCustomTextButton = 886,// SID_T7200K_RCustomTextButton
	SID_T7200K_GCustomTextButton = 887,// SID_T7200K_GCustomTextButton
	SID_T7200K_BCustomTextButton = 888,// SID_T7200K_BCustomTextButton
	SID_T6500K_RCustomTextButton = 889,// SID_T6500K_RCustomTextButton
	SID_T6500K_GCustomTextButton = 890,// SID_T6500K_GCustomTextButton
	SID_T6500K_BCustomTextButton = 891,// SID_T6500K_BCustomTextButton
	SID_T5700K_RCustomTextButton = 892,// SID_T5700K_RCustomTextButton
	SID_T5700K_GCustomTextButton = 893,// SID_T5700K_GCustomTextButton
	SID_T5700K_BCustomTextButton = 894,// SID_T5700K_BCustomTextButton
	SID_T5000K_RCustomTextButton = 895,// SID_T5000K_RCustomTextButton
	SID_T5000K_GCustomTextButton = 896,// SID_T5000K_GCustomTextButton
	SID_T5000K_BCustomTextButton = 897,// SID_T5000K_BCustomTextButton
	SID_sRGB_RCustomTextButton = 898,// SID_sRGB_RCustomTextButton
	SID_sRGB_GCustomTextButton = 899,// SID_sRGB_GCustomTextButton
	SID_sRGB_BCustomTextButton = 900,// SID_sRGB_BCustomTextButton
	SID_AdobeRGB_RCustomTextButton = 901,// SID_AdobeRGB_RCustomTextButton
	SID_AdobeRGB_GCustomTextButton = 902,// SID_AdobeRGB_GCustomTextButton
	SID_AdobeRGB_BCustomTextButton = 903,// SID_AdobeRGB_BCustomTextButton
	SID_BriBase_StandradTextButton = 904,// SID_BriBase_StandradTextButton
	SID_BriBase_testTextButton = 905,// SID_BriBase_testTextButton
	SID_BriBase_sRGB_TextButton = 906,// SID_BriBase_sRGB_TextButton
	SID_BriBase_Adobe_TextButton = 907,// SID_BriBase_Adobe_TextButton
	SID_O1RCustomText = 908,// SID_O1RCustomText
	SID_O1GCustomText = 909,// SID_O1GCustomText
	SID_O1BCustomText = 910,// SID_O1BCustomText
	SID_O2RCustomText = 911,// SID_O2RCustomText
	SID_O2GCustomText = 912,// SID_O2GCustomText
	SID_O2BCustomText = 913,// SID_O2BCustomText
	SID_GainRCustomTextButton = 914,// SID_GainRCustomTextButton
	SID_GainGCustomTextButton = 915,// SID_GainGCustomTextButton
	SID_GainBCustomTextButton = 916,// SID_GainBCustomTextButton
	SID_EDID_WPOff_OnTextButton = 917,// SID_EDID_WPOff_OnTextButton
	SID_T10000K_RCustomLong3096E93B = 918,// SID_T10000K_RCustomLongValueButton
	SID_T10000K_GCustomLongCC367CBD = 919,// SID_T10000K_GCustomLongValueButton
	SID_T10000K_BCustomLong81B5EBD9 = 920,// SID_T10000K_BCustomLongValueButton
	SID_T9300K_RCustomLongVA8B65DF4 = 921,// SID_T9300K_RCustomLongValueButton
	SID_T9300K_GCustomLongV59A219D9 = 922,// SID_T9300K_GCustomLongValueButton
	SID_T9300K_BCustomLongV73BC8FF6 = 923,// SID_T9300K_BCustomLongValueButton
	SID_T7500K_RCustomLongV55A23AD6 = 924,// SID_T7500K_RCustomLongValueButton
	SID_T7500K_GCustomLongV54EF1847 = 925,// SID_T7500K_GCustomLongValueButton
	SID_T7500K_BCustomLongV4ABFE2A1 = 926,// SID_T7500K_BCustomLongValueButton
	SID_T7200K_RCustomLongV81E6658F = 927,// SID_T7200K_RCustomLongValueButton
	SID_T7200K_GCustomLongV0ACFE0F0 = 928,// SID_T7200K_GCustomLongValueButton
	SID_T7200K_BCustomLongV49D7E388 = 929,// SID_T7200K_BCustomLongValueButton
	SID_T6500K_RCustomLongVA04E71F1 = 930,// SID_T6500K_RCustomLongValueButton
	SID_T6500K_GCustomLongV98D621D8 = 931,// SID_T6500K_GCustomLongValueButton
	SID_T6500K_BCustomLongV5346522C = 932,// SID_T6500K_BCustomLongValueButton
	SID_T5700K_RCustomLongV4B40A7FC = 933,// SID_T5700K_RCustomLongValueButton
	SID_T5700K_GCustomLongVC0B8BB0B = 934,// SID_T5700K_GCustomLongValueButton
	SID_T5700K_BCustomLongV5940EA9D = 935,// SID_T5700K_BCustomLongValueButton
	SID_T5000K_RCustomLongV17367407 = 936,// SID_T5000K_RCustomLongValueButton
	SID_T5000K_GCustomLongVB45630B5 = 937,// SID_T5000K_GCustomLongValueButton
	SID_T5000K_BCustomLongV658799EA = 938,// SID_T5000K_BCustomLongValueButton
	SID_sRGB_RCustomLongValueButton = 939,// SID_sRGB_RCustomLongValueButton
	SID_sRGB_GCustomLongValueButton = 940,// SID_sRGB_GCustomLongValueButton
	SID_sRGB_BCustomLongValueButton = 941,// SID_sRGB_BCustomLongValueButton
	SID_AdobeRGB_RCustomLon4F3F1EBD = 942,// SID_AdobeRGB_RCustomLongValueButton
	SID_AdobeRGB_GCustomLon48D153C7 = 943,// SID_AdobeRGB_GCustomLongValueButton
	SID_AdobeRGB_BCustomLon46EC0120 = 944,// SID_AdobeRGB_BCustomLongValueButton
	SID_BriBase_Standrard_V2DF1E25B = 945,// SID_BriBase_Standrard_ValueButton
	SID_BriBase_Text_LongVaC1DC33E1 = 946,// SID_BriBase_Text_LongValueButton
	SID_BriBase_sRGB_LongVaD963BCBC = 947,// SID_BriBase_sRGB_LongValueButton
	SID_BriBase_Adobe_LongV44495420 = 948,// SID_BriBase_Adobe_LongValueButton
	SID_O1RCustomLongValueButton = 949,// SID_O1RCustomLongValueButton
	SID_O1GCustomLongValueButton = 950,// SID_O1GCustomLongValueButton
	SID_O1BCustomLongValueButton = 951,// SID_O1BCustomLongValueButton
	SID_O2RCustomLongValueButton = 952,// SID_O2RCustomLongValueButton
	SID_O2GCustomLongValueButton = 953,// SID_O2GCustomLongValueButton
	SID_O2BCustomLongValueButton = 954,// SID_O2BCustomLongValueButton
	SID_GainRCustomLongValueButton = 955,// SID_GainRCustomLongValueButton
	SID_GainGCustomLongValueButton = 956,// SID_GainGCustomLongValueButton
	SID_GainBCustomLongValueButton = 957,// SID_GainBCustomLongValueButton
	SID_BackLightHoursCusto56356E1B = 958,// SID_BackLightHoursCustomLongValueButton
	SID_HoursText = 959,// SID_HoursText
	SID_BackLightMinutesCus5A6D350F = 960,// SID_BackLightMinutesCustomLongValueButton
	SID_MinutesText = 961,// SID_MinutesText
	SID_AmpText = 962,// SID_AmpText
	SID_AmpLongValue = 963,// SID_AmpLongValue
	SID_PeriodText = 964,// SID_PeriodText
	SID_FreqPeriodLongValue = 965,// SID_FreqPeriodLongValue
	SID_DCROffTextButton = 966,// SID_DCROffTextButton
	SID_UartSelectSettingBtn = 967,// SID_UartSelectSettingBtn
	SID_DiagnosticTestPatteB2EA28B3 = 968,// SID_DiagnosticTestPatterninvisibleState
	SID_DiagnosticTestPatte4F88806A = 969,// SID_DiagnosticTestPatterninvisibleState_R
	SID_DiagnosticTestPatternBitmap = 970,// SID_DiagnosticTestPatternBitmap
	SID_DiagnosticTestPatte2F2E3738 = 971,// SID_DiagnosticTestPatternRectangle
	SID_ResolutionTimingInfo = 972,// SID_ResolutionTimingInfo
	SID_OptResolutionValueS13616CE7 = 973,// SID_OptResolutionValueStaticText_WUXGA
	SID_OptResolutionValueS4D12722A = 974,// SID_OptResolutionValueStaticText_WQXGA
	SID_OptResolutionValueS8AA47FCD = 975,// SID_OptResolutionValueStaticText_2560x1440
	SID_OptResolutionValueSA9412F99 = 976,// SID_OptResolutionValueStaticText_2560x1080
	SID_DiagnosticTestPatte413DEE10 = 977,// SID_DiagnosticTestPatternBitmap1
	SID_DiagnosticTestPatteD0A7FFA2 = 978,// SID_DiagnosticTestPatternRectangle1
	SID_ResolutionTimingInfo1 = 979,// SID_ResolutionTimingInfo1
	SID_OptResolutionValueS9EC7AA18 = 980,// SID_OptResolutionValueStaticText_WUXGA1
	SID_OptResolutionValueS9271C8FB = 981,// SID_OptResolutionValueStaticText_WQXGA1
	SID_OptResolutionValueS24353D1F = 982,// SID_OptResolutionValueStaticText_2560x14401
	SID_OptResolutionValueSEF21D9A1 = 983,// SID_OptResolutionValueStaticText_2560x10801
	SID_DisplayInfo = 984,// SID_DisplayInfo
	SID_DisplayInfoUpdate = 985,// SID_DisplayInfoUpdate
	SID_PresetMode = 986,// SID_PresetMode
	SID_MainSourceTxt = 987,// SID_MainSourceTxt
	SID_MainSourceInputTxt = 988,// SID_MainSourceInputTxt
	SID_MainDTimingInfo = 989,// SID_MainDTimingInfo
	SID_PxpSourceTxt = 990,// SID_PxpSourceTxt
	SID_PipSourceInputTxt = 991,// SID_PipSourceInputTxt
	SID_PxpTimingInfo = 992,// SID_PxpTimingInfo
	SID_BoardIDText = 993,// SID_BoardIDText
	SID_BoardIDValue = 994,// SID_BoardIDValue
	SID_MuteInfoTxt_1080 = 995,// SID_MuteInfoTxt_1080
	SID_MuteBmp_1080 = 996,// SID_MuteBmp_1080
	SID_UnMuteBmp_1080 = 997,// SID_UnMuteBmp_1080
	SID_FreezeDisplayTxt_1080 = 998,// SID_FreezeDisplayTxt_1080
	SID_MainSourceTxt1 = 999,// SID_MainSourceTxt1
	SID_Preset_Standard = 1000,// SID_Preset_Standard
	SID_Preset_MultiMedia = 1001,// SID_Preset_MultiMedia
	SID_Preset_Game = 1002,// SID_Preset_Game
	SID_Preset_Movie = 1003,// SID_Preset_Movie
	SID_Mode_NoPxp1 = 1004,// SID_Mode_NoPxp1
	SID_Mode_Small1 = 1005,// SID_Mode_Small1
	SID_Mode_Large1 = 1006,// SID_Mode_Large1
	SID_Mode_SideBySide1 = 1007,// SID_Mode_SideBySide1
	SID_Mode_Medium1 = 1008,// SID_Mode_Medium1
	SID_Mode_Huge1 = 1009,// SID_Mode_Huge1
	SID_BigMesInvState = 1010,// SID_BigMesInvState
	SID_BackRectangle3 = 1011,// SID_BackRectangle3
	SID_CenterBackRectangle = 1012,// SID_CenterBackRectangle
	SID_FactoryResetOnOffState = 1013,// SID_FactoryResetOnOffState
	SID_LuckMenuOnOffState = 1014,// SID_LuckMenuOnOffState
	SID_DP_MSTState = 1015,// SID_DP_MSTState
	SID_DP_1_2 = 1016,// SID_DP_1_2
	SID_DP_1_1 = 1017,// SID_DP_1_1
	SID_TopLeftBmp6 = 1018,// SID_TopLeftBmp6
	SID_BottomLeftBmp4 = 1019,// SID_BottomLeftBmp4
	SID_TopRightBmp6 = 1020,// SID_TopRightBmp6
	SID_BottomRightBmp4 = 1021,// SID_BottomRightBmp4
	SID_FactoryResetConfirmText = 1022,// SID_FactoryResetConfirmText
	SID_NoBitmapButton = 1023,// SID_NoBitmapButton
	SID_YesBitmapButton = 1024,// SID_YesBitmapButton
	SID_NoTextButton = 1025,// SID_NoTextButton
	SID_YesTextButton = 1026,// SID_YesTextButton
	SID_LuckText = 1027,// SID_LuckText
	SID_LuckText2 = 1028,// SID_LuckText2
	SID_offBitmapButton = 1029,// SID_offBitmapButton
	SID_onBitmapButton = 1030,// SID_onBitmapButton
	SID_offTextButton = 1031,// SID_offTextButton
	SID_onTextButton = 1032,// SID_onTextButton
	SID_DP_MSTStaticText = 1033,// SID_DP_MSTStaticText
	SID_DP12DisableBitmapButton = 1034,// SID_DP12DisableBitmapButton
	SID_DP11EnableBitmapButton = 1035,// SID_DP11EnableBitmapButton
	SID_DP11EnableTextButton = 1036,// SID_DP11EnableTextButton
	SID_DP12DisableTextButton = 1037,// SID_DP12DisableTextButton
	SID_DP2_Text1 = 1038,// SID_DP2_Text1
	SID_DP2_Text2 = 1039,// SID_DP2_Text2
	SID_DP2_Text3 = 1040,// SID_DP2_Text3
	SID_DP_Confirm_BitmapButton = 1041,// SID_DP_Confirm_BitmapButton
	SID_DP_Exit_BitmapButton = 1042,// SID_DP_Exit_BitmapButton
	SID_DP_Confirm_TextButton = 1043,// SID_DP_Confirm_TextButton
	SID_DP_Exit_TextButton = 1044,// SID_DP_Exit_TextButton
	SID_DP_MSTStaticText1 = 1045,// SID_DP_MSTStaticText1
	SID_DP_Confirm_BitmapButton1 = 1046,// SID_DP_Confirm_BitmapButton1
	SID_DP_Exit_BitmapButton1 = 1047,// SID_DP_Exit_BitmapButton1
	SID_DP_Confirm_TextButton1 = 1048,// SID_DP_Confirm_TextButton1
	SID_DP_Exit_TextButton1 = 1049,// SID_DP_Exit_TextButton1
	SID_LanguageEnglishState = 1050,// SID_LanguageEnglishState
	SID_LanguageChineseState = 1051,// SID_LanguageChineseState
	SID_FactoryResetState1 = 1052,// SID_FactoryResetState1
	SID_FactoryMenuUpdate = 1053,// SID_FactoryMenuUpdate
	SID_OSDRotationUpdate = 1054,// SID_OSDRotationUpdate
	MAINTHREAD_STATES_NUMBER
} MainThreadStateEnum;

typedef enum 
{
	SID_Default = 0,// SID_Default
	SID_IconUpdateState = 1,// SID_IconUpdateState
	SID_MainInputSourceDialog = 2,// SID_MainInputSourceDialog
	SID_ChooseInputSourceState = 3,// SID_ChooseInputSourceState
	SID_VGAInputSourceState = 4,// SID_VGAInputSourceState
	SID_DVIInputSourceState = 5,// SID_DVIInputSourceState
	SID_DPInputSourceState = 6,// SID_DPInputSourceState
	SID_DP3InputSourceState = 7,// SID_DP3InputSourceState
	SID_HDMIInputSourceState = 8,// SID_HDMIInputSourceState
	SID_DIPInputSourceState = 9,// SID_DIPInputSourceState
	SID_YPbPrInputSourceState = 10,// SID_YPbPrInputSourceState
	SID_VGABitmap6 = 11,// SID_VGABitmap6
	SID_DVIBitmap6 = 12,// SID_DVIBitmap6
	SID_DPBitmap6 = 13,// SID_DPBitmap6
	SID_DP3Bitmap6 = 14,// SID_DP3Bitmap6
	SID_HDMIBitmap6 = 15,// SID_HDMIBitmap6
	SID_DIPBitmap = 16,// SID_DIPBitmap
	SID_YPbPrBitmap = 17,// SID_YPbPrBitmap
	INPUTICONSTHREAD_STATES_NUMBER
} InputIconsThreadStateEnum;

typedef enum 
{
	SID_Default1 = 0,// SID_Default1
	SID_PIPIconUpdateState = 1,// SID_PIPIconUpdateState
	SID_PIPInputSourceDialog = 2,// SID_PIPInputSourceDialog
	SID_ChooseInputSourceState1 = 3,// SID_ChooseInputSourceState1
	SID_VGAInputSourceState1 = 4,// SID_VGAInputSourceState1
	SID_DVIInputSourceState1 = 5,// SID_DVIInputSourceState1
	SID_DPInputSourceState1 = 6,// SID_DPInputSourceState1
	SID_DP3InputSourceState1 = 7,// SID_DP3InputSourceState1
	SID_HDMIInputSourceState1 = 8,// SID_HDMIInputSourceState1
	SID_DIPInputSourceState1 = 9,// SID_DIPInputSourceState1
	SID_YPbPrInputSourceState1 = 10,// SID_YPbPrInputSourceState1
	SID_VGABitmap7 = 11,// SID_VGABitmap7
	SID_DVIBitmap7 = 12,// SID_DVIBitmap7
	SID_DPBitmap7 = 13,// SID_DPBitmap7
	SID_DP3Bitmap7 = 14,// SID_DP3Bitmap7
	SID_HDMIBitmap7 = 15,// SID_HDMIBitmap7
	SID_DIPBitmap1 = 16,// SID_DIPBitmap1
	SID_YPbPrBitmap1 = 17,// SID_YPbPrBitmap1
	PIPICONSTHREAD_STATES_NUMBER
} PIPIconsThreadStateEnum;

typedef enum 
{
	SID_DefaultState1 = 0,// SID_DefaultState1
	SID_HideInvisibleState = 1,// SID_HideInvisibleState
	SID_ChooseInvState = 2,// SID_ChooseInvState
	PIPMESSAGES_STATES_NUMBER
} PIPMessagesStateEnum;

extern WORD ROM gmv_ThreadNumOfStates[];



#ifdef WB_ENABLE_DEBUG_INFO_STATES
extern char ROM* ROM* ROM gmv_ThreadsDebugArrayDef[];

extern char ROM* ROM gmv_ThreadsDebugInfo[];

#endif //WB_ENABLE_DEBUG_INFO_STATES

extern gmt_OSD_SM_THREAD_DESCRIPTOR ROM gmv_GlobalThreadSet[];

#define NUMBER_OF_THREADS 4

#define WB_MAX_STATE_SIZE 426

////////////////////////////////////////////////////////////////////////////////
//    Workbench Defines
////////////////////////////////////////////////////////////////////////////////

#define WB_BUILD_CONDITION_Default		
// User Timers definition

extern BYTE ROM B_OSD_TimeoutTid;
typedef enum 
{
	B_InfoTimerTid,
	B_OsdCustomTimerTid = 1,
	B_OSDCustomPIPTimerTid = 2,
	B_InputIconTimerTid = 3,
	B_AlertTimerTid = 4,
	B_OSDRedrawTimerTid = 5,
	B_DiagnosticTestPatternTimerTid = 6,
	B_LCDConditionTimerTid = 7,
	B_OSD_MsgShow_PIPTid = 8,
	B_PIPMUpdateTimerTid = 9,
	B_AutoConfigTimerTid = 10,
	B_NoSyncTimerTid = 11,
	B_OSD_IconShowTid = 12,
	B_OSD_IconShow_PIPTid = 13,
	B_OsdHardLockTimerTid = 15
} TimerOpIDEnum;


extern WORD ROM W_OsdTimerResolution;

#define OSD_TIMERS_NUM		16
extern WORD  gW_OsdTimers[OSD_TIMERS_NUM];

extern BYTE  gB_OsdTimerStart[OSD_TIMERS_NUM];

extern WORD ROM gB_OsdTimerEvents[];


// State Action Table definition
typedef enum 
{
	ATID_PublEAT_Main_Dialog,
	ATID_PublEAT_FactoryModeDialog,
	ATID_CommonMainEVT,
	ATID_PublEAT_Control_Dialog,
	ATID_PublEAT_FactoryMode1,
	ATID_CommonMainEVT_MainOSD,
	ATID_PublEAT_MessagesDialog,
	ATID_PublEAT_MesInvState,
	ATID_PipEVT_MainMenuTrtbl,
	ATID_PublEAT_PIPMenuState,
	ATID_PublEAT_PortChange_Dialog,
	ATID_PublEAT_YesNoStateDlg,
	ATID_PublEAT_PBPMainMessages,
	ATID_PublEAT_PortChange,
	ATID_PublEAT_NoSignalIn0505F1D4,
	ATID_PublEAT_NoFlyingDialog,
	ATID_PipEVT_ValidModeTrtbl,
	ATID_PublEAT_FlyingDialog,
	ATID_InputKeyEventActions,
	ATID_PublEAT_InfoDisplay,
	ATID_PowerOFFActions,
	ATID_PublEAT_Diagnostic9F141EEF,
	ATID_PublEAT_MainInputSEC51F5A4,
	ATID_PublEAT_PIPInputSo598E2D6A,
	ATID_SystemEvents,
	ATID_PublEAT_DisplayInfo,
	ATID_PublEAT_PowerSaveP631C6A69,
	ATID_PublEAT_LockDialog,
	ATID_PublEAT_DiagnosticF825C16C,
	ATID_PublEAT_Diagnostic5F3D55F8,
	ATID_ValidModeEAT,
	ATID_PublEAT_LCDCondition,
	ATID_PublEAT_AutoAdjustment1,
	ATID_PublEAT_LogoFlyDialog,
	ATID_CMD_EVT,
	ATID_PublEAT_SplashScreenAthena,
	ATID_PIPUpdate,
	ATID_OSDTimerEventActions,
	ATID_PublEAT_BurnInModeState,
	ATID_PublEAT_DefaultState1,
	ATID_PublEAT_NoSyncTemp,
	ATID_PublEAT_ValidMode_State
} ActionTableEnum;

extern BYTE ROM * ROM gmv_ActTableSet[];

#define WB_MAX_EAT_SIZE 324


#endif  // ifndef OSD_DAT_H_DEFINED
