////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#include "System\all.h"

ModeIndependentUserPrefType  ModeIndependentUserPreferences;

ModeIndependentUserPrefType ROM FactoryDefaultInROM =
{
	TNR_LOW,	// TNR
 	MADI_STANDARD,	// MADI
 	CCS_OFF,	// CCS
 	SHARPNOISE_LOW,	// SharpNoise
 	ENABLE,	// DCDiMain
 	ENABLE,	// DCDiPip
 	MPEG_NR_MOSQ_GAUSS,	// MPEGNRMode
 	MPEG_NR_THRESHOLD_0_DEF,	// MPEGNRThresh0
 	MPEG_NR_THRESHOLD_1_DEF,	// MPEGNRThresh1
 	MPEG_NR_THRESHOLD_2_DEF,	// MPEGNRThresh2
 	OD_NOISE_CORING_ADAPTIVE,	// LCDOverdriveNoiseCoring
 	NORMAL_32_DISPLAY_MODE,	// ThreeTwoFilmDisplayMode
 	VBI_SERVICE_CC,	// VBI_ServicePreferred
 	12,	// SharpnessPip
 	BLUE_STRETCH_OFF,	// BlueStretch
 	12,	// SharpnessRGB
 	12,	// SharpnessRGBpip
 	0,	// AVSDelay
 	DEFAULT_VOLUME_VALUE,	// AudioVolume
 	INTERNAL_DAC_COMP,	// ADCCalibrationMethod_Comp
 	INTERNAL_DAC_VGA,	// ADCCalibrationMethod_VGA
 	AR_FULL_SCREEN,	// AspectRatioMain
 	AR_FULL_SCREEN,	// AspectRatioPip
 	WB_PORT_DEF_MAIN,	// CurrentInputMain
 	WB_PORT_DEF_PXP,	// CurrentInputPip
 	0,	// DynamicContrast
 	FM_VIDEO_32,	// FilmMode
 	FT_OFF,	// FleshToneComp 'Desc' :Flesh tone compensation level
 	USER,	// ImageScheme
 	0,	// LCDOverdrive
 	DISABLE,	// LetterboxEnable
 	5,	// MPEGNR
 	500,	// OsdHPosition
 	500,	// OsdVPosition
 	LANG_DEF,	// OsdLanguage
 	OSD_NON_ROTATED,	// OsdRotation
 	30,	// OsdTimeout 'Desc' :Osd hide timeout
 	ENABLE,	// OverscanEnable
 	1,	// PowerState
 	12,	// Sharpness
 	0,	// SleepAMPM
 	0,	// SleepDay
 	0,	// SleepHour
 	0,	// SleepMin
 	0,	// SleepMinsLeft
 	0,	// ThreeDNR
 	7,	// TVRating
 	0,	// TVUnrated
 	NVRAM_CHECKSUM,	// Version
 	0,	// WakeAMPM
 	0,	// WakeDay
 	0,	// WakeHour
 	0,	// WakeMin
 	7,	// MPRating
 	0,	// AVSDelayTime
 	0,	// CC_On
 	0,	// AudioMute
 	POP7,	// MPipConfig
 	1111,	// ParentalPassword
 	0,	// PipMode
 	0,	// PipPosition
 	LARGE_PIP,	// PipSize
 	0,	// ScrollMenuItem
 	0,	// MainRouteModeComponent
 	0,	// MainRouteModeScartRGB
 	0,	// PipRouteModeComponent
 	0,	// PipRouteModeScartRGB
 	US_TV_RATING_SUBCODE_FV,	// UserPrefTVYouth7Subcode
 	(US_TV_RATING_SUBCODE_V | US_TV_RATING_SUBCODE_S | US_TV_RATING_SUBCODE_L | US_TV_RATING_SUBCODE_D),	// UserPrefTVPGSubcode
 	(US_TV_RATING_SUBCODE_V | US_TV_RATING_SUBCODE_S | US_TV_RATING_SUBCODE_L | US_TV_RATING_SUBCODE_D),	// UserPrefTV14Subcode
 	(US_TV_RATING_SUBCODE_V | US_TV_RATING_SUBCODE_S | US_TV_RATING_SUBCODE_L),	// UserPrefTVMASubcode
 	SWAGC,	// DecoderAGCMethod 'Desc' :DecoderAGCMethod
 	Off,	// CCSforHD
 	0,	// TwoStageProcessing
 	0,	// ManualTVMHzFreq
 	0,	// ManualTVkHzFreq
 	0,	// TVFreqFineTune
 	1,	// TVManualScanRequired 'Desc' :A new system should display a warning message that autoscan is required (1=required, 0=not required)
 	1,	// UserPrefScartRgbViaOverlay
 	INTERNAL_DAC_CVBS,	// ADCCalibrationMethod_CVBS
 	BAND_GAP,	// ADCCalibrationMethod_InternalDac
 	FALSE,	// AutoAspectRatio
 	INTERNAL_DAC_SCART,	// ADCCalibrationMethod_SCART
 	1,	// EnhancerEnable
 	0,	// OldEnhancerEnable 'Desc' :echeung:
	// Old Enhancer Menu On/Off
 	0,	// OldEnhancerRouting
 	0,	// ColorResourceRouting
 	INTERNAL_DAC_SIF_CALIB_OFF,	// ADCCalibrationMethod_SIF
 	0,	// LineoutVariable 'Desc' :adjust Variable Volume
 	0,	// UserPrefGameFlag
 	0,	// UserPrefXvYcc
 	0,	// AudioDownMix
 	ColorSpace_sRGB,	// ColorSpace
 	VWD_DEF,	// VwdFlag
 	VWD_DEF,	// VwdDemo
 	gmd_AUDIO_SRC_AUTO_Main,	// AudioMainInput
 	WB_AUDIO_OUT_DEF,	// AudioMainOutput
 	gmd_AUDIO_SRC_AUTO_Pxp,	// AudioPipInput
 	gmd_AUDIO_TAR_HeadPhone_OUT,	// AudioPipOutput
 	0,	// OSDG1Blend
 	0,	// OSDG2Blend
 	0,	// OSDG3Blend
 	0,	// CaptureM
 	0,	// ImageRotation
 	0,	// OSD_4Kx2K_Port
 	DP_SWITCH_DEF,	// DPSWitch
 	ON,	// OsdRotation_Auto 'Desc' :owenh:
	// for OSD Rotation Atou
	// 0 -> off
	// 1->Auto
	// 
 	1,	// Speakers
 	1,	// Headphones
 	AUDIO_MAIN,	// SpeakerAudioSource
 	AUDIO_MAIN,	// HeadphoneAudioSource
 	20,	// OsdBlend
 	On,	// PwrAudio 'Desc' :Power Save on Audio option
 	0,	// SavingBitFlags
 	0,	// OSDLock
 	0,	// OSDHardLock
 	0,	// RunBurnInModeFlag
 	0,	// OsdVPosition1
 	0,	// OsdHPosition1
 	3,	// PIPTimer
 	0,	// PIPMHide 'Desc' :Show/Hide OSD Messages
	// 
 	0,	// HideIconFlag 'Desc' :Not show icon when exit main menu.
 	ENABLE,	// DdcciOnOffFlag
 	ShortCut_PresetMode_All,	// PersonalKey1
 	ShortCut_BrightnessContrast,	// PersonalKey2
 	ShortCut_InputSource_ALL,	// PersonalKey3
 	1,	// ButtonSoundOff
 	0,	// AutoAdjustJump
 	0,	// MenuOnOffFlag
 	0,	// WakeUpByTouchPad
 	0,	// PowerKeyPressedFlag
 	0,	// CustomColorSelection
 	{ 0, 256, 256, 0, USER_GAIN_DEF, USER_GAIN_DEF, USER_GAIN_DEF, 0, 0, 0, CTEMP_6500K, GAMMA_TABLE_OFF, DEFAULT_PIP_INPUT, 0, 0, Video_MOVIE, Graphics_STANDARD, Gamma_PC },
	0,	// StoredPipMode
 	BOTTOM_RIGHT,	// OSDMenuLocation
 	Off,	// EnergySmartOnOffFlag
 	0,	// LCDCondition_Save
 	WB_CONTRAST_DEFAULT,	// Contrast_Vwd
 	50,	// Sharpness_Vwd
 	0,	// Offset_Vwd
 	0,	// Hue_Vwd
 	SATURATION_DEFAULT,	// Saturation_Vwd
 	UNIFORMITY_OFF,	// DUMSwitch
 	1,	// HDMIEDIDPrimeMode 'Desc' :HDMI_EDID_U2913
 	{
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF },
		{ UNIFORMITY_OFF }
	},
	0,	// PxpBlendLevel
 	DEC_1Ch_Sel_D1,	// CurrentInputMainDIP
 	DEC_1Ch_Sel_D1,	// CurrentInputPxpDIP
 	FULL_SCREEN,	// MainMode
 	TOP_LEFT,	// MainPosition
 	0,	// OSDZoom
 	5,	// LampBrightness
 	0,	// PD_MainCtrl
 	0,	// PD_PxpCtrl
 	OSD_UART_DEF,	// UartSelect
 	0,	// OutputAspectRatio
 	OPM_Normal,	// OutputMode
 	0,	// MainBlendLevel
 	0,	// BlendSpeed
 	DE_1920x1080,	// DynamicEDID
 	0,	// DimEffect
 	0,	// PanelProtect
 	50,	// OSDAudioVolume
 	1,	// PanelNumber
 	0,	// SerlCmdPanelHStart
 	0,	// SerlCmdPanelVStart
 	0,	// SerlCmdPanelHLeng
 	0,	// SerlCmdPanelVWide
 	0,	// PIPScalerSW
 	0	// PipAutoScalerSW
 };

GlobalUserPrefType  GlobalUserPreferences =
{
	0,	// ParentalBlockStateFlagMain
 	0,	// ParentalBlockStateFlagPip
 	0,	// ChannelBlockStateFlag 'Desc' :Main TV Block  Status
 	0,	// ChannelBlockStateFlagPip 'Desc' :Pip TV Block  Status
 	{
		{ 32, 0 },
		{ 32, 0 },
		{ 32, 0 },
		{ 32, 0 },
		{ 32, 0 },
		{ 32, 0 },
		{ 32, 0 },
		{ 32, 0 }
	},
	0,	// Freeze
 	0,	// MultiPipStateFlag
 	0,	// OsdMPipHPos
 	0,	// OsdMPipVPos
 	0,	// OsdMPipChannel
 	0,	// SideBySideFocus
 	255,	// OSDBottomPos
 	25,	// OSDCenterPos
 	6,	// OSDTopHPos
 	6,	// OSDTopVPos
 	0,	// VChipPassword 'Desc' :used to store the vchip passwprd user has entered
 	1,	// Month
 	1,	// Date
 	0,	// Year
 	1,	// Hour
 	0,	// Min
 	0,	// AMPM
 	0,	// InfoDisplayOn 'Desc' :Flag to indicate if user pressed Info key
 	0,	// PrevPipSource
 	MINCHANNELFREQSLIDER,	// ChannelFreqSlider
 	MINCHANNELFREQVALUE,	// ChannelFreqValue
 	0,	// FactoryState
 	0,	// RegAddr
 	0,	// RegVal
 	0,	// PreviousPipMode
 	32,	// ChannelNameEntry1
 	32,	// ChannelNameEntry2
 	32,	// ChannelNameEntry3
 	32,	// ChannelNameEntry4
 	32,	// ChannelNameEntry5
 	0,	// PtrSegment
 	0,	// PtrOffset
 	{
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 },
		{ 0 }
	},
	0,	// ChannelNumDisplayFlag 'Desc' :Flag to indicate if the tv number should be displayed in the InfoDisplay_Dialog
 	0,	// ChannelNumAppendDisplayFlag 'Desc' :Flag to indicate if the tv number should be displayed in the InfoDisplay_Dialog
 	100,	// OsdScale100Percent
 	0,	// OsdFullScreenXPercent
 	0,	// OsdFullScreenYPercent
 	0,	// OsdState 'Desc' :0=default state
 	0,	// OsdBitFlags
 	0,	// CurrentBlockedTVRatingSubcodeMain
 	0,	// CurrentBlockedTVRatingSubcodePip
 	Column_One,	// MPipTileSet
 	0,	// ChipIDdigit1
 	0,	// ChipIDdigit2
 	0,	// ChipIDdigit3
 	0,	// ChipIDdigit4
 	0,	// ColorSystem
 	0,	// TtxNoSignalFlag
 	{
		{ 99 },
		{ 99 },
		{ 99 },
		{ 99 },
		{ 99 }
	},
	0,	// InputPortCount
 	0,	// DisplayPortName 'Desc' :Flag to indicate if to display port name only
 	0,	// OldOrNewPortChange
 	0,	// Str1_seg
 	0,	// Str2_seg
 	0,	// Str3_seg
 	0,	// Str4_seg
 	0,	// Str1_ofs
 	0,	// Str2_ofs
 	0,	// Str3_ofs
 	0,	// Str4_ofs
 	0,	// CecDeviceName_seg
 	0,	// CecDeviceName_ofs
 	0,	// CecDeviceType 'Desc' :Logical address of CEC device under control
 	0,	// DontRemoveOSD
 	0,	// CecRecordOnExtPlugNumber
 	0,	// CecDevicePowerStatus
 	0,	// CecStatusText1_seg
 	0,	// CecStatusText1_ofs
 	0,	// CecStatusText2_seg
 	0,	// CecStatusText2_ofs
 	0,	// CecStatusText3_seg
 	0,	// CecStatusText3_ofs
 	0,	// CecStatusLineCounter 'Desc' :line counter for CEC status strings
 	0,	// CecRecordDateDay 'Desc' :Day of month for CEC timer control feature
 	0,	// CecRecordDateMonth 'Desc' :Month of year for CEC timer control feature
 	0,	// CecRecordTimeHours 'Desc' :CEC timer control feature: time of record, hours
 	0,	// CecRecordTimeMinutes 'Desc' :CEC timer control feature: time of record, minutes
 	0,	// CecRecordDurationHours 'Desc' :CEC timer control feature: duration of record, hours
 	0,	// CecRecordDurationMinutes 'Desc' :CEC timer control feature: duration of record, minutes
 	0,	// CecHDMITreeMode 'Desc' :This variable serves as a label where to return after close HDMI tree dialog
 	0,	// CecDeviceSelectedFromHDMITree 'Desc' :result of selection from hdmi tree dialog
 	0,	// CecSystemAudioStatus 'Desc' :if 0 then sound outputs via TV speakers
	// if 1 then sound outputs via audio-receiver
 	0,	// IspWrPercent
 	0,	// InFwMajor
 	0,	// InFwMinor
 	0,	// InFwRc
 	0,	// NoSignal
 	400,	// OsdVPosCenter 'Desc' :Dell
 	300,	// OsdHPosCenter 'Desc' :Dell
 	0,	// CurrentOutput 'Desc' :Main = 0 or PIP = 1 , for adjusting
 	0,	// PowerOnFlag 'Desc' :For autoconfig up to 3 times
 	0,	// PipOnScreen 'Desc' :1 = Only Pip on the screen, there is no main
 	500,	// OsdVPosFloat
 	500,	// OsdHPosFloat
 	1,	// EnableNoCable
 	0,	// MainImageZoom
 	0,	// CurrentSourceInputFlag
 	0,	// NoInpSignalStateFlag 'Desc' :Dell, NoCable NoInputSignal ststes
 	0,	// OutOfRangeStateFlag 'Desc' : Dell, For Hard and Soft Lock
 	0,	// NoCableStateFlag 'Desc' : Dell, For Hard and Soft Lock
 	0,	// BitFlags
 	600,	// OSDHposCenterPip
 	800,	// OSDVposCenterPip
 	0,	// CustomSplashScreen
 	0,	// MenuOn
 	0,	// Flag
 	0,	// Flagg
 	0,	// ScanResult
 	0,	// InputSourceFlag
 	0,	// NoSignalMSGFlag
 	0,	// MenuAdjust
 	0,	// RequestDoAutoFlag
 	0,	// DynamicTextValue
 	0,	// DuringSourceScan
 	0,	// Offset1_R
 	0,	// Offset1_G
 	0,	// Offset1_B
 	0,	// Offset2_R
 	0,	// Offset2_G
 	0,	// Offset2_B
 	0,	// Gain_R
 	0,	// Gain_G
 	0,	// Gain_B
 	0,	// BurnInModeFun 'Desc' ://20060607 JasonWu // jimmyH20051026 add
 	0,	// LCDOnOffFlag
 	1,	// RotationOnOffFlag
 	0,	// XPosOffset
 	0,	// YPosOffset
 	0,	// PIPMessagesXPos
 	0,	// PIPMessagesYPos
 	0,	// PIPIconsXPos
 	0,	// PIPIconsYPos
 	0,	// DynamicContrast
 	960,	// LCDConditionXPos
 	590,	// LCDConditionYPos
 	0,	// LCDConditionPosition
 	FORCE_BACKGROUND_GRAY,	// ForceBGColor
 	1,	// MenuRemovableFlag
 	0,	// ForcePowerSavingFlag
 	0,	// MenuKeyPressed
 	110,	// IICSlaveAddress
 	1,	// ISP_Mode
 	0,	// PIPMessageOnOffFlag
 	0,	// StateTempFlag 'Desc' :jimhuang:
	// 0 : Normal
	// 1 : Graphice Customer RGB
	// 2 : Graphice Customer YMC
	// 3 : Video Customer RGB 
	// 4 : Video Customer YMC
	// 5 : Auto Scan with Hot key
	// 6 : Power Saving wake up
	//  
	// 10: FlyingWindow
	// 11: OOR
	// 
	// Jimhuang:
	// 
 	2,	// KeySpeedUpFlag
 	0,	// OSDStateFlag
 	0,	// PowerKeyFlag
 	0,	// DCACBottonSoundFlag
 	0,	// LanguageStateFlag
 	0,	// PIPEnFlag
 	0,	// AutoSourceStateFlag
 	0,	// FlyStateFlag
 	0,	// PowerSavingFlag
 	0,	// ServiceMenuFlag
 	0,	// DiagnosticTestState
 	0,	// RotationEnabled
 	0,	// InfoFlag
 	0,	// DCRTestOnOffFlag
 	0,	// PIPMessageOnFlag
 	FALSE,	// AdjustInputColorFormatByOSD
 	0,	// PIPNoCableMessageOnFlag
 	0,	// PIPOORMessageOnFlag
 	0,	// FactoryFlag
 	FALSE,	// IsIconUpdateDisable
 	Off,	// InputMenuOn
 	4,	// SpreadAmpValue
 	63,	// SpreadPeriodValue
 	2,	// SpreadAmpValue2
 	20,	// SpreadPeriodValue2
 	0,	// MainMessageOnFlag
 	0,	// VGADisplayResetFlag
 	FALSE,	// InputMenuSourceChanged
 	5,	// NoCablePowerDownMins
 	0,	// NoCablePowerDownSecs
 	0,	// NoCablePowerDownFlag
 	0,	// NoCablePowerDownTime
 	0,	// EnergyUsedLevel
 	0,	// IsCustomColorAdjustMenu
 	0,	// IsEnergySmartToggledFlag
 	0,	// PtrSegmentDynamicString
 	0,	// PtrOffsetDynamicString
 	0,	// OSD_Temp
 	0,	// BrightnessItemGreyout
 	0,	// StartSmartISP
 	1,	// EDIDWP_Temp
 	0,	// OSDMessageCtrl
 	0,	// VWD_OSD_Enable
 	0,	// UnStableByOSD
 	0,	// SundBox_OSD_True
 	0,	// SundBox_OSD_False
 	0,	// PIPSourceChange_OSD
 	0,	// AudioPCM_Messaeg
 	0,	// EnableDDC2BiAddress0x7C
 	CH_A,	// PortChangeOnChannel
 	0,	// BoardID_1
 	0,	// BoardID_2
 	0,	// BoardID_3
 	0,	// BoardID_4
 	0,	// BoardID_VerifyCnt
 	0,	// OSDCurrentStates
 	0,	// UserEvent
 	0,	// PxpImageZoom
 	1,	// DE_Week
 	2014,	// DE_YEAR
 	0,	// KeyChanged
 	ALL_BOARDS_VGA1,	// DyEDIDPort
 	0,	// SelectPanel
 	0,	// PanelProtectAdjustHStartFlag
 	0	// HotKeyState
 };

ModeDependentUserPrefType  ModeDependentUserPreferences;

PortSchemeDependentUserPrefType  PortSchemeDependentUserPreferences;

ModeDependent_PIPUserPrefType  ModeDependent_PIPUserPreferences;

FactoryUserPrefType  FactoryUserPreferences;

FactoryUserPrefType ROM FactoryCalibDefaultsInROM =
{
	FACTORY_NVRAM_VERSION,	// FactoryVersion
 	0,	// TimeUsedHour
 	0,	// TimeUsedMin
 	36,	// Offset1_VR
 	30,	// Offset1_VG
 	27,	// Offset1_VB
 	48,	// Offset2_VR
 	59,	// Offset2_VG
 	58,	// Offset2_VB
 	232,	// Gain_VR
 	242,	// Gain_VG
 	220,	// Gain_VB
 	DEF_F_CT10000K_R,	// ColorT10000_R 'Desc' ://74 TO 63
 	DEF_F_CT10000K_G,	// ColorT10000_G 'Desc' ://105 TO 87
 	DEF_F_CT10000K_B,	// ColorT10000_B 'Desc' ://113 TO 96
	// 
	// Administrator:
	// Neil 20090307 change from 241 to 225
	// 
 	DEF_F_CT9300K_R,	// ColorT9300_R 'Desc' ://74 TO 63
 	DEF_F_CT9300K_G,	// ColorT9300_G 'Desc' ://105 TO 87
 	DEF_F_CT9300K_B,	// ColorT9300_B 'Desc' ://113 TO 96
	// 
	// Administrator:
	// Neil 20090307 change from 241 to 225
	// 
 	DEF_F_CT7500K_R,	// ColorT7500_R 'Desc' ://74 TO 63
 	DEF_F_CT7500K_G,	// ColorT7500_G 'Desc' ://105 TO 87
 	DEF_F_CT7500K_B,	// ColorT7500_B 'Desc' ://113 TO 96
	// 
	// Administrator:
	// Neil 20090307 change from 241 to 225
	// 
 	DEF_F_CT7200K_R,	// ColorT7200_R 'Desc' ://74 TO 63
 	DEF_F_CT7200K_G,	// ColorT7200_G 'Desc' ://105 TO 87
 	DEF_F_CT7200K_B,	// ColorT7200_B 'Desc' ://113 TO 96
	// 
	// Administrator:
	// Neil 20090307 change from 241 to 225
	// 
 	DEF_F_CT6500K_R,	// ColorT6500_R 'Desc' ://92 TO 80 CHANGED
 	DEF_F_CT6500K_G,	// ColorT6500_G 'Desc' ://102 TO 87
 	DEF_F_CT6500K_B,	// ColorT6500_B 'Desc' ://100 TO 66
 	DEF_F_CT5700K_R,	// ColorT5700_R 'Desc' ://95 TO 82
 	DEF_F_CT5700K_G,	// ColorT5700_G 'Desc' ://105 TO 87
 	DEF_F_CT5700K_B,	// ColorT5700_B 'Desc' ://82 TO 50
 	DEF_F_CT5000K_R,	// ColorT5000_R 'Desc' ://92 TO 80 CHANGED
 	DEF_F_CT5000K_G,	// ColorT5000_G 'Desc' ://102 TO 87
 	DEF_F_CT5000K_B,	// ColorT5000_B 'Desc' ://100 TO 66
 	128,	// sRGB_Contrast
 	70,	// sRGB_Brightness
 	253,	// MacColor_R
 	252,	// MacColor_G
 	254,	// MacColor_B
 	1,	// SpeadSpectrum_Mode
 	0,	// SpeadSpectrum_Mode2
 	0,	// Debug_Mode
 	40,	// ColorT9300_Brightness
 	128,	// ColorT9300_Contrast
 	40,	// ColorT6500_Brightness
 	128,	// ColorT6500_Contrast
 	128,	// UserColor_Contrast
 	40,	// UserColor_Brightness
 	12288,	// Gm1601RegNumber
 	0,	// Gm1601RegValue
 	0,	// Gm1601RegWrite
 	0,	// MonitorOnCount
 	0,	// ConstantTimeUsedHour
 	0,	// ConstantTimeUsedMin
 	0,	// SoftKeyOnCount
 	80,	// sRGB_R_Gamma18 'Desc' ://92 TO 80 CHANGED
 	87,	// sRGB_G_Gamma18 'Desc' ://102 TO 87
 	66,	// sRGB_B_Gamma18 'Desc' ://100 TO 66
 	30,	// Offset1_CR
 	30,	// Offset1_CG
 	30,	// Offset1_CB
 	48,	// Offset2_CR
 	59,	// Offset2_CG
 	48,	// Offset2_CB
 	230,	// Gain_CR
 	240,	// Gain_CG
 	230,	// Gain_CB
 	2,	// DDRSSC
 	0,	// AddressNo
 	0,	// DataW
 	0,	// MonitorHours
 	0,	// MonitorMinutes
 	1,	// HDMIGraphics
 	DEF_F_sRGB_R,	// sRGBColor_R
 	DEF_F_sRGB_G,	// sRGBColor_G
 	DEF_F_sRGB_B,	// sRGBColor_B
 	DEF_F_AdobeRGB_R,	// AdobeRGBColor_R
 	DEF_F_AdobeRGB_G,	// AdobeRGBColor_G
 	DEF_F_AdobeRGB_B,	// AdobeRGBColor_B
 	WB_BriBase6500K_DEF,	// BriBase_6500K
 	WB_BriBasesRGB_DEF,	// BriBase_sRGB
 	WB_BriBaseAdobeRGB_DEFT,	// BriBase_AdobeRGB
 	WB_BriBaseTable1_DEFT,	// BriBase_Table1
 	WB_BriBaseTable2_DEFT,	// BriBase_Table2
 	WB_BriBaseText_DEFT,	// BriBase_Text
 	164,	// Color_R1
 	149,	// Color_R2
 	4,	// Color_R3
 	85,	// Color_G1
 	187,	// Color_G2
 	47,	// Color_G3
 	21,	// Color_B1
 	49,	// Color_B2
 	197,	// Color_B3
 	242,	// AdobeColor_R1
 	11,	// AdobeColor_R2
 	4,	// AdobeColor_R3
 	151,	// AdobeColor_G1
 	172,	// AdobeColor_G2
 	48,	// AdobeColor_G3
 	9,	// AdobeColor_B1
 	19,	// AdobeColor_B2
 	153,	// AdobeColor_B3
 	0,	// SRGB_GAMMASELECT
 	0,	// AdobeRGB_GAMMASELECT
 	WB_BOARD_ID_DEF,	// BoardID
 	DEFAULT_PANEL,	// PanelSelect
 	WB_LOGO_DEF,	// LOGO_Ctrl
 	WB_BAUDRATE_DEF,	// UartBaudRate
 	0	// AudioSelectFlag
 };

ServiceBlockUserPrefType  ServiceBlockUserPreferences;

ServiceBlockUserPrefType ROM ServiceBlockDefault =
{
	0,	// ACPowerOnCounter
 	0	// DCPowerOnCounter
 };

gmt_OSD_ADJUSTERS_GROUP ROM gmv_OsdAdjustersGroupList[] =
{
	{ (void*) &ModeIndependentUserPreferences },
	{ (void*) &GlobalUserPreferences },
	{ (void*) &ModeDependentUserPreferences },
	{ (void*) &PortSchemeDependentUserPreferences },
	{ (void*) &ModeDependent_PIPUserPreferences },
	{ (void*) &FactoryUserPreferences },
	{ (void*) &ServiceBlockUserPreferences }
};

BYTE ChannelNameDigit;
BYTE BlockedChannelList;
BYTE ADCOffsetGainList;
BYTE InputPortList;
BYTE WB_ImageScheme;
BYTE WB_SourceSelector;

gmt_OSD_ADJUSTERS_MODE_SWITCHERS ROM gmv_OsdAdjusterModeSwitchers[] =
{
	{ &ChannelNameDigit, 8 },
	{ &BlockedChannelList, 10 },
	{ &ADCOffsetGainList, 9 },
	{ &InputPortList, 5 },
	{ &WB_ImageScheme, 11 },
	{ &WB_SourceSelector, 2 }
};


