////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_UADJ_H_DEFINED
#define OSD_UADJ_H_DEFINED

#ifndef WB_NVRAM_STRUCTURE_VERSION
#define WB_NVRAM_STRUCTURE_VERSION		0xb52d
#endif //WB_NVRAM_STRUCTURE_VERSION

// gmv_OsdAdjusterFuncSet definition
#define Action_Adjust3DNR_WB_Used 
#define Action_AdjustAVSDelayOnOff_WB_Used 
#define Action_AdjustAcmBlackHue_WB_Used 
#define Action_AdjustAcmBlackLuma_WB_Used 
#define Action_AdjustAcmBlackSat_WB_Used 
#define Action_AdjustAcmBlueHue_WB_Used 
#define Action_AdjustAcmBlueLuma_WB_Used 
#define Action_AdjustAcmBlueSat_WB_Used 
#define Action_AdjustAcmCyanHue_WB_Used 
#define Action_AdjustAcmCyanLuma_WB_Used 
#define Action_AdjustAcmCyanSat_WB_Used 
#define Action_AdjustAcmGreenHue_WB_Used 
#define Action_AdjustAcmGreenLuma_WB_Used 
#define Action_AdjustAcmGreenSat_WB_Used 
#define Action_AdjustAcmMagentaHue_WB_Used 
#define Action_AdjustAcmMagentaLuma_WB_Used 
#define Action_AdjustAcmMagentaSat_WB_Used 
#define Action_AdjustAcmRedHue_WB_Used 
#define Action_AdjustAcmRedLuma_WB_Used 
#define Action_AdjustAcmRedSat_WB_Used 
#define Action_AdjustAcmWhiteHue_WB_Used 
#define Action_AdjustAcmWhiteLuma_WB_Used 
#define Action_AdjustAcmWhiteSat_WB_Used 
#define Action_AdjustAcmYellowHue_WB_Used 
#define Action_AdjustAcmYellowLuma_WB_Used 
#define Action_AdjustAcmYellowSat_WB_Used 
#define Action_AdjustAdvanceVWD_WB_Used 
#define Action_AdjustAspectRatioMain_WB_Used 
#define Action_AdjustAspectRatioPip_WB_Used 
#define Action_AdjustAudio_WB_Used 
#define Action_AdjustAudioInputSource_WB_Used 
#define Action_AdjustAudioMute_WB_Used 
#define Action_AdjustAudioVolume_WB_Used 
#define Action_AdjustAutoAspectRatio_WB_Used 
#define Action_AdjustBKG_Lamp_WB_Used 
#define Action_AdjustBlue_WB_Used 
#define Action_AdjustBlueGain_WB_Used 
#define Action_AdjustBlueOff_WB_Used 
#define Action_AdjustBlueStretch_WB_Used 
#define Action_AdjustBrightness_WB_Used 
#define Action_AdjustBurnInMode_WB_Used 
#define Action_AdjustCCS_WB_Used 
#define Action_AdjustCCSforHD_WB_Used 
#define Action_AdjustCaptureMain_WB_Used 
#define Action_AdjustColorDomain_WB_Used 
#define Action_AdjustColorFormat_WB_Used 
#define Action_AdjustColorMode_WB_Used 
#define Action_AdjustColorResourceRouting_WB_Used 
#define Action_AdjustColorSpace_WB_Used 
#define Action_AdjustColorTemp_WB_Used 
#define Action_AdjustContrast_WB_Used 
#define Action_AdjustCurrentInputMain_WB_Used 
#define Action_AdjustCurrentInputPip_WB_Used 
#define Action_AdjustCurrentMainInputDIP_WB_Used 
#define Action_AdjustCurrentPxpInputDIP_WB_Used 
#define Action_AdjustDCDiMain_WB_Used 
#define Action_AdjustDCDiPip_WB_Used 
#define Action_AdjustDPSwitch_WB_Used 
#define Action_AdjustDUMSwitch_WB_Used 
#define Action_AdjustDecoderAGCMethod_WB_Used 
#define Action_AdjustDimEffect_WB_Used 
#define Action_AdjustDynamicContrast_WB_Used 
#define Action_AdjustEnergySmart_WB_Used 
#define Action_AdjustEnhancerEnable_WB_Used 
#define Action_AdjustFilmMode_WB_Used 
#define Action_AdjustFleshToneLevel_WB_Used 
#define Action_AdjustFlyingOsdHPosition_WB_Used 
#define Action_AdjustFlyingOsdVPosition_WB_Used 
#define Action_AdjustForceBackGroundColor_WB_Used 
#define Action_AdjustGammaCorrection_WB_Used 
#define Action_AdjustGammaMode_WB_Used 
#define Action_AdjustGreen_WB_Used 
#define Action_AdjustGreenGain_WB_Used 
#define Action_AdjustGreenOff_WB_Used 
#define Action_AdjustHStart_WB_Used 
#define Action_AdjustHStartPip_WB_Used 
#define Action_AdjustHSyncPhase_WB_Used 
#define Action_AdjustHSyncPhasePip_WB_Used 
#define Action_AdjustHTotal_WB_Used 
#define Action_AdjustHTotalPip_WB_Used 
#define Action_AdjustHeadphoneAudioSource_WB_Used 
#define Action_AdjustHeadphones_WB_Used 
#define Action_AdjustHue_WB_Used 
#define Action_AdjustImageRotation_WB_Used 
#define Action_AdjustImageScheme_WB_Used 
#define Action_AdjustLCDOverdrive_WB_Used 
#define Action_AdjustLCDOverdriveNoiseCoring_WB_Used 
#define Action_AdjustMADI_WB_Used 
#define Action_AdjustMPEGNR_WB_Used 
#define Action_AdjustMPEGNRMode_WB_Used 
#define Action_AdjustMPEGNRThresh_WB_Used 
#define Action_AdjustMainBlendLevel_WB_Used 
#define Action_AdjustMainMode_WB_Used 
#define Action_AdjustMainPosition_WB_Used 
#define Action_AdjustOSDAudioVolume_WB_Used 
#define Action_AdjustOSDBlending_WB_Used 
#define Action_AdjustOSDBlending1_WB_Used 
#define Action_AdjustOSDBlending2_WB_Used 
#define Action_AdjustOldEnhancerEnable_WB_Used 
#define Action_AdjustOldEnhancerRouting_WB_Used 
#define Action_AdjustOsdBlend_WB_Used 
#define Action_AdjustOsdHPosition_WB_Used 
#define Action_AdjustOsdLanguage_WB_Used 
#define Action_AdjustOsdRotation_WB_Used 
#define Action_AdjustOsdVPosition_WB_Used 
#define Action_AdjustOsdZoom_WB_Used 
#define Action_AdjustOutputMode_WB_Used 
#define Action_AdjustPIPMessageOnOff_WB_Used 
#define Action_AdjustPanelProtectCount_WB_Used 
#define Action_AdjustPanelResponseTime_WB_Used 
#define Action_AdjustPipHStart_WB_Used 
#define Action_AdjustPipMode_WB_Used 
#define Action_AdjustPipPosition_WB_Used 
#define Action_AdjustPipVStart_WB_Used 
#define Action_AdjustPresetModes_WB_Used 
#define Action_AdjustPrinterPrevue_WB_Used 
#define Action_AdjustPublicDisplayCtrl_WB_Used 
#define Action_AdjustPxpBlendLevel_WB_Used 
#define Action_AdjustRed_WB_Used 
#define Action_AdjustRedGain_WB_Used 
#define Action_AdjustRedOff_WB_Used 
#define Action_AdjustSaturation_WB_Used 
#define Action_AdjustScartRGBViaOverlay_WB_Used 
#define Action_AdjustSharpNoise_WB_Used 
#define Action_AdjustSharpness_WB_Used 
#define Action_AdjustSharpnessRGB_WB_Used 
#define Action_AdjustSpeakerAudioSource_WB_Used 
#define Action_AdjustSpeakers_WB_Used 
#define Action_AdjustTNR_WB_Used 
#define Action_AdjustThreeTwoFilmDisplayMode_WB_Used 
#define Action_AdjustTwoStageProcessing_WB_Used 
#define Action_AdjustUartSelect_WB_Used 
#define Action_AdjustVBIService_WB_Used 
#define Action_AdjustVStart_WB_Used 
#define Action_AdjustVStartPip_WB_Used 
#define Action_AdjustZoom_WB_Used 
#define Action_FAdjustAmplitudeValue_WB_Used 
#define Action_FAdjustAmplitudeValue2_WB_Used 
#define Action_FAdjustColorTempCommon_WB_Used 
#define Action_FAdjustGain_B_WB_Used 
#define Action_FAdjustGain_G_WB_Used 
#define Action_FAdjustGain_R_WB_Used 
#define Action_FAdjustIspMode_WB_Used 
#define Action_FAdjustNormalPresetGamma18Common_WB_Used 
#define Action_FAdjustOffset1_B_WB_Used 
#define Action_FAdjustOffset1_G_WB_Used 
#define Action_FAdjustOffset1_R_WB_Used 
#define Action_FAdjustOffset2_B_WB_Used 
#define Action_FAdjustOffset2_G_WB_Used 
#define Action_FAdjustOffset2_R_WB_Used 
#define Action_FAdjustPeriodValue_WB_Used 
#define Action_FAdjustPeriodValue2_WB_Used 
#define Action_FAdjustReadReg_WB_Used 
#define Action_FAdjustRegisterNumber_WB_Used 
#define Action_FAdjustSpreadEnable_WB_Used 
#define Action_FAdjustTimeUsedHour_WB_Used 
#define Action_FAdjustTimeUsedMin_WB_Used 
#define Action_FAdjustUserPresetCommon_WB_Used 
#define Action_FAdjustWriteReg_WB_Used 
#define Action_FactoryAdjustADCValues_WB_Used 
#define Action_SetOsdTimeout_WB_Used 
#define Action_VWD_ApplyHighLightWindow_WB_Used 
#define Action_VWD_Switch_WB_Used 


typedef enum 
{
	ADJID_NULL = 0,
	ADJID_Adjust3DNR,
	ADJID_AdjustAVSDelayOnOff,
	ADJID_AdjustAcmBlackHue,
	ADJID_AdjustAcmBlackLuma,
	ADJID_AdjustAcmBlackSat,
	ADJID_AdjustAcmBlueHue,
	ADJID_AdjustAcmBlueLuma,
	ADJID_AdjustAcmBlueSat,
	ADJID_AdjustAcmCyanHue,
	ADJID_AdjustAcmCyanLuma,
	ADJID_AdjustAcmCyanSat,
	ADJID_AdjustAcmGreenHue,
	ADJID_AdjustAcmGreenLuma,
	ADJID_AdjustAcmGreenSat,
	ADJID_AdjustAcmMagentaHue,
	ADJID_AdjustAcmMagentaLuma,
	ADJID_AdjustAcmMagentaSat,
	ADJID_AdjustAcmRedHue,
	ADJID_AdjustAcmRedLuma,
	ADJID_AdjustAcmRedSat,
	ADJID_AdjustAcmWhiteHue,
	ADJID_AdjustAcmWhiteLuma,
	ADJID_AdjustAcmWhiteSat,
	ADJID_AdjustAcmYellowHue,
	ADJID_AdjustAcmYellowLuma,
	ADJID_AdjustAcmYellowSat,
	ADJID_AdjustAdvanceVWD,
	ADJID_AdjustAspectRatioMain,
	ADJID_AdjustAspectRatioPip,
	ADJID_AdjustAudio,
	ADJID_AdjustAudioInputSource,
	ADJID_AdjustAudioMute,
	ADJID_AdjustAudioVolume,
	ADJID_AdjustAutoAspectRatio,
	ADJID_AdjustBKG_Lamp,
	ADJID_AdjustBlue,
	ADJID_AdjustBlueGain,
	ADJID_AdjustBlueOff,
	ADJID_AdjustBlueStretch,
	ADJID_AdjustBrightness,
	ADJID_AdjustBurnInMode,
	ADJID_AdjustCCS,
	ADJID_AdjustCCSforHD,
	ADJID_AdjustCaptureMain,
	ADJID_AdjustColorDomain,
	ADJID_AdjustColorFormat,
	ADJID_AdjustColorMode,
	ADJID_AdjustColorResourceRouting,
	ADJID_AdjustColorSpace,
	ADJID_AdjustColorTemp,
	ADJID_AdjustContrast,
	ADJID_AdjustCurrentInputMain,
	ADJID_AdjustCurrentInputPip,
	ADJID_AdjustCurrentMainInputDIP,
	ADJID_AdjustCurrentPxpInputDIP,
	ADJID_AdjustDCDiMain,
	ADJID_AdjustDCDiPip,
	ADJID_AdjustDPSwitch,
	ADJID_AdjustDUMSwitch,
	ADJID_AdjustDecoderAGCMethod,
	ADJID_AdjustDimEffect,
	ADJID_AdjustDynamicContrast,
	ADJID_AdjustEnergySmart,
	ADJID_AdjustEnhancerEnable,
	ADJID_AdjustFilmMode,
	ADJID_AdjustFleshToneLevel,
	ADJID_AdjustFlyingOsdHPosition,
	ADJID_AdjustFlyingOsdVPosition,
	ADJID_AdjustForceBackGroundColor,
	ADJID_AdjustGammaCorrection,
	ADJID_AdjustGammaMode,
	ADJID_AdjustGreen,
	ADJID_AdjustGreenGain,
	ADJID_AdjustGreenOff,
	ADJID_AdjustHStart,
	ADJID_AdjustHStartPip,
	ADJID_AdjustHSyncPhase,
	ADJID_AdjustHSyncPhasePip,
	ADJID_AdjustHTotal,
	ADJID_AdjustHTotalPip,
	ADJID_AdjustHeadphoneAudioSource,
	ADJID_AdjustHeadphones,
	ADJID_AdjustHue,
	ADJID_AdjustImageRotation,
	ADJID_AdjustImageScheme,
	ADJID_AdjustLCDOverdrive,
	ADJID_AdjustLCDOverdriveNoiseCoring,
	ADJID_AdjustMADI,
	ADJID_AdjustMPEGNR,
	ADJID_AdjustMPEGNRMode,
	ADJID_AdjustMPEGNRThresh,
	ADJID_AdjustMainBlendLevel,
	ADJID_AdjustMainMode,
	ADJID_AdjustMainPosition,
	ADJID_AdjustOSDAudioVolume,
	ADJID_AdjustOSDBlending,
	ADJID_AdjustOSDBlending1,
	ADJID_AdjustOSDBlending2,
	ADJID_AdjustOldEnhancerEnable,
	ADJID_AdjustOldEnhancerRouting,
	ADJID_AdjustOsdBlend,
	ADJID_AdjustOsdHPosition,
	ADJID_AdjustOsdLanguage,
	ADJID_AdjustOsdRotation,
	ADJID_AdjustOsdVPosition,
	ADJID_AdjustOsdZoom,
	ADJID_AdjustOutputMode,
	ADJID_AdjustPIPMessageOnOff,
	ADJID_AdjustPanelProtectCount,
	ADJID_AdjustPanelResponseTime,
	ADJID_AdjustPipHStart,
	ADJID_AdjustPipMode,
	ADJID_AdjustPipPosition,
	ADJID_AdjustPipVStart,
	ADJID_AdjustPresetModes,
	ADJID_AdjustPrinterPrevue,
	ADJID_AdjustPublicDisplayCtrl,
	ADJID_AdjustPxpBlendLevel,
	ADJID_AdjustRed,
	ADJID_AdjustRedGain,
	ADJID_AdjustRedOff,
	ADJID_AdjustSaturation,
	ADJID_AdjustScartRGBViaOverlay,
	ADJID_AdjustSharpNoise,
	ADJID_AdjustSharpness,
	ADJID_AdjustSharpnessRGB,
	ADJID_AdjustSpeakerAudioSource,
	ADJID_AdjustSpeakers,
	ADJID_AdjustTNR,
	ADJID_AdjustThreeTwoFilmDisplayMode,
	ADJID_AdjustTwoStageProcessing,
	ADJID_AdjustUartSelect,
	ADJID_AdjustVBIService,
	ADJID_AdjustVStart,
	ADJID_AdjustVStartPip,
	ADJID_AdjustZoom,
	ADJID_FAdjustAmplitudeValue,
	ADJID_FAdjustAmplitudeValue2,
	ADJID_FAdjustColorTempCommon,
	ADJID_FAdjustGain_B,
	ADJID_FAdjustGain_G,
	ADJID_FAdjustGain_R,
	ADJID_FAdjustIspMode,
	ADJID_FAdjustNormalPresetGamma18Common,
	ADJID_FAdjustOffset1_B,
	ADJID_FAdjustOffset1_G,
	ADJID_FAdjustOffset1_R,
	ADJID_FAdjustOffset2_B,
	ADJID_FAdjustOffset2_G,
	ADJID_FAdjustOffset2_R,
	ADJID_FAdjustPeriodValue,
	ADJID_FAdjustPeriodValue2,
	ADJID_FAdjustReadReg,
	ADJID_FAdjustRegisterNumber,
	ADJID_FAdjustSpreadEnable,
	ADJID_FAdjustTimeUsedHour,
	ADJID_FAdjustTimeUsedMin,
	ADJID_FAdjustUserPresetCommon,
	ADJID_FAdjustWriteReg,
	ADJID_FactoryAdjustADCValues,
	ADJID_SetOsdTimeout,
	ADJID_VWD_ApplyHighLightWindow,
	ADJID_VWD_Switch
} AdjFuncEnum;

extern BYTE ROM * ROM gmv_OsdAdjusterFuncSet[164];

// gmv_OsdMinMaxFuncSet definition
typedef enum 
{
	EXTRID_MaxHStart = 0,
	EXTRID_MaxHTotal,
	EXTRID_MaxVStart,
	EXTRID_MinHStart,
	EXTRID_MinHTotal,
	EXTRID_MinVStart
} ExtrFuncEnum;

extern BYTE ROM * ROM gmv_OsdMinMaxFuncSet[6];

// gmv_OsdStepFuncSet definition
typedef enum 
{
	SFID_BallisticAcceleration = 0,
	SFID_BallisticAccelerationForUserBlue,
	SFID_BallisticAccelerationForUserGreen,
	SFID_BallisticAccelerationForUserRed
} StepFuncEnum;

extern BYTE ROM * ROM gmv_OsdStepFuncSet[4];

extern WORD ROM gmc_AdjvNullValue;

typedef enum 
{
	ADJV_TNR = 0,
	ADJV_MADI = 10,
	ADJV_CCS = 20,
	ADJV_SharpNoise = 30,
	ADJV_DCDiMain = 40,
	ADJV_DCDiPip = 50,
	ADJV_MPEGNRMode = 60,
	ADJV_MPEGNRThresh0 = 70,
	ADJV_MPEGNRThresh1 = 80,
	ADJV_MPEGNRThresh2 = 90,
	ADJV_LCDOverdriveNoiseCoring = 100,
	ADJV_ThreeTwoFilmDisplayMode = 110,
	ADJV_VBI_ServicePreferred = 120,
	ADJV_SharpnessPip = 130,
	ADJV_BlueStretch = 140,
	ADJV_SharpnessRGB = 150,
	ADJV_SharpnessRGBpip = 160,
	ADJV_AVSDelay = 170,
	ADJV_AudioVolume = 180,
	ADJV_ADCCalibrationMethod_Comp = 190,
	ADJV_ADCCalibrationMethod_VGA = 200,
	ADJV_AspectRatioMain = 210,
	ADJV_AspectRatioPip = 220,
	ADJV_CurrentInputMain = 230,
	ADJV_CurrentInputPip = 240,
	ADJV_DynamicContrast = 250,
	ADJV_FilmMode = 260,
	ADJV_FleshToneComp = 270,
	ADJV_ImageScheme = 280,
	ADJV_LCDOverdrive = 290,
	ADJV_LetterboxEnable = 300,
	ADJV_MPEGNR = 310,
	ADJV_OsdHPosition = 320,
	ADJV_OsdVPosition = 330,
	ADJV_OsdLanguage = 340,
	ADJV_OsdRotation = 350,
	ADJV_OsdTimeout = 360,
	ADJV_OverscanEnable = 370,
	ADJV_PowerState = 380,
	ADJV_Sharpness = 390,
	ADJV_SleepAMPM = 400,
	ADJV_SleepDay = 410,
	ADJV_SleepHour = 420,
	ADJV_SleepMin = 430,
	ADJV_SleepMinsLeft = 440,
	ADJV_ThreeDNR = 450,
	ADJV_TVRating = 460,
	ADJV_TVUnrated = 470,
	ADJV_Version = 480,
	ADJV_WakeAMPM = 490,
	ADJV_WakeDay = 500,
	ADJV_WakeHour = 510,
	ADJV_WakeMin = 520,
	ADJV_MPRating = 530,
	ADJV_AVSDelayTime = 540,
	ADJV_CC_On = 550,
	ADJV_AudioMute = 560,
	ADJV_MPipConfig = 570,
	ADJV_ParentalPassword = 580,
	ADJV_PipMode = 590,
	ADJV_PipPosition = 600,
	ADJV_PipSize = 610,
	ADJV_ScrollMenuItem = 620,
	ADJV_MainRouteModeComponent = 630,
	ADJV_MainRouteModeScartRGB = 640,
	ADJV_PipRouteModeComponent = 650,
	ADJV_PipRouteModeScartRGB = 660,
	ADJV_TVYouth7Subcode = 670,
	ADJV_TVPGSubcode = 680,
	ADJV_TV14Subcode = 690,
	ADJV_TVMASubcode = 700,
	ADJV_DecoderAGCMethod = 710,
	ADJV_CCSforHD = 720,
	ADJV_TwoStageProcessing = 730,
	ADJV_ManualTVMHzFreq = 740,
	ADJV_ManualTVkHzFreq = 750,
	ADJV_TVFreqFineTune = 760,
	ADJV_TVManualScanRequired = 770,
	ADJV_ScartRgbViaOverlay = 780,
	ADJV_ADCCalibrationMethod_CVBS = 790,
	ADJV_ADCCalibrationMethod_InternalDac = 800,
	ADJV_AutoAspectRatio = 810,
	ADJV_ADCCalibrationMethod_SCART = 820,
	ADJV_EnhancerEnable = 830,
	ADJV_OldEnhancerEnable = 840,
	ADJV_OldEnhancerRouting = 850,
	ADJV_ColorResourceRouting = 860,
	ADJV_ADCCalibrationMethod_SIF = 870,
	ADJV_VariableForLineout = 880,
	ADJV_GameMode = 890,
	ADJV_XvYcc = 900,
	ADJV_AudioDownMix = 910,
	ADJV_ColorSpace = 920,
	ADJV_VwdFlag = 930,
	ADJV_VwdDemo = 940,
	ADJV_AudioMainInput = 950,
	ADJV_AudioMainOutput = 960,
	ADJV_AudioPipInput = 970,
	ADJV_AudioPipOutput = 980,
	ADJV_OSDG1Blend = 990,
	ADJV_OSDG2Blend = 1000,
	ADJV_OSDG3Blend = 1010,
	ADJV_CaptureM = 1020,
	ADJV_ImageRotation = 1030,
	ADJV_OSD_4Kx2K_Port = 1040,
	ADJV_DPSWitch = 1050,
	ADJV_OsdRotation_Auto = 1060,
	ADJV_Speakers = 1070,
	ADJV_Headphones = 1080,
	ADJV_SpeakerAudioSource = 1090,
	ADJV_HeadphoneAudioSource = 1100,
	ADJV_OsdBlend = 1110,
	ADJV_PwrAudio = 1120,
	ADJV_SavingBitFlags = 1130,
	ADJV_OSDLock = 1140,
	ADJV_OSDHardLock = 1150,
	ADJV_RunBurnInModeFlag = 1160,
	ADJV_OsdVPosition1 = 1170,
	ADJV_OsdHPosition1 = 1180,
	ADJV_PIPTimer = 1190,
	ADJV_PIPMHide = 1200,
	ADJV_HideIconFlag = 1210,
	ADJV_DdcciOnOffFlag = 1220,
	ADJV_PersonalKey1 = 1230,
	ADJV_PersonalKey2 = 1240,
	ADJV_PersonalKey3 = 1250,
	ADJV_ButtonSoundOff = 1260,
	ADJV_AutoAdjustJump = 1270,
	ADJV_MenuOnOffFlag = 1280,
	ADJV_WakeUpByTouchPad = 1290,
	ADJV_PowerKeyPressedFlag = 1300,
	ADJV_CustomColorSelection = 1310,
	ADJV_PipBrightness = 1320,
	ADJV_PipContrast = 1330,
	ADJV_PipSaturation = 1340,
	ADJV_PipHue = 1350,
	ADJV_PipUserRedGain = 1360,
	ADJV_PipUserGreenGain = 1370,
	ADJV_PipUserBlueGain = 1380,
	ADJV_PipUserRedOff = 1390,
	ADJV_PipUserGreenOff = 1400,
	ADJV_PipUserBlueOff = 1410,
	ADJV_PipColorTemp = 1420,
	ADJV_PipGammaTable = 1430,
	ADJV_PipImageScheme = 1440,
	ADJV_PipColorFormat = 1450,
	ADJV_PipColorMode = 1460,
	ADJV_PipVideoImageMode = 1470,
	ADJV_PipGraphicsImageMode = 1480,
	ADJV_PipGammaMode = 1490,
	ADJV_StoredPipMode = 1500,
	ADJV_OSDMenuLocation = 1510,
	ADJV_EnergySmartOnOffFlag = 1520,
	ADJV_LCDCondition_Save = 1530,
	ADJV_Contrast_Vwd = 1540,
	ADJV_Sharpness_Vwd = 1550,
	ADJV_Offset_Vwd = 1560,
	ADJV_Hue_Vwd = 1570,
	ADJV_Saturation_Vwd = 1580,
	ADJV_DUMSwitch0 = 1590,
	ADJV_HDMIEDIDPrimeMode = 1600,
	ADJV_DUMSwitch = 1610,
	ADJV_ModeIndependentPresetModesWB_StandardDUMSwitch = 1612,
	ADJV_ModeIndependentPresetModesWB_MultimediaDUMSwitch = 1622,
	ADJV_ModeIndependentPresetModesWB_MovieDUMSwitch = 1632,
	ADJV_ModeIndependentPresetModesWB_GameDUMSwitch = 1642,
	ADJV_ModeIndependentPresetModesWB_TextDUMSwitch = 1652,
	ADJV_ModeIndependentPresetModesWB_ColorTempDUMSwitch = 1662,
	ADJV_ModeIndependentPresetModesWB_AdobeRGBDUMSwitch = 1672,
	ADJV_ModeIndependentPresetModesWB_sRGBDUMSwitch = 1682,
	ADJV_ModeIndependentPresetModesWB_CAL1DUMSwitch = 1692,
	ADJV_ModeIndependentPresetModesWB_CAL2DUMSwitch = 1702,
	ADJV_ModeIndependentPresetModesWB_CustomColorDUMSwitch = 1712,
	ADJV_PxpBlendLevel = 1722,
	ADJV_CurrentInputMainDIP = 1732,
	ADJV_CurrentInputPxpDIP = 1742,
	ADJV_MainMode = 1752,
	ADJV_MainPosition = 1762,
	ADJV_OSDZoom = 1772,
	ADJV_LampBrightness = 1782,
	ADJV_PD_MainCtrl = 1792,
	ADJV_PD_PxpCtrl = 1802,
	ADJV_UartSelect = 1812,
	ADJV_OutputAspectRatio = 1822,
	ADJV_OutputMode = 1832,
	ADJV_MainBlendLevel = 1842,
	ADJV_BlendSpeed = 1852,
	ADJV_DynamicEDID = 1862,
	ADJV_DimEffect = 1872,
	ADJV_PanelProtect = 1882,
	ADJV_OSDAudioVolume = 1892,
	ADJV_PanelNumber = 1902,
	ADJV_SerlCmdPanelHStart = 1912,
	ADJV_SerlCmdPanelVStart = 1922,
	ADJV_SerlCmdPanelHLeng = 1932,
	ADJV_SerlCmdPanelVWide = 1942,
	ADJV_PIPScalerSW = 1952,
	ADJV_PipAutoScalerSW = 1962,
	ADJV_ParentalBlockStateFlagMain = 1972,
	ADJV_ParentalBlockStateFlagPip = 1982,
	ADJV_ChannelBlockStateFlag = 1992,
	ADJV_ChannelBlockStateFlagPip = 2002,
	ADJV_ChannelName = 2012,
	ADJV_Digit1ChannelName = 2014,
	ADJV_Digit2ChannelName = 2024,
	ADJV_Digit3ChannelName = 2034,
	ADJV_Digit4ChannelName = 2044,
	ADJV_Digit5ChannelName = 2054,
	ADJV_Digit6ChannelName = 2064,
	ADJV_Digit7ChannelName = 2074,
	ADJV_Digit8ChannelName = 2084,
	ADJV_GlobalChannelNameGroupPIPScalerSW = 2094,
	ADJV_GlobalChannelNameGroupDigit1PIPScalerSW = 2096,
	ADJV_GlobalChannelNameGroupDigit2PIPScalerSW = 2106,
	ADJV_GlobalChannelNameGroupDigit3PIPScalerSW = 2116,
	ADJV_GlobalChannelNameGroupDigit4PIPScalerSW = 2126,
	ADJV_GlobalChannelNameGroupDigit5PIPScalerSW = 2136,
	ADJV_GlobalChannelNameGroupDigit6PIPScalerSW = 2146,
	ADJV_GlobalChannelNameGroupDigit7PIPScalerSW = 2156,
	ADJV_GlobalChannelNameGroupDigit8PIPScalerSW = 2166,
	ADJV_Freeze = 2176,
	ADJV_MultiPipStateFlag = 2186,
	ADJV_OsdMPipHPos = 2196,
	ADJV_OsdMPipVPos = 2206,
	ADJV_OsdMPipChannel = 2216,
	ADJV_SideBySideFocus = 2226,
	ADJV_OSDBottomPos = 2236,
	ADJV_OSDCenterPos = 2246,
	ADJV_OSDTopHPos = 2256,
	ADJV_OSDTopVPos = 2266,
	ADJV_VChipPassword = 2276,
	ADJV_Month = 2286,
	ADJV_Date = 2296,
	ADJV_Year = 2306,
	ADJV_Hour = 2316,
	ADJV_Min = 2326,
	ADJV_AMPM = 2336,
	ADJV_InfoDisplayOn = 2346,
	ADJV_PrevPipSource = 2356,
	ADJV_ChannelFreqSlider = 2366,
	ADJV_ChannelFreqValue = 2376,
	ADJV_FactoryState = 2386,
	ADJV_RegAddr = 2396,
	ADJV_RegVal = 2406,
	ADJV_PreviousPipMode = 2416,
	ADJV_ChannelNameEntry1 = 2426,
	ADJV_ChannelNameEntry2 = 2436,
	ADJV_ChannelNameEntry3 = 2446,
	ADJV_ChannelNameEntry4 = 2456,
	ADJV_ChannelNameEntry5 = 2466,
	ADJV_PtrSegment = 2476,
	ADJV_PtrOffset = 2486,
	ADJV_OffsetGain = 2496,
	ADJV_Offset1_1OffsetGain = 2498,
	ADJV_Offset1_2OffsetGain = 2508,
	ADJV_Offset1_3OffsetGain = 2518,
	ADJV_Offset2_1OffsetGain = 2528,
	ADJV_Offset2_2OffsetGain = 2538,
	ADJV_Offset2_3OffsetGain = 2548,
	ADJV_Gain_1OffsetGain = 2558,
	ADJV_Gain_2OffsetGain = 2568,
	ADJV_Gain_3OffsetGain = 2578,
	ADJV_ChannelNumDisplayFlag = 2588,
	ADJV_ChannelNumAppendDisplayFlag = 2598,
	ADJV_OsdScale100Percent = 2608,
	ADJV_OsdFullScreenXPercent = 2618,
	ADJV_OsdFullScreenYPercent = 2628,
	ADJV_OsdState = 2638,
	ADJV_OsdBitFlags = 2648,
	ADJV_CurrentBlockedTVRatingSubcodeMain = 2658,
	ADJV_CurrentBlockedTVRatingSubcodePip = 2668,
	ADJV_MPipTileSet = 2678,
	ADJV_ChipIDdigit1 = 2688,
	ADJV_ChipIDdigit2 = 2698,
	ADJV_ChipIDdigit3 = 2708,
	ADJV_ChipIDdigit4 = 2718,
	ADJV_ColorSystem = 2728,
	ADJV_TtxNoSignalFlag = 2738,
	ADJV_InputPortList = 2748,
	ADJV_GlobalInputPortListGroupInputPort_1InputPortList = 2750,
	ADJV_GlobalInputPortListGroupInputPort_2InputPortList = 2760,
	ADJV_GlobalInputPortListGroupInputPort_3InputPortList = 2770,
	ADJV_GlobalInputPortListGroupInputPort_4InputPortList = 2780,
	ADJV_GlobalInputPortListGroupInputPort_5InputPortList = 2790,
	ADJV_InputPortCount = 2800,
	ADJV_DisplayPortName = 2810,
	ADJV_OldOrNewPortChange = 2820,
	ADJV_Str1_seg = 2830,
	ADJV_Str2_seg = 2840,
	ADJV_Str3_seg = 2850,
	ADJV_Str4_seg = 2860,
	ADJV_Str1_ofs = 2870,
	ADJV_Str2_ofs = 2880,
	ADJV_Str3_ofs = 2890,
	ADJV_Str4_ofs = 2900,
	ADJV_CecDeviceName_seg = 2910,
	ADJV_CecDeviceName_ofs = 2920,
	ADJV_CecDeviceType = 2930,
	ADJV_DontRemoveOSD = 2940,
	ADJV_CecRecordOnExtPlugNumber = 2950,
	ADJV_CecDevicePowerStatus = 2960,
	ADJV_CecStatusText1_seg = 2970,
	ADJV_CecStatusText1_ofs = 2980,
	ADJV_CecStatusText2_seg = 2990,
	ADJV_CecStatusText2_ofs = 3000,
	ADJV_CecStatusText3_seg = 3010,
	ADJV_CecStatusText3_ofs = 3020,
	ADJV_CecStatusLineCounter = 3030,
	ADJV_CecRecordDateDay = 3040,
	ADJV_CecRecordDateMonth = 3050,
	ADJV_CecRecordTimeHours = 3060,
	ADJV_CecRecordTimeMinutes = 3070,
	ADJV_CecRecordDurationHours = 3080,
	ADJV_CecRecordDurationMinutes = 3090,
	ADJV_CecHDMITreeMode = 3100,
	ADJV_CecDeviceSelectedFromHDMITree = 3110,
	ADJV_CecSystemAudioStatus = 3120,
	ADJV_IspFlashWrPercent = 3130,
	ADJV_InFwMajor = 3140,
	ADJV_InFwMinor = 3150,
	ADJV_InFwRc = 3160,
	ADJV_NoSignal = 3170,
	ADJV_OsdVPosCenter = 3180,
	ADJV_OsdHPosCenter = 3190,
	ADJV_CurrentOutput = 3200,
	ADJV_PowerOnFlag = 3210,
	ADJV_PipOnScreen = 3220,
	ADJV_OsdVPosFloat = 3230,
	ADJV_OsdHPosFloat = 3240,
	ADJV_EnableNoCable = 3250,
	ADJV_MainImageZoom = 3260,
	ADJV_CurrentSourceInputFlag = 3270,
	ADJV_NoInpSignalStateFlag = 3280,
	ADJV_OutOfRangeStateFlag = 3290,
	ADJV_NoCableStateFlag = 3300,
	ADJV_BitFlags = 3310,
	ADJV_OSDHposCenterPip = 3320,
	ADJV_OSDVposCenterPip = 3330,
	ADJV_CustomSplashScreen = 3340,
	ADJV_MenuOn = 3350,
	ADJV_Flag = 3360,
	ADJV_Flagg = 3370,
	ADJV_ScanResult = 3380,
	ADJV_InputSourceFlag = 3390,
	ADJV_NoSignalMSGFlag = 3400,
	ADJV_MenuAdjust = 3410,
	ADJV_RequestDoAutoFlag = 3420,
	ADJV_DynamicTextValue = 3430,
	ADJV_DuringSourceScan = 3440,
	ADJV_GlobalOffset1_R = 3450,
	ADJV_GlobalOffset1_G = 3460,
	ADJV_GlobalOffset1_B = 3470,
	ADJV_GlobalOffset2_R = 3480,
	ADJV_GlobalOffset2_G = 3490,
	ADJV_GlobalOffset2_B = 3500,
	ADJV_GlobalGain_R = 3510,
	ADJV_GlobalGain_G = 3520,
	ADJV_GlobalGain_B = 3530,
	ADJV_BurnInModeFun = 3540,
	ADJV_GlobalLCDOnOffFlag = 3550,
	ADJV_GlobalRotationOnOffFlag = 3560,
	ADJV_GlobalXPosOffset = 3570,
	ADJV_GlobalYPosOffset = 3580,
	ADJV_PIPMessagesXPos = 3590,
	ADJV_PIPMessagesYPos = 3600,
	ADJV_PIPIconsXPos = 3610,
	ADJV_PIPIconsYPos = 3620,
	ADJV_GlobalDynamicContrast = 3630,
	ADJV_GlobalLCDConditionXPos = 3640,
	ADJV_GlobalLCDConditionYPos = 3650,
	ADJV_GlobalLCDConditionPosition = 3660,
	ADJV_ForceBGColor = 3670,
	ADJV_MenuRemovableFlag = 3680,
	ADJV_ForcePowerSavingFlag = 3690,
	ADJV_GlobalMenuKeyPressed = 3700,
	ADJV_IICSlaveAddress = 3710,
	ADJV_ISP_Mode = 3720,
	ADJV_PIPMessageOnOffFlag = 3730,
	ADJV_StateTempFlag = 3740,
	ADJV_KeySpeedUpFlag = 3750,
	ADJV_OSDStateFlag = 3760,
	ADJV_PowerKeyFlag = 3770,
	ADJV_DCACBottonSoundFlag = 3780,
	ADJV_LanguageStateFlag = 3790,
	ADJV_PIPEnFlag = 3800,
	ADJV_AutoSourceStateFlag = 3810,
	ADJV_FlyStateFlag = 3820,
	ADJV_PowerSavingFlag = 3830,
	ADJV_ServiceMenuFlag = 3840,
	ADJV_DiagnosticTestState = 3850,
	ADJV_GlobalRotationEnabled = 3860,
	ADJV_InfoFlag = 3870,
	ADJV_DCRTestOnOffFlag = 3880,
	ADJV_PIPMessageOnFlag = 3890,
	ADJV_AdjustInputColorFormatByOSD = 3900,
	ADJV_PIPNoCableMessageOnFlag = 3910,
	ADJV_PIPOORMessageOnFlag = 3920,
	ADJV_FactoryFlag = 3930,
	ADJV_IsIconUpdateDisable = 3940,
	ADJV_InputMenuOn = 3950,
	ADJV_SpreadAmpValue = 3960,
	ADJV_SpreadPeriodValue = 3970,
	ADJV_SpreadAmpValue2 = 3980,
	ADJV_SpreadPeriodValue2 = 3990,
	ADJV_MainMessageOnFlag = 4000,
	ADJV_VGADisplayResetFlag = 4010,
	ADJV_InputMenuSourceChanged = 4020,
	ADJV_NoCablePowerDownMins = 4030,
	ADJV_NoCablePowerDownSecs = 4040,
	ADJV_NoCablePowerDownFlag = 4050,
	ADJV_NoCablePowerDownTime = 4060,
	ADJV_EnergyUsedLevel = 4070,
	ADJV_IsCustomColorAdjustMenu = 4080,
	ADJV_IsEnergySmartToggledFlag = 4090,
	ADJV_PtrSegmentDynamicString = 4100,
	ADJV_PtrOffsetDynamicString = 4110,
	ADJV_OSD_Temp = 4120,
	ADJV_BrightnessItemGreyout = 4130,
	ADJV_StartSmartISP = 4140,
	ADJV_EDIDWP_Temp = 4150,
	ADJV_OSDMessageCtrl = 4160,
	ADJV_VWD_OSD_Enable = 4170,
	ADJV_UnStableByOSD = 4180,
	ADJV_SundBox_OSD_True = 4190,
	ADJV_SundBox_OSD_False = 4200,
	ADJV_PIPSourceChange_OSD = 4210,
	ADJV_AudioPCM_Messaeg = 4220,
	ADJV_EnableDDC2BiAddress0x7C = 4230,
	ADJV_PortChangeOnChannel = 4240,
	ADJV_BoardID_1 = 4250,
	ADJV_BoardID_2 = 4260,
	ADJV_BoardID_3 = 4270,
	ADJV_BoardID_4 = 4280,
	ADJV_BoardID_VerifyCnt = 4290,
	ADJV_OSDCurrentStates = 4300,
	ADJV_UserEvent = 4310,
	ADJV_PxpImageZoom = 4320,
	ADJV_DE_Week = 4330,
	ADJV_DE_YEAR = 4340,
	ADJV_KeyChanged = 4350,
	ADJV_DyEDIDPort = 4360,
	ADJV_SelectPanel = 4370,
	ADJV_PanelProtectAdjustHStartFlag = 4380,
	ADJV_HotKeyState = 4390,
	ADJV_HStart = 4400,
	ADJV_VStart = 4410,
	ADJV_HTotal = 4420,
	ADJV_HSyncPhase = 4430,
	ADJV_HSyncDelay = 4440,
	ADJV_VSyncDelay = 4450,
	ADJV_HStartBestValue = 4460,
	ADJV_VStartBestValue = 4470,
	ADJV_HTotalBestValue = 4480,
	ADJV_Acm3BlueLuma = 4490,
	ADJV_Acm3CyanLuma = 4500,
	ADJV_Acm3GreenLuma = 4510,
	ADJV_Acm3MagentaLuma = 4520,
	ADJV_Acm3RedLuma = 4530,
	ADJV_Acm3YellowLuma = 4540,
	ADJV_Acm3BlackLuma = 4550,
	ADJV_Acm3WhiteLuma = 4560,
	ADJV_Acm3BlueHue = 4570,
	ADJV_Acm3CyanHue = 4580,
	ADJV_Acm3GreenHue = 4590,
	ADJV_Acm3MagentaHue = 4600,
	ADJV_Acm3RedHue = 4610,
	ADJV_Acm3YellowHue = 4620,
	ADJV_Acm3BlackHue = 4630,
	ADJV_Acm3WhiteHue = 4640,
	ADJV_Acm3BlueSat = 4650,
	ADJV_Acm3CyanSat = 4660,
	ADJV_Acm3GreenSat = 4670,
	ADJV_Acm3MagentaSat = 4680,
	ADJV_Acm3RedSat = 4690,
	ADJV_Acm3YellowSat = 4700,
	ADJV_Acm3BlackSat = 4710,
	ADJV_Acm3WhiteSat = 4720,
	ADJV_Brightness = 4730,
	ADJV_Brightness_All = 4740,
	ADJV_Brightness_Text = 4750,
	ADJV_Brightness_CAL1 = 4760,
	ADJV_Brightness_CAL2 = 4770,
	ADJV_Contrast = 4780,
	ADJV_Contrast_All = 4790,
	ADJV_Contrast_Text = 4800,
	ADJV_Contrast_CAL1 = 4810,
	ADJV_Contrast_CAL2 = 4820,
	ADJV_Saturation = 4830,
	ADJV_Saturation_Movie = 4840,
	ADJV_Saturation_Game = 4850,
	ADJV_Hue = 4860,
	ADJV_Hue_Movie = 4870,
	ADJV_Hue_Game = 4880,
	ADJV_UserRedGain = 4890,
	ADJV_UserGreenGain = 4900,
	ADJV_UserBlueGain = 4910,
	ADJV_UserRedOff = 4920,
	ADJV_UserGreenOff = 4930,
	ADJV_UserBlueOff = 4940,
	ADJV_ColorTemp = 4950,
	ADJV_GammaTable = 4960,
	ADJV_UserRed = 4970,
	ADJV_UserGreen = 4980,
	ADJV_UserBlue = 4990,
	ADJV_ColorFormat = 5000,
	ADJV_VideoImageMode = 5010,
	ADJV_GraphicsImageMode = 5020,
	ADJV_PresetColorTemp = 5030,
	ADJV_PresetColorSpace = 5040,
	ADJV_ColorMode = 5050,
	ADJV_PortSharpness = 5060,
	ADJV_PortSharpness_All = 5070,
	ADJV_PortSharpness_Text = 5080,
	ADJV_PortImageZoom = 5090,
	ADJV_PortAspectRatio = 5100,
	ADJV_DCR = 5110,
	ADJV_PortSchemeDependentPresetModesWB_StandardDCR = 5112,
	ADJV_PortSchemeDependentPresetModesWB_MultimediaDCR = 5122,
	ADJV_PortSchemeDependentPresetModesWB_MovieDCR = 5132,
	ADJV_PortSchemeDependentPresetModesWB_GameDCR = 5142,
	ADJV_PortSchemeDependentPresetModesWB_TextDCR = 5152,
	ADJV_PortSchemeDependentPresetModesWB_ColorTempDCR = 5162,
	ADJV_PortSchemeDependentPresetModesWB_AdobeRGBDCR = 5172,
	ADJV_PortSchemeDependentPresetModesWB_sRGBDCR = 5182,
	ADJV_PortSchemeDependentPresetModesWB_CAL1DCR = 5192,
	ADJV_PortSchemeDependentPresetModesWB_CAL2DCR = 5202,
	ADJV_PortSchemeDependentPresetModesWB_CustomColorDCR = 5212,
	ADJV_ResponseTime = 5222,
	ADJV_GammaMode = 5232,
	ADJV_Saturation_YPbPr = 5242,
	ADJV_PresetPrinterPrevue = 5252,
	ADJV_PortTNR = 5262,
	ADJV_AcmRedHue = 5272,
	ADJV_AcmYellowHue = 5282,
	ADJV_AcmBlueSat = 5292,
	ADJV_AcmCyanSat = 5302,
	ADJV_AcmGreenSat = 5312,
	ADJV_AcmMagentaSat = 5322,
	ADJV_AcmRedSat = 5332,
	ADJV_AcmYellowSat = 5342,
	ADJV_MFMImageScheme = 5352,
	ADJV_InputColorDomain = 5362,
	ADJV_OutputColorType = 5372,
	ADJV_PortMPEGNRMode = 5382,
	ADJV_HStart_PIP = 5392,
	ADJV_VStart_PIP = 5402,
	ADJV_HTotal_PIP = 5412,
	ADJV_HSyncPhase_PIP = 5422,
	ADJV_HSyncDelay_PIP = 5432,
	ADJV_VSyncDelay_PIP = 5442,
	ADJV_FactoryVersion = 5452,
	ADJV_TimeUsedHour = 5462,
	ADJV_TimeUsedMin = 5472,
	ADJV_Offset1_VR = 5482,
	ADJV_Offset1_VG = 5492,
	ADJV_Offset1_VB = 5502,
	ADJV_Offset2_VR = 5512,
	ADJV_Offset2_VG = 5522,
	ADJV_Offset2_VB = 5532,
	ADJV_Gain_VR = 5542,
	ADJV_Gain_VG = 5552,
	ADJV_Gain_VB = 5562,
	ADJV_ColorT10000_R = 5572,
	ADJV_ColorT10000_G = 5582,
	ADJV_ColorT10000_B = 5592,
	ADJV_ColorT9300_R = 5602,
	ADJV_ColorT9300_G = 5612,
	ADJV_ColorT9300_B = 5622,
	ADJV_ColorT7500_R = 5632,
	ADJV_ColorT7500_G = 5642,
	ADJV_ColorT7500_B = 5652,
	ADJV_ColorT7200_R = 5662,
	ADJV_ColorT7200_G = 5672,
	ADJV_ColorT7200_B = 5682,
	ADJV_ColorT6500_R = 5692,
	ADJV_ColorT6500_G = 5702,
	ADJV_ColorT6500_B = 5712,
	ADJV_ColorT5700_R = 5722,
	ADJV_ColorT5700_G = 5732,
	ADJV_ColorT5700_B = 5742,
	ADJV_ColorT5000_R = 5752,
	ADJV_ColorT5000_G = 5762,
	ADJV_ColorT5000_B = 5772,
	ADJV_sRGB_Contrast = 5782,
	ADJV_sRGB_Brightness = 5792,
	ADJV_MacColor_R = 5802,
	ADJV_MacColor_G = 5812,
	ADJV_MacColor_B = 5822,
	ADJV_SpeadSpectrum_Mode = 5832,
	ADJV_SpeadSpectrum_Mode2 = 5842,
	ADJV_Debug_Mode = 5852,
	ADJV_ColorT9300_Brightness = 5862,
	ADJV_ColorT9300_Contrast = 5872,
	ADJV_ColorT6500_Brightness = 5882,
	ADJV_ColorT6500_Contrast = 5892,
	ADJV_UserColor_Contrast = 5902,
	ADJV_UserColor_Brightness = 5912,
	ADJV_Gm1601RegNumber = 5922,
	ADJV_Gm1601RegValue = 5932,
	ADJV_Gm1601RegWrite = 5942,
	ADJV_MonitorOnCount = 5952,
	ADJV_ConstantTimeUsedHour = 5962,
	ADJV_ConstantTimeUsedMin = 5972,
	ADJV_SoftKeyOnCount = 5982,
	ADJV_sRGB_R_Gamma18 = 5992,
	ADJV_sRGB_G_Gamma18 = 6002,
	ADJV_sRGB_B_Gamma18 = 6012,
	ADJV_FactoryOffset1_CR = 6022,
	ADJV_FactoryOffset1_CG = 6032,
	ADJV_FactoryOffset1_CB = 6042,
	ADJV_FactoryOffset2_CR = 6052,
	ADJV_FactoryOffset2_CG = 6062,
	ADJV_FactoryOffset2_CB = 6072,
	ADJV_FactoryGain_CR = 6082,
	ADJV_FactoryGain_CG = 6092,
	ADJV_FactoryGain_CB = 6102,
	ADJV_FactoryDDRSSC = 6112,
	ADJV_AddressNo = 6122,
	ADJV_DataW = 6132,
	ADJV_MonitorUsedHour = 6142,
	ADJV_MonitorUsedMin = 6152,
	ADJV_HDMIGraphics = 6162,
	ADJV_sRGBColor_R = 6172,
	ADJV_sRGBColor_G = 6182,
	ADJV_sRGBColor_B = 6192,
	ADJV_AdobeRGBColor_R = 6202,
	ADJV_AdobeRGBColor_G = 6212,
	ADJV_AdobeRGBColor_B = 6222,
	ADJV_BriBase_6500K = 6232,
	ADJV_BriBase_sRGB = 6242,
	ADJV_BriBase_AdobeRGB = 6252,
	ADJV_BriBase_Table1 = 6262,
	ADJV_BriBase_Table2 = 6272,
	ADJV_BriBase_Text = 6282,
	ADJV_Color_R1 = 6292,
	ADJV_Color_R2 = 6302,
	ADJV_Color_R3 = 6312,
	ADJV_Color_G1 = 6322,
	ADJV_Color_G2 = 6332,
	ADJV_Color_G3 = 6342,
	ADJV_Color_B1 = 6352,
	ADJV_Color_B2 = 6362,
	ADJV_Color_B3 = 6372,
	ADJV_AdobeColor_R1 = 6382,
	ADJV_AdobeColor_R2 = 6392,
	ADJV_AdobeColor_R3 = 6402,
	ADJV_AdobeColor_G1 = 6412,
	ADJV_AdobeColor_G2 = 6422,
	ADJV_AdobeColor_G3 = 6432,
	ADJV_AdobeColor_B1 = 6442,
	ADJV_AdobeColor_B2 = 6452,
	ADJV_AdobeColor_B3 = 6462,
	ADJV_SRGB_GAMMASELECT = 6472,
	ADJV_AdobeRGB_GAMMASELECT = 6482,
	ADJV_BoardID = 6492,
	ADJV_PanelSelect = 6502,
	ADJV_LOGO_Ctrl = 6512,
	ADJV_UartBaudRate = 6522,
	ADJV_AudioSelectFlag = 6532,
	ADJV_ACPowerOnCounter = 6542,
	ADJV_DCPowerOnCounter = 6552,
	ADJV_NULL = 0x7FFF
} AdjValEnum;

extern BYTE ROM gmv_UserDefAdjusterProperty[6562];

#endif  // ifndef OSD_UADJ_H_DEFINED
