////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_CLPT_H_DEFINED
#define OSD_CLPT_H_DEFINED

// Color Palletes Table externals definition
extern BYTE ROM ColorPalette5[];
extern BYTE ROM ColorPalette35[];
extern BYTE ROM ColorPalette1[];
extern BYTE ROM ColorPalette18[];
extern BYTE ROM ColorPalette26[];
extern BYTE ROM ColorPalette13[];
extern BYTE ROM ColorPalette15[];
extern BYTE ROM ColorPalette16[];
extern BYTE ROM ColorPalette38[];
extern BYTE ROM ColorPalette25[];
extern BYTE ROM ColorPalette21[];
extern BYTE ROM ColorPalette22[];
extern BYTE ROM ColorPalette42[];
extern BYTE ROM ColorPalette37[];
extern BYTE ROM ColorPalette2[];
extern BYTE ROM ColorPalette32[];
extern BYTE ROM ColorPalette24[];
extern BYTE ROM ColorPalette6[];
extern BYTE ROM ColorPalette40[];
extern BYTE ROM ColorPalette41[];
extern BYTE ROM ColorPalette8[];
extern BYTE ROM ColorPalette7[];
extern BYTE ROM ColorPalette30[];
extern BYTE ROM ColorPalette36[];
extern BYTE ROM ColorPalette10[];
extern BYTE ROM ColorPalette33[];
extern BYTE ROM ColorPalette9[];
extern BYTE ROM ColorPalette43[];
extern BYTE ROM ColorPalette11[];
extern BYTE ROM ColorPalette31[];
extern BYTE ROM ColorPalette44[];
extern BYTE ROM ColorPalette19[];
extern BYTE ROM ColorPalette20[];
extern BYTE ROM ColorPalette27[];
extern BYTE ROM ColorPalette17[];
extern BYTE ROM ColorPalette34[];
extern BYTE ROM ColorPalette23[];
extern BYTE ROM ColorPalette12[];
extern BYTE ROM ColorPalette28[];
extern BYTE ROM ColorPalette39[];
extern BYTE ROM ColorPalette29[];
extern BYTE ROM ColorPalette14[];
extern BYTE ROM ColorPalette4[];
extern BYTE ROM ColorPalette3[];
extern BYTE ROM ColorPalette0[];

#endif  // ifndef OSD_CLPT_H_DEFINED
