////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_ACT_H_DEFINED
#define OSD_ACT_H_DEFINED

// Actions definition
typedef enum 
{
	AID_GoToState_WORD = 0,
	AID_GoToState_BYTE,
	AID_SetSysAdjByte,
	AID_DrawText,
	AID_ResetTimer,
	AID_DrawBitmap,
	AID_SetOsdTimeout,
	AID_DrawSelectedText,
	AID_EraseControl,
	AID_LoadColorsInvisibleState,
	AID_DrawLongValue,
	AID_IncrementAdjuster,
	AID_UpdateLongValue,
	AID_SetAdjByte,
	AID_DecrementAdjuster,
	AID_UpdateSelectedLongValue,
	AID_UpdateSelectedSlider,
	AID_PIPSendMessage,
	AID_SaveModeIndependentSettings,
	AID_SavePortSchemeDependentSettings,
	AID_SetSysAdjSByte,
	AID_SetSysAdjSWord,
	AID_DrawSlider,
	AID_DrawSelectedLongValue,
	AID_DrawSelectedSlider,
	AID_AllocateTile,
	AID_DeallocateTile,
	AID_DebugOSD,
	AID_DecState,
	AID_IncState,
	AID_HideOsd,
	AID_DrawOption1DStaticTextButton,
	AID_SetOSDMenuState,
	AID_DrawOption2DStaticTextButton,
	AID_DrawSelectedBitmap,
	AID_DrawOption1DStaticText,
	AID_DrawOption2DStaticText,
	AID_DrawOption3DStaticTextButton,
	AID_DrawOption4DStaticTextButton,
	AID_DrawRectangle,
	AID_ShowOsd,
	AID_SaveGrModeDependentSettings,
	AID_DrawSelectedOption2DStaticTextButton,
	AID_SetActiveDialog,
	AID_DrawDTimingInfo,
	AID_DrawSelectedOption1DStaticTextButton,
	AID_LoadColorsDialog,
	AID_DrawOption1D2StaticTextButton,
	AID_DrawDisabledText,
	AID_DrawSelectedOption1D2StaticTextButton,
	AID_DrawSelectedOption2D2StaticTextButton,
	AID_MultiPipTurnOff,
	AID_DrawOption2D2StaticTextButton,
	AID_DrawOption3DStaticText,
	AID_ClrBitFlag,
	AID_DrawSelectedOption3DStaticTextButton,
	AID_DrawSelectedOption4DStaticTextButton,
	AID_RestoreXYOffsetAfterPIPIconDraw,
	AID_DrawOption5DStaticTextButton,
	AID_RestorePipOnscreenState,
	AID_SaveFactorySettingsInNVR,
	AID_TurnLcdOff,
	AID_DrawOption4DStaticText,
	AID_DrawSelectedOption5DStaticTextButton,
	AID_DrawOption7DStaticTextButton,
	AID_EnableTile,
	AID_DrawOption1D2StaticText,
	AID_TurnLcdOn,
	AID_GetChipID,
	AID_SetDynamicStringPtr,
	AID_SetIspActionConfirm,
	AID_SetOsdRequestForPowerUp,
	AID_AdjustOsdBlend,
	AID_OSD_AdjustBrigntnessContrast,
	AID_SavePipOnScreenState,
	AID_SetWbMainChannel,
	AID_TurnBacklightOn,
	AID_DrawOption6DStaticTextButton,
	AID_DrawOption8DStaticTextButton,
	AID_DrawSelectedOption1D4StaticTextButton,
	AID_DrawSelectedOption2D4StaticTextButton,
	AID_DrawSelectedOption3D4StaticTextButton,
	AID_DrawSelectedOption4D4StaticTextButton,
	AID_DrawSelectedOption6DStaticTextButton,
	AID_OSDSendMessage,
	AID_RestoreRotatedXOffsetAfterIconDraw,
	AID_AdjustAudioMute,
	AID_DrawOption1D4StaticTextButton,
	AID_DrawOption2D4StaticTextButton,
	AID_DrawOption3D4StaticTextButton,
	AID_DrawOption4D4StaticTextButton,
	AID_Osd_Hide,
	AID_PostEvent,
	AID_ResetBurninTime,
	AID_AutoAdjust,
	AID_DrawDynamicText1,
	AID_DrawSelectedOption8DStaticTextButton,
	AID_FactoryReset,
	AID_SwapMainPip,
	AID_SysteHardReset,
	AID_DrawSelectedOption7DStaticTextButton,
	AID_LockOSD,
	AID_SetForceBackground,
	AID_ADCCalibration,
	AID_DrawDisabledBitmap,
	AID_EraseBitmap,
	AID_SaveState,
	AID_SetAdjSByte,
	AID_SetOsdReadyForPowerDown,
	AID_StartFlyingWindow,
	AID_StopFlyingWindow,
	AID_ToggleInfoDisplay,
	AID_ToggleMute,
	AID_UpdateSourceLeds,
	AID_gm_SetOsdRotation,
	AID_AdjustBlueGain,
	AID_AdjustBlueOff,
	AID_AdjustGreenGain,
	AID_AdjustGreenOff,
	AID_AdjustRedGain,
	AID_AdjustRedOff,
	AID_AdjustUartBaudRate,
	AID_ClrForceBackground,
	AID_DrawOption1D3StaticTextButton,
	AID_DrawOption2D2StaticText,
	AID_DrawOption2D3StaticTextButton,
	AID_DrawOption3D3StaticTextButton,
	AID_DrawOption5DStaticText,
	AID_DrawOption6DStaticText,
	AID_DrawOption8DStaticText,
	AID_EDID_WP_DISABLE,
	AID_EDID_WP_ENABLE,
	AID_FactoryGetADCValues,
	AID_IspThruDisplay,
	AID_PipBorderControl,
	AID_RequestSoftPowerOn,
	AID_RestoreLedState,
	AID_RestoreState,
	AID_SaveModeDep_gm57xx,
	AID_SetPIPIconXYOffset,
	AID_SetSharpnessNoiseCoringToTNR,
	AID_ToggleFreezeVar,
	AID_TurnSoundOff,
	AID_TurnSoundOn,
	AID_UpdateSlider,
	AID_AdjustOsdHPosition,
	AID_AdjustOsdRotation,
	AID_AdjustPipMode,
	AID_AutoConfig,
	AID_CancelNoSignalMsg,
	AID_DrawOption1DStaticTextExt,
	AID_DrawSelectedOption1D3StaticTextButton,
	AID_DrawSelectedOption2D3StaticTextButton,
	AID_DrawSelectedOption3D3StaticTextButton,
	AID_InitPIPIconPosition,
	AID_InitPanelSpectrum,
	AID_OSDHardLock,
	AID_OSDHardUnLock,
	AID_OsdBlend,
	AID_OsdFactoryMenuInfo,
	AID_RequestSoftPowerOff,
	AID_RequestUpdateCableStatus,
	AID_ResetAudioSetting,
	AID_ResetDisplaySettings,
	AID_SavePipPortSchemeDependent,
	AID_SetBackGroundColor,
	AID_SetIspAutoDetMode,
	AID_SetMessageHVPos,
	AID_SetRotatedIconXOffset,
	AID_StartNoCablePowerDownCounter,
	AID_StartNoCableSleep,
	AID_StopNoCablePowerDownCounter,
	AID_StoreACC2Mask,
	AID_UnLockOSD,
	AID_UpdateColorTemp
} ActionIDEnum;

typedef enum 
{
	CID_Condition70,
	CID_Condition93,
	CID_Condition27,
	CID_Condition199,
	CID_Condition65,
	CID_Condition90,
	CID_Condition67,
	CID_Condition668,
	CID_Condition28,
	CID_Condition36,
	CID_Condition22,
	CID_Condition214,
	CID_Condition384,
	CID_Condition442,
	CID_Condition74,
	CID_Condition412,
	CID_Condition639,
	CID_Condition227,
	CID_Condition52,
	CID_Condition144,
	CID_Condition135,
	CID_Condition105,
	CID_Condition228,
	CID_Condition225,
	CID_Condition224,
	CID_Condition226,
	CID_Condition223,
	CID_Condition240,
	CID_Condition0,
	CID_Condition673,
	CID_Condition631,
	CID_Condition17,
	CID_Condition359,
	CID_Condition360,
	CID_Condition357,
	CID_Condition358,
	CID_Condition518,
	CID_Condition519,
	CID_Condition440,
	CID_Condition197,
	CID_Condition198,
	CID_Condition66,
	CID_Condition115,
	CID_Condition277,
	CID_Condition219,
	CID_Condition220,
	CID_Condition217,
	CID_Condition239,
	CID_Condition564,
	CID_Condition102,
	CID_Condition692,
	CID_Condition114,
	CID_Condition627,
	CID_Condition92,
	CID_Condition172,
	CID_Condition181,
	CID_Condition243,
	CID_Condition244,
	CID_Condition64,
	CID_Condition443,
	CID_Condition628,
	CID_Condition517,
	CID_Condition218,
	CID_Condition91,
	CID_Condition630,
	CID_Condition536,
	CID_Condition68,
	CID_Condition69,
	CID_Condition213,
	CID_Condition141,
	CID_Condition153,
	CID_Condition534,
	CID_Condition535,
	CID_Condition247,
	CID_Condition245,
	CID_Condition246,
	CID_Condition441,
	CID_Condition273,
	CID_Condition276,
	CID_Condition274,
	CID_Condition275,
	CID_Condition272,
	CID_Condition448,
	CID_Condition445,
	CID_Condition446,
	CID_Condition447,
	CID_Condition444,
	CID_Condition474,
	CID_Condition641,
	CID_Condition229,
	CID_Condition323,
	CID_Condition321,
	CID_Condition322,
	CID_Condition320,
	CID_Condition251,
	CID_Condition594,
	CID_Condition215,
	CID_Condition200,
	CID_Condition541,
	CID_Condition59,
	CID_Condition189,
	CID_Condition554,
	CID_Condition459,
	CID_Condition410,
	CID_Condition411,
	CID_Condition615,
	CID_Condition288,
	CID_Condition271,
	CID_Condition529,
	CID_Condition146,
	CID_Condition438,
	CID_Condition437,
	CID_Condition629,
	CID_Condition278,
	CID_Condition475,
	CID_Condition133,
	CID_Condition592,
	CID_Condition593,
	CID_Condition595,
	CID_Condition596,
	CID_Condition597,
	CID_Condition591,
	CID_Condition104,
	CID_Condition532,
	CID_Condition242,
	CID_Condition279,
	CID_Condition624,
	CID_Condition241,
	CID_Condition313,
	CID_Condition328,
	CID_Condition140,
	CID_Condition538,
	CID_Condition604,
	CID_Condition605,
	CID_Condition606,
	CID_Condition566,
	CID_Condition603,
	CID_Condition46,
	CID_Condition63,
	CID_Condition540,
	CID_Condition539,
	CID_Condition461,
	CID_Condition324,
	CID_Condition325,
	CID_Condition327,
	CID_Condition400,
	CID_Condition401,
	CID_Condition402,
	CID_Condition403,
	CID_Condition409,
	CID_Condition406,
	CID_Condition408,
	CID_Condition405,
	CID_Condition407,
	CID_Condition45,
	CID_Condition614,
	CID_Condition613,
	CID_Condition612,
	CID_Condition611,
	CID_Condition469,
	CID_Condition470,
	CID_Condition467,
	CID_Condition468,
	CID_Condition471,
	CID_Condition280,
	CID_Condition282,
	CID_Condition283,
	CID_Condition281,
	CID_Condition563,
	CID_Condition424,
	CID_Condition427,
	CID_Condition425,
	CID_Condition428,
	CID_Condition429,
	CID_Condition426,
	CID_Condition284,
	CID_Condition286,
	CID_Condition287,
	CID_Condition285,
	CID_Condition216,
	CID_Condition306,
	CID_Condition312,
	CID_Condition309,
	CID_Condition307,
	CID_Condition310,
	CID_Condition311,
	CID_Condition308,
	CID_Condition361,
	CID_Condition618,
	CID_Condition62,
	CID_Condition61,
	CID_Condition619,
	CID_Condition623,
	CID_Condition57,
	CID_Condition56,
	CID_Condition201,
	CID_Condition134,
	CID_Condition314,
	CID_Condition537,
	CID_Condition430,
	CID_Condition431,
	CID_Condition432,
	CID_Condition47,
	CID_Condition433,
	CID_Condition622,
	CID_Condition543,
	CID_Condition121,
	CID_Condition60,
	CID_Condition180,
	CID_Condition72,
	CID_Condition73,
	CID_Condition561,
	CID_Condition50,
	CID_Condition51,
	CID_Condition48,
	CID_Condition49,
	CID_Condition568,
	CID_Condition565,
	CID_Condition567,
	CID_Condition344,
	CID_Condition44,
	CID_Condition319,
	CID_Condition549,
	CID_Condition548,
	CID_Condition454,
	CID_Condition453,
	CID_Condition452,
	CID_Condition455,
	CID_Condition456,
	CID_Condition329,
	CID_Condition175,
	CID_Condition177,
	CID_Condition174,
	CID_Condition176,
	CID_Condition1,
	CID_Condition5,
	CID_Condition2,
	CID_Condition6,
	CID_Condition29,
	CID_Condition33,
	CID_Condition34,
	CID_Condition31,
	CID_Condition30,
	CID_Condition32,
	CID_Condition43,
	CID_Condition138,
	CID_Condition55,
	CID_Condition103,
	CID_Condition413,
	CID_Condition625,
	CID_Condition616,
	CID_Condition435,
	CID_Condition436,
	CID_Condition632,
	CID_Condition636,
	CID_Condition634,
	CID_Condition633,
	CID_Condition635,
	CID_Condition99,
	CID_Condition100,
	CID_Condition249,
	CID_Condition248,
	CID_Condition472,
	CID_Condition387,
	CID_Condition637,
	CID_Condition289,
	CID_Condition270,
	CID_Condition544,
	CID_Condition127,
	CID_Condition145,
	CID_Condition170,
	CID_Condition53,
	CID_Condition54,
	CID_Condition178,
	CID_Condition58,
	CID_Condition476,
	CID_Condition477,
	CID_Condition513,
	CID_Condition514,
	CID_Condition132,
	CID_Condition562,
	CID_Condition113,
	CID_Condition598,
	CID_Condition434,
	CID_Condition109,
	CID_Condition14,
	CID_Condition16,
	CID_Condition101,
	CID_Condition173,
	CID_Condition129,
	CID_Condition130,
	CID_Condition131,
	CID_Condition142,
	CID_Condition512,
	CID_Condition657,
	CID_Condition656,
	CID_Condition569,
	CID_Condition570,
	CID_Condition571,
	CID_Condition250,
	CID_Condition494,
	CID_Condition492,
	CID_Condition495,
	CID_Condition493,
	CID_Condition552,
	CID_Condition171,
	CID_Condition191,
	CID_Condition572,
	CID_Condition509,
	CID_Condition511,
	CID_Condition499,
	CID_Condition501,
	CID_Condition503,
	CID_Condition497,
	CID_Condition672,
	CID_Condition23,
	CID_Condition96,
	CID_Condition395,
	CID_Condition394,
	CID_Condition508,
	CID_Condition396,
	CID_Condition510,
	CID_Condition397,
	CID_Condition393,
	CID_Condition498,
	CID_Condition391,
	CID_Condition500,
	CID_Condition392,
	CID_Condition502,
	CID_Condition390,
	CID_Condition496,
	CID_Condition473,
	CID_Condition506,
	CID_Condition507,
	CID_Condition504,
	CID_Condition505,
	CID_Condition194,
	CID_Condition183,
	CID_Condition182,
	CID_Condition161,
	CID_Condition582,
	CID_Condition581,
	CID_Condition583,
	CID_Condition88,
	CID_Condition600,
	CID_Condition601,
	CID_Condition602,
	CID_Condition139,
	CID_Condition165,
	CID_Condition169,
	CID_Condition466,
	CID_Condition381,
	CID_Condition374,
	CID_Condition525,
	CID_Condition524,
	CID_Condition232,
	CID_Condition233,
	CID_Condition230,
	CID_Condition231,
	CID_Condition25,
	CID_Condition26,
	CID_Condition24,
	CID_Condition523,
	CID_Condition559,
	CID_Condition354,
	CID_Condition356,
	CID_Condition352,
	CID_Condition355,
	CID_Condition351,
	CID_Condition353,
	CID_Condition350,
	CID_Condition349,
	CID_Condition659,
	CID_Condition587,
	CID_Condition521,
	CID_Condition234,
	CID_Condition235,
	CID_Condition347,
	CID_Condition348,
	CID_Condition345,
	CID_Condition346,
	CID_Condition164,
	CID_Condition106,
	CID_Condition166,
	CID_Condition464,
	CID_Condition465,
	CID_Condition458,
	CID_Condition460,
	CID_Condition457,
	CID_Condition451,
	CID_Condition449,
	CID_Condition450,
	CID_Condition462,
	CID_Condition463,
	CID_Condition290,
	CID_Condition292,
	CID_Condition293,
	CID_Condition291,
	CID_Condition414,
	CID_Condition415,
	CID_Condition416,
	CID_Condition421,
	CID_Condition420,
	CID_Condition302,
	CID_Condition304,
	CID_Condition305,
	CID_Condition303,
	CID_Condition666,
	CID_Condition665,
	CID_Condition664,
	CID_Condition667,
	CID_Condition336,
	CID_Condition331,
	CID_Condition335,
	CID_Condition334,
	CID_Condition332,
	CID_Condition333,
	CID_Condition330,
	CID_Condition382,
	CID_Condition383,
	CID_Condition380,
	CID_Condition378,
	CID_Condition379,
	CID_Condition377,
	CID_Condition364,
	CID_Condition365,
	CID_Condition362,
	CID_Condition363,
	CID_Condition294,
	CID_Condition296,
	CID_Condition297,
	CID_Condition295,
	CID_Condition417,
	CID_Condition418,
	CID_Condition419,
	CID_Condition423,
	CID_Condition422,
	CID_Condition298,
	CID_Condition300,
	CID_Condition301,
	CID_Condition299,
	CID_Condition342,
	CID_Condition338,
	CID_Condition343,
	CID_Condition341,
	CID_Condition339,
	CID_Condition340,
	CID_Condition337,
	CID_Condition375,
	CID_Condition376,
	CID_Condition373,
	CID_Condition371,
	CID_Condition372,
	CID_Condition370,
	CID_Condition368,
	CID_Condition369,
	CID_Condition366,
	CID_Condition367,
	CID_Condition385,
	CID_Condition386,
	CID_Condition646,
	CID_Condition222,
	CID_Condition647,
	CID_Condition648,
	CID_Condition221,
	CID_Condition610,
	CID_Condition609,
	CID_Condition599,
	CID_Condition653,
	CID_Condition654,
	CID_Condition655,
	CID_Condition202,
	CID_Condition4,
	CID_Condition8,
	CID_Condition76,
	CID_Condition79,
	CID_Condition78,
	CID_Condition81,
	CID_Condition20,
	CID_Condition13,
	CID_Condition18,
	CID_Condition3,
	CID_Condition7,
	CID_Condition83,
	CID_Condition85,
	CID_Condition19,
	CID_Condition11,
	CID_Condition12,
	CID_Condition84,
	CID_Condition86,
	CID_Condition21,
	CID_Condition15,
	CID_Condition77,
	CID_Condition80,
	CID_Condition37,
	CID_Condition41,
	CID_Condition42,
	CID_Condition39,
	CID_Condition38,
	CID_Condition40,
	CID_Condition116,
	CID_Condition117,
	CID_Condition122,
	CID_Condition123,
	CID_Condition187,
	CID_Condition585,
	CID_Condition584,
	CID_Condition680,
	CID_Condition676,
	CID_Condition678,
	CID_Condition674,
	CID_Condition119,
	CID_Condition677,
	CID_Condition679,
	CID_Condition675,
	CID_Condition195,
	CID_Condition196,
	CID_Condition560,
	CID_Condition404,
	CID_Condition626,
	CID_Condition617,
	CID_Condition542,
	CID_Condition545,
	CID_Condition546,
	CID_Condition326,
	CID_Condition150,
	CID_Condition151,
	CID_Condition149,
	CID_Condition152,
	CID_Condition148,
	CID_Condition263,
	CID_Condition253,
	CID_Condition254,
	CID_Condition255,
	CID_Condition256,
	CID_Condition257,
	CID_Condition258,
	CID_Condition259,
	CID_Condition260,
	CID_Condition261,
	CID_Condition262,
	CID_Condition620,
	CID_Condition621,
	CID_Condition252,
	CID_Condition574,
	CID_Condition662,
	CID_Condition663,
	CID_Condition661,
	CID_Condition660,
	CID_Condition110,
	CID_Condition658,
	CID_Condition388,
	CID_Condition389,
	CID_Condition160,
	CID_Condition159,
	CID_Condition638,
	CID_Condition640,
	CID_Condition522,
	CID_Condition528,
	CID_Condition35,
	CID_Condition526,
	CID_Condition111,
	CID_Condition95,
	CID_Condition192,
	CID_Condition193,
	CID_Condition118,
	CID_Condition527,
	CID_Condition186,
	CID_Condition184,
	CID_Condition586,
	CID_Condition185,
	CID_Condition237,
	CID_Condition120,
	CID_Condition681,
	CID_Condition682,
	CID_Condition94,
	CID_Condition317,
	CID_Condition318,
	CID_Condition315,
	CID_Condition316,
	CID_Condition112,
	CID_Condition266,
	CID_Condition269,
	CID_Condition264,
	CID_Condition267,
	CID_Condition265,
	CID_Condition268,
	CID_Condition168,
	CID_Condition108,
	CID_Condition107,
	CID_Condition167,
	CID_Condition163,
	CID_Condition128,
	CID_Condition533,
	CID_Condition580,
	CID_Condition579,
	CID_Condition147,
	CID_Condition553,
	CID_Condition10,
	CID_Condition97,
	CID_Condition482,
	CID_Condition483,
	CID_Condition484,
	CID_Condition645,
	CID_Condition479,
	CID_Condition643,
	CID_Condition480,
	CID_Condition608,
	CID_Condition607,
	CID_Condition644,
	CID_Condition481,
	CID_Condition642,
	CID_Condition478,
	CID_Condition9,
	CID_Condition98,
	CID_Condition690,
	CID_Condition489,
	CID_Condition490,
	CID_Condition491,
	CID_Condition689,
	CID_Condition652,
	CID_Condition486,
	CID_Condition691,
	CID_Condition650,
	CID_Condition487,
	CID_Condition651,
	CID_Condition488,
	CID_Condition649,
	CID_Condition485,
	CID_Condition136,
	CID_Condition137,
	CID_Condition87,
	CID_Condition82,
	CID_Condition126,
	CID_Condition124,
	CID_Condition125,
	CID_Condition590,
	CID_Condition179,
	CID_Condition188,
	CID_Condition162,
	CID_Condition236,
	CID_Condition143,
	CID_Condition671,
	CID_Condition71,
	CID_Condition154,
	CID_Condition157,
	CID_Condition212,
	CID_Condition156,
	CID_Condition155,
	CID_Condition158,
	CID_Condition398,
	CID_Condition399,
	CID_Condition670,
	CID_Condition669,
	CID_Condition89,
	CID_Condition206,
	CID_Condition207,
	CID_Condition209,
	CID_Condition203,
	CID_Condition210,
	CID_Condition204,
	CID_Condition211,
	CID_Condition205,
	CID_Condition208,
	CID_Condition573,
	CID_Condition75,
	CID_Condition687,
	CID_Condition439,
	CID_Condition550,
	CID_Condition547,
	CID_Condition530,
	CID_Condition531,
	CID_Condition588,
	CID_Condition516,
	CID_Condition589,
	CID_Condition238,
	CID_Condition577,
	CID_Condition578,
	CID_Condition551,
	CID_Condition557,
	CID_Condition683,
	CID_Condition684,
	CID_Condition515,
	CID_Condition694,
	CID_Condition688,
	CID_Condition685,
	CID_Condition686,
	CID_Condition693,
	CID_Condition520,
	CID_Condition556,
	CID_Condition558,
	CID_Condition555,
	CID_Condition576,
	CID_Condition575,
	CID_Condition190
} ConditionIDEnum;

#define Action_gm_GoToState_WB_Used 
#define Action_gm_GoToState_WB_Used 
#define Action_gm_SetAdjuster_WB_Used 
#define Action_DrawText_WB_Used 
#define Action_ResetTimer_WB_Used 
#define Action_DrawBitmap_WB_Used 
#define Action_SetOsdTimeout_WB_Used 
#define Action_DrawSelectedText_WB_Used 
#define Action_EraseControl_WB_Used 
#define Action_LoadColorsInvisibleState_WB_Used 
#define Action_DrawLongValue_WB_Used 
#define Action_gm_IncAdjuster_WB_Used 
#define Action_UpdateLongValue_WB_Used 
#define Action_gm_SetAdjuster_WB_Used 
#define Action_gm_DecAdjuster_WB_Used 
#define Action_UpdateSelectedLongValue_WB_Used 
#define Action_UpdateSelectedSlider_WB_Used 
#define Action_PIPSendMessage_WB_Used 
#define Action_SaveModeIndependentSettings_WB_Used 
#define Action_SavePortSchemeDependentSettings_WB_Used 
#define Action_gm_SetAdjuster_WB_Used 
#define Action_gm_SetAdjuster_WB_Used 
#define Action_DrawSlider_WB_Used 
#define Action_DrawSelectedLongValue_WB_Used 
#define Action_DrawSelectedSlider_WB_Used 
#define Action_AllocateTile_WB_Used 
#define Action_DeallocateTile_WB_Used 
#define Action_DebugOSD_WB_Used 
#define Action_gm_DecState_WB_Used 
#define Action_gm_IncState_WB_Used 
#define Action_HideOsd_WB_Used 
#define Action_DrawOption1DStaticTextButton_WB_Used 
#define Action_SetOSDMenuState_WB_Used 
#define Action_DrawOption2DStaticTextButton_WB_Used 
#define Action_DrawSelectedBitmap_WB_Used 
#define Action_DrawOption1DStaticText_WB_Used 
#define Action_DrawOption2DStaticText_WB_Used 
#define Action_DrawOption3DStaticTextButton_WB_Used 
#define Action_DrawOption4DStaticTextButton_WB_Used 
#define Action_DrawRectangle_WB_Used 
#define Action_ShowOsd_WB_Used 
#define Action_SaveGrModeDependentSettings_WB_Used 
#define Action_DrawSelectedOption2DStaticTextButton_WB_Used 
#define Action_SetActiveDialog_WB_Used 
#define Action_DrawDTimingInfo_WB_Used 
#define Action_DrawSelectedOption1DStaticTextButton_WB_Used 
#define Action_LoadColorsDialog_WB_Used 
#define Action_DrawOption1D2StaticTextButton_WB_Used 
#define Action_DrawDisabledText_WB_Used 
#define Action_DrawSelectedOption1D2StaticTextButton_WB_Used 
#define Action_DrawSelectedOption2D2StaticTextButton_WB_Used 
#define Action_MultiPipTurnOff_WB_Used 
#define Action_DrawOption2D2StaticTextButton_WB_Used 
#define Action_DrawOption3DStaticText_WB_Used 
#define Action_ClrBitFlag_WB_Used 
#define Action_DrawSelectedOption3DStaticTextButton_WB_Used 
#define Action_DrawSelectedOption4DStaticTextButton_WB_Used 
#define Action_RestoreXYOffsetAfterPIPIconDraw_WB_Used 
#define Action_DrawOption5DStaticTextButton_WB_Used 
#define Action_RestorePipOnscreenState_WB_Used 
#define Action_SaveFactorySettingsInNVR_WB_Used 
#define Action_TurnLcdOff_WB_Used 
#define Action_DrawOption4DStaticText_WB_Used 
#define Action_DrawSelectedOption5DStaticTextButton_WB_Used 
#define Action_DrawOption7DStaticTextButton_WB_Used 
#define Action_EnableTile_WB_Used 
#define Action_DrawOption1D2StaticText_WB_Used 
#define Action_TurnLcdOn_WB_Used 
#define Action_GetChipID_WB_Used 
#define Action_SetDynamicStringPtr_WB_Used 
#define Action_SetIspActionConfirm_WB_Used 
#define Action_SetOsdRequestForPowerUp_WB_Used 
#define Action_AdjustOsdBlend_WB_Used 
#define Action_OSD_AdjustBrigntnessContrast_WB_Used 
#define Action_SavePipOnScreenState_WB_Used 
#define Action_SetWbMainChannel_WB_Used 
#define Action_TurnBacklightOn_WB_Used 
#define Action_DrawOption6DStaticTextButton_WB_Used 
#define Action_DrawOption8DStaticTextButton_WB_Used 
#define Action_DrawSelectedOption1D4StaticTextButton_WB_Used 
#define Action_DrawSelectedOption2D4StaticTextButton_WB_Used 
#define Action_DrawSelectedOption3D4StaticTextButton_WB_Used 
#define Action_DrawSelectedOption4D4StaticTextButton_WB_Used 
#define Action_DrawSelectedOption6DStaticTextButton_WB_Used 
#define Action_OSDSendMessage_WB_Used 
#define Action_RestoreRotatedXOffsetAfterIconDraw_WB_Used 
#define Action_AdjustAudioMute_WB_Used 
#define Action_DrawOption1D4StaticTextButton_WB_Used 
#define Action_DrawOption2D4StaticTextButton_WB_Used 
#define Action_DrawOption3D4StaticTextButton_WB_Used 
#define Action_DrawOption4D4StaticTextButton_WB_Used 
#define Action_Osd_Hide_WB_Used 
#define Action_PostEvent_WB_Used 
#define Action_ResetBurninTime_WB_Used 
#define Action_AutoAdjust_WB_Used 
#define Action_DrawDynamicText1_WB_Used 
#define Action_DrawSelectedOption8DStaticTextButton_WB_Used 
#define Action_FactoryReset_WB_Used 
#define Action_SwapMainPip_WB_Used 
#define Action_SysteHardReset_WB_Used 
#define Action_DrawSelectedOption7DStaticTextButton_WB_Used 
#define Action_LockOSD_WB_Used 
#define Action_SetForceBackground_WB_Used 
#define Action_ADCCalibration_WB_Used 
#define Action_DrawDisabledBitmap_WB_Used 
#define Action_EraseBitmap_WB_Used 
#define Action_gm_SaveState_WB_Used 
#define Action_gm_SetAdjuster_WB_Used 
#define Action_SetOsdReadyForPowerDown_WB_Used 
#define Action_StartFlyingWindow_WB_Used 
#define Action_StopFlyingWindow_WB_Used 
#define Action_ToggleInfoDisplay_WB_Used 
#define Action_ToggleMute_WB_Used 
#define Action_UpdateSourceLeds_WB_Used 
#define Action_gm_SetOsdRotation_WB_Used 
#define Action_AdjustBlueGain_WB_Used 
#define Action_AdjustBlueOff_WB_Used 
#define Action_AdjustGreenGain_WB_Used 
#define Action_AdjustGreenOff_WB_Used 
#define Action_AdjustRedGain_WB_Used 
#define Action_AdjustRedOff_WB_Used 
#define Action_AdjustUartBaudRate_WB_Used 
#define Action_ClrForceBackground_WB_Used 
#define Action_DrawOption1D3StaticTextButton_WB_Used 
#define Action_DrawOption2D2StaticText_WB_Used 
#define Action_DrawOption2D3StaticTextButton_WB_Used 
#define Action_DrawOption3D3StaticTextButton_WB_Used 
#define Action_DrawOption5DStaticText_WB_Used 
#define Action_DrawOption6DStaticText_WB_Used 
#define Action_DrawOption8DStaticText_WB_Used 
#define Action_EDID_WP_DISABLE_WB_Used 
#define Action_EDID_WP_ENABLE_WB_Used 
#define Action_FactoryGetADCValues_WB_Used 
#define Action_IspThruDisplay_WB_Used 
#define Action_PipBorderControl_WB_Used 
#define Action_RequestSoftPowerOn_WB_Used 
#define Action_RestoreLedState_WB_Used 
#define Action_gm_RestoreState_WB_Used 
#define Action_SaveModeDep_gm57xx_WB_Used 
#define Action_SetPIPIconXYOffset_WB_Used 
#define Action_SetSharpnessNoiseCoringToTNR_WB_Used 
#define Action_ToggleFreezeVar_WB_Used 
#define Action_TurnSoundOff_WB_Used 
#define Action_TurnSoundOn_WB_Used 
#define Action_UpdateSlider_WB_Used 
#define Action_AdjustOsdHPosition_WB_Used 
#define Action_AdjustOsdRotation_WB_Used 
#define Action_AdjustPipMode_WB_Used 
#define Action_AutoConfig_WB_Used 
#define Action_CancelNoSignalMsg_WB_Used 
#define Action_DrawOption1DStaticTextExt_WB_Used 
#define Action_DrawSelectedOption1D3StaticTextButton_WB_Used 
#define Action_DrawSelectedOption2D3StaticTextButton_WB_Used 
#define Action_DrawSelectedOption3D3StaticTextButton_WB_Used 
#define Action_InitPIPIconPosition_WB_Used 
#define Action_InitPanelSpectrum_WB_Used 
#define Action_OSDHardLock_WB_Used 
#define Action_OSDHardUnLock_WB_Used 
#define Action_OsdBlend_WB_Used 
#define Action_OsdFactoryMenuInfo_WB_Used 
#define Action_RequestSoftPowerOff_WB_Used 
#define Action_RequestUpdateCableStatus_WB_Used 
#define Action_ResetAudioSetting_WB_Used 
#define Action_ResetDisplaySettings_WB_Used 
#define Action_SavePipPortSchemeDependent_WB_Used 
#define Action_SetBackGroundColor_WB_Used 
#define Action_SetIspAutoDetMode_WB_Used 
#define Action_SetMessageHVPos_WB_Used 
#define Action_SetRotatedIconXOffset_WB_Used 
#define Action_StartNoCablePowerDownCounter_WB_Used 
#define Action_StartNoCableSleep_WB_Used 
#define Action_StopNoCablePowerDownCounter_WB_Used 
#define Action_StoreACC2Mask_WB_Used 
#define Action_UnLockOSD_WB_Used 
#define Action_UpdateColorTemp_WB_Used 

extern gmt_OSD_ACTION_ENTRY ROM gmv_ActionSet[];

extern gmt_OSD_CONDITION_FUNC ROM gmv_ConditionSet[];

// Conditions definition

extern BYTE Condition70();
extern BYTE Condition93();
extern BYTE Condition27();
extern BYTE Condition199();
extern BYTE Condition65();
extern BYTE Condition90();
extern BYTE Condition67();
extern BYTE Condition668();
extern BYTE Condition28();
extern BYTE Condition36();
extern BYTE Condition22();
extern BYTE Condition214();
extern BYTE Condition384();
extern BYTE Condition442();
extern BYTE Condition74();
extern BYTE Condition412();
extern BYTE Condition639();
extern BYTE Condition227();
extern BYTE Condition52();
extern BYTE Condition144();
extern BYTE Condition135();
extern BYTE Condition105();
extern BYTE Condition228();
extern BYTE Condition225();
extern BYTE Condition224();
extern BYTE Condition226();
extern BYTE Condition223();
extern BYTE Condition240();
extern BYTE Condition0();
extern BYTE Condition673();
extern BYTE Condition631();
extern BYTE Condition17();
extern BYTE Condition359();
extern BYTE Condition360();
extern BYTE Condition357();
extern BYTE Condition358();
extern BYTE Condition518();
extern BYTE Condition519();
extern BYTE Condition440();
extern BYTE Condition197();
extern BYTE Condition198();
extern BYTE Condition66();
extern BYTE Condition115();
extern BYTE Condition277();
extern BYTE Condition219();
extern BYTE Condition220();
extern BYTE Condition217();
extern BYTE Condition239();
extern BYTE Condition564();
extern BYTE Condition102();
extern BYTE Condition692();
extern BYTE Condition114();
extern BYTE Condition627();
extern BYTE Condition92();
extern BYTE Condition172();
extern BYTE Condition181();
extern BYTE Condition243();
extern BYTE Condition244();
extern BYTE Condition64();
extern BYTE Condition443();
extern BYTE Condition628();
extern BYTE Condition517();
extern BYTE Condition218();
extern BYTE Condition91();
extern BYTE Condition630();
extern BYTE Condition536();
extern BYTE Condition68();
extern BYTE Condition69();
extern BYTE Condition213();
extern BYTE Condition141();
extern BYTE Condition153();
extern BYTE Condition534();
extern BYTE Condition535();
extern BYTE Condition247();
extern BYTE Condition245();
extern BYTE Condition246();
extern BYTE Condition441();
extern BYTE Condition273();
extern BYTE Condition276();
extern BYTE Condition274();
extern BYTE Condition275();
extern BYTE Condition272();
extern BYTE Condition448();
extern BYTE Condition445();
extern BYTE Condition446();
extern BYTE Condition447();
extern BYTE Condition444();
extern BYTE Condition474();
extern BYTE Condition641();
extern BYTE Condition229();
extern BYTE Condition323();
extern BYTE Condition321();
extern BYTE Condition322();
extern BYTE Condition320();
extern BYTE Condition251();
extern BYTE Condition594();
extern BYTE Condition215();
extern BYTE Condition200();
extern BYTE Condition541();
extern BYTE Condition59();
extern BYTE Condition189();
extern BYTE Condition554();
extern BYTE Condition459();
extern BYTE Condition410();
extern BYTE Condition411();
extern BYTE Condition615();
extern BYTE Condition288();
extern BYTE Condition271();
extern BYTE Condition529();
extern BYTE Condition146();
extern BYTE Condition438();
extern BYTE Condition437();
extern BYTE Condition629();
extern BYTE Condition278();
extern BYTE Condition475();
extern BYTE Condition133();
extern BYTE Condition592();
extern BYTE Condition593();
extern BYTE Condition595();
extern BYTE Condition596();
extern BYTE Condition597();
extern BYTE Condition591();
extern BYTE Condition104();
extern BYTE Condition532();
extern BYTE Condition242();
extern BYTE Condition279();
extern BYTE Condition624();
extern BYTE Condition241();
extern BYTE Condition313();
extern BYTE Condition328();
extern BYTE Condition140();
extern BYTE Condition538();
extern BYTE Condition604();
extern BYTE Condition605();
extern BYTE Condition606();
extern BYTE Condition566();
extern BYTE Condition603();
extern BYTE Condition46();
extern BYTE Condition63();
extern BYTE Condition540();
extern BYTE Condition539();
extern BYTE Condition461();
extern BYTE Condition324();
extern BYTE Condition325();
extern BYTE Condition327();
extern BYTE Condition400();
extern BYTE Condition401();
extern BYTE Condition402();
extern BYTE Condition403();
extern BYTE Condition409();
extern BYTE Condition406();
extern BYTE Condition408();
extern BYTE Condition405();
extern BYTE Condition407();
extern BYTE Condition45();
extern BYTE Condition614();
extern BYTE Condition613();
extern BYTE Condition612();
extern BYTE Condition611();
extern BYTE Condition469();
extern BYTE Condition470();
extern BYTE Condition467();
extern BYTE Condition468();
extern BYTE Condition471();
extern BYTE Condition280();
extern BYTE Condition282();
extern BYTE Condition283();
extern BYTE Condition281();
extern BYTE Condition563();
extern BYTE Condition424();
extern BYTE Condition427();
extern BYTE Condition425();
extern BYTE Condition428();
extern BYTE Condition429();
extern BYTE Condition426();
extern BYTE Condition284();
extern BYTE Condition286();
extern BYTE Condition287();
extern BYTE Condition285();
extern BYTE Condition216();
extern BYTE Condition306();
extern BYTE Condition312();
extern BYTE Condition309();
extern BYTE Condition307();
extern BYTE Condition310();
extern BYTE Condition311();
extern BYTE Condition308();
extern BYTE Condition361();
extern BYTE Condition618();
extern BYTE Condition62();
extern BYTE Condition61();
extern BYTE Condition619();
extern BYTE Condition623();
extern BYTE Condition57();
extern BYTE Condition56();
extern BYTE Condition201();
extern BYTE Condition134();
extern BYTE Condition314();
extern BYTE Condition537();
extern BYTE Condition430();
extern BYTE Condition431();
extern BYTE Condition432();
extern BYTE Condition47();
extern BYTE Condition433();
extern BYTE Condition622();
extern BYTE Condition543();
extern BYTE Condition121();
extern BYTE Condition60();
extern BYTE Condition180();
extern BYTE Condition72();
extern BYTE Condition73();
extern BYTE Condition561();
extern BYTE Condition50();
extern BYTE Condition51();
extern BYTE Condition48();
extern BYTE Condition49();
extern BYTE Condition568();
extern BYTE Condition565();
extern BYTE Condition567();
extern BYTE Condition344();
extern BYTE Condition44();
extern BYTE Condition319();
extern BYTE Condition549();
extern BYTE Condition548();
extern BYTE Condition454();
extern BYTE Condition453();
extern BYTE Condition452();
extern BYTE Condition455();
extern BYTE Condition456();
extern BYTE Condition329();
extern BYTE Condition175();
extern BYTE Condition177();
extern BYTE Condition174();
extern BYTE Condition176();
extern BYTE Condition1();
extern BYTE Condition5();
extern BYTE Condition2();
extern BYTE Condition6();
extern BYTE Condition29();
extern BYTE Condition33();
extern BYTE Condition34();
extern BYTE Condition31();
extern BYTE Condition30();
extern BYTE Condition32();
extern BYTE Condition43();
extern BYTE Condition138();
extern BYTE Condition55();
extern BYTE Condition103();
extern BYTE Condition413();
extern BYTE Condition625();
extern BYTE Condition616();
extern BYTE Condition435();
extern BYTE Condition436();
extern BYTE Condition632();
extern BYTE Condition636();
extern BYTE Condition634();
extern BYTE Condition633();
extern BYTE Condition635();
extern BYTE Condition99();
extern BYTE Condition100();
extern BYTE Condition249();
extern BYTE Condition248();
extern BYTE Condition472();
extern BYTE Condition387();
extern BYTE Condition637();
extern BYTE Condition289();
extern BYTE Condition270();
extern BYTE Condition544();
extern BYTE Condition127();
extern BYTE Condition145();
extern BYTE Condition170();
extern BYTE Condition53();
extern BYTE Condition54();
extern BYTE Condition178();
extern BYTE Condition58();
extern BYTE Condition476();
extern BYTE Condition477();
extern BYTE Condition513();
extern BYTE Condition514();
extern BYTE Condition132();
extern BYTE Condition562();
extern BYTE Condition113();
extern BYTE Condition598();
extern BYTE Condition434();
extern BYTE Condition109();
extern BYTE Condition14();
extern BYTE Condition16();
extern BYTE Condition101();
extern BYTE Condition173();
extern BYTE Condition129();
extern BYTE Condition130();
extern BYTE Condition131();
extern BYTE Condition142();
extern BYTE Condition512();
extern BYTE Condition657();
extern BYTE Condition656();
extern BYTE Condition569();
extern BYTE Condition570();
extern BYTE Condition571();
extern BYTE Condition250();
extern BYTE Condition494();
extern BYTE Condition492();
extern BYTE Condition495();
extern BYTE Condition493();
extern BYTE Condition552();
extern BYTE Condition171();
extern BYTE Condition191();
extern BYTE Condition572();
extern BYTE Condition509();
extern BYTE Condition511();
extern BYTE Condition499();
extern BYTE Condition501();
extern BYTE Condition503();
extern BYTE Condition497();
extern BYTE Condition672();
extern BYTE Condition23();
extern BYTE Condition96();
extern BYTE Condition395();
extern BYTE Condition394();
extern BYTE Condition508();
extern BYTE Condition396();
extern BYTE Condition510();
extern BYTE Condition397();
extern BYTE Condition393();
extern BYTE Condition498();
extern BYTE Condition391();
extern BYTE Condition500();
extern BYTE Condition392();
extern BYTE Condition502();
extern BYTE Condition390();
extern BYTE Condition496();
extern BYTE Condition473();
extern BYTE Condition506();
extern BYTE Condition507();
extern BYTE Condition504();
extern BYTE Condition505();
extern BYTE Condition194();
extern BYTE Condition183();
extern BYTE Condition182();
extern BYTE Condition161();
extern BYTE Condition582();
extern BYTE Condition581();
extern BYTE Condition583();
extern BYTE Condition88();
extern BYTE Condition600();
extern BYTE Condition601();
extern BYTE Condition602();
extern BYTE Condition139();
extern BYTE Condition165();
extern BYTE Condition169();
extern BYTE Condition466();
extern BYTE Condition381();
extern BYTE Condition374();
extern BYTE Condition525();
extern BYTE Condition524();
extern BYTE Condition232();
extern BYTE Condition233();
extern BYTE Condition230();
extern BYTE Condition231();
extern BYTE Condition25();
extern BYTE Condition26();
extern BYTE Condition24();
extern BYTE Condition523();
extern BYTE Condition559();
extern BYTE Condition354();
extern BYTE Condition356();
extern BYTE Condition352();
extern BYTE Condition355();
extern BYTE Condition351();
extern BYTE Condition353();
extern BYTE Condition350();
extern BYTE Condition349();
extern BYTE Condition659();
extern BYTE Condition587();
extern BYTE Condition521();
extern BYTE Condition234();
extern BYTE Condition235();
extern BYTE Condition347();
extern BYTE Condition348();
extern BYTE Condition345();
extern BYTE Condition346();
extern BYTE Condition164();
extern BYTE Condition106();
extern BYTE Condition166();
extern BYTE Condition464();
extern BYTE Condition465();
extern BYTE Condition458();
extern BYTE Condition460();
extern BYTE Condition457();
extern BYTE Condition451();
extern BYTE Condition449();
extern BYTE Condition450();
extern BYTE Condition462();
extern BYTE Condition463();
extern BYTE Condition290();
extern BYTE Condition292();
extern BYTE Condition293();
extern BYTE Condition291();
extern BYTE Condition414();
extern BYTE Condition415();
extern BYTE Condition416();
extern BYTE Condition421();
extern BYTE Condition420();
extern BYTE Condition302();
extern BYTE Condition304();
extern BYTE Condition305();
extern BYTE Condition303();
extern BYTE Condition666();
extern BYTE Condition665();
extern BYTE Condition664();
extern BYTE Condition667();
extern BYTE Condition336();
extern BYTE Condition331();
extern BYTE Condition335();
extern BYTE Condition334();
extern BYTE Condition332();
extern BYTE Condition333();
extern BYTE Condition330();
extern BYTE Condition382();
extern BYTE Condition383();
extern BYTE Condition380();
extern BYTE Condition378();
extern BYTE Condition379();
extern BYTE Condition377();
extern BYTE Condition364();
extern BYTE Condition365();
extern BYTE Condition362();
extern BYTE Condition363();
extern BYTE Condition294();
extern BYTE Condition296();
extern BYTE Condition297();
extern BYTE Condition295();
extern BYTE Condition417();
extern BYTE Condition418();
extern BYTE Condition419();
extern BYTE Condition423();
extern BYTE Condition422();
extern BYTE Condition298();
extern BYTE Condition300();
extern BYTE Condition301();
extern BYTE Condition299();
extern BYTE Condition342();
extern BYTE Condition338();
extern BYTE Condition343();
extern BYTE Condition341();
extern BYTE Condition339();
extern BYTE Condition340();
extern BYTE Condition337();
extern BYTE Condition375();
extern BYTE Condition376();
extern BYTE Condition373();
extern BYTE Condition371();
extern BYTE Condition372();
extern BYTE Condition370();
extern BYTE Condition368();
extern BYTE Condition369();
extern BYTE Condition366();
extern BYTE Condition367();
extern BYTE Condition385();
extern BYTE Condition386();
extern BYTE Condition646();
extern BYTE Condition222();
extern BYTE Condition647();
extern BYTE Condition648();
extern BYTE Condition221();
extern BYTE Condition610();
extern BYTE Condition609();
extern BYTE Condition599();
extern BYTE Condition653();
extern BYTE Condition654();
extern BYTE Condition655();
extern BYTE Condition202();
extern BYTE Condition4();
extern BYTE Condition8();
extern BYTE Condition76();
extern BYTE Condition79();
extern BYTE Condition78();
extern BYTE Condition81();
extern BYTE Condition20();
extern BYTE Condition13();
extern BYTE Condition18();
extern BYTE Condition3();
extern BYTE Condition7();
extern BYTE Condition83();
extern BYTE Condition85();
extern BYTE Condition19();
extern BYTE Condition11();
extern BYTE Condition12();
extern BYTE Condition84();
extern BYTE Condition86();
extern BYTE Condition21();
extern BYTE Condition15();
extern BYTE Condition77();
extern BYTE Condition80();
extern BYTE Condition37();
extern BYTE Condition41();
extern BYTE Condition42();
extern BYTE Condition39();
extern BYTE Condition38();
extern BYTE Condition40();
extern BYTE Condition116();
extern BYTE Condition117();
extern BYTE Condition122();
extern BYTE Condition123();
extern BYTE Condition187();
extern BYTE Condition585();
extern BYTE Condition584();
extern BYTE Condition680();
extern BYTE Condition676();
extern BYTE Condition678();
extern BYTE Condition674();
extern BYTE Condition119();
extern BYTE Condition677();
extern BYTE Condition679();
extern BYTE Condition675();
extern BYTE Condition195();
extern BYTE Condition196();
extern BYTE Condition560();
extern BYTE Condition404();
extern BYTE Condition626();
extern BYTE Condition617();
extern BYTE Condition542();
extern BYTE Condition545();
extern BYTE Condition546();
extern BYTE Condition326();
extern BYTE Condition150();
extern BYTE Condition151();
extern BYTE Condition149();
extern BYTE Condition152();
extern BYTE Condition148();
extern BYTE Condition263();
extern BYTE Condition253();
extern BYTE Condition254();
extern BYTE Condition255();
extern BYTE Condition256();
extern BYTE Condition257();
extern BYTE Condition258();
extern BYTE Condition259();
extern BYTE Condition260();
extern BYTE Condition261();
extern BYTE Condition262();
extern BYTE Condition620();
extern BYTE Condition621();
extern BYTE Condition252();
extern BYTE Condition574();
extern BYTE Condition662();
extern BYTE Condition663();
extern BYTE Condition661();
extern BYTE Condition660();
extern BYTE Condition110();
extern BYTE Condition658();
extern BYTE Condition388();
extern BYTE Condition389();
extern BYTE Condition160();
extern BYTE Condition159();
extern BYTE Condition638();
extern BYTE Condition640();
extern BYTE Condition522();
extern BYTE Condition528();
extern BYTE Condition35();
extern BYTE Condition526();
extern BYTE Condition111();
extern BYTE Condition95();
extern BYTE Condition192();
extern BYTE Condition193();
extern BYTE Condition118();
extern BYTE Condition527();
extern BYTE Condition186();
extern BYTE Condition184();
extern BYTE Condition586();
extern BYTE Condition185();
extern BYTE Condition237();
extern BYTE Condition120();
extern BYTE Condition681();
extern BYTE Condition682();
extern BYTE Condition94();
extern BYTE Condition317();
extern BYTE Condition318();
extern BYTE Condition315();
extern BYTE Condition316();
extern BYTE Condition112();
extern BYTE Condition266();
extern BYTE Condition269();
extern BYTE Condition264();
extern BYTE Condition267();
extern BYTE Condition265();
extern BYTE Condition268();
extern BYTE Condition168();
extern BYTE Condition108();
extern BYTE Condition107();
extern BYTE Condition167();
extern BYTE Condition163();
extern BYTE Condition128();
extern BYTE Condition533();
extern BYTE Condition580();
extern BYTE Condition579();
extern BYTE Condition147();
extern BYTE Condition553();
extern BYTE Condition10();
extern BYTE Condition97();
extern BYTE Condition482();
extern BYTE Condition483();
extern BYTE Condition484();
extern BYTE Condition645();
extern BYTE Condition479();
extern BYTE Condition643();
extern BYTE Condition480();
extern BYTE Condition608();
extern BYTE Condition607();
extern BYTE Condition644();
extern BYTE Condition481();
extern BYTE Condition642();
extern BYTE Condition478();
extern BYTE Condition9();
extern BYTE Condition98();
extern BYTE Condition690();
extern BYTE Condition489();
extern BYTE Condition490();
extern BYTE Condition491();
extern BYTE Condition689();
extern BYTE Condition652();
extern BYTE Condition486();
extern BYTE Condition691();
extern BYTE Condition650();
extern BYTE Condition487();
extern BYTE Condition651();
extern BYTE Condition488();
extern BYTE Condition649();
extern BYTE Condition485();
extern BYTE Condition136();
extern BYTE Condition137();
extern BYTE Condition87();
extern BYTE Condition82();
extern BYTE Condition126();
extern BYTE Condition124();
extern BYTE Condition125();
extern BYTE Condition590();
extern BYTE Condition179();
extern BYTE Condition188();
extern BYTE Condition162();
extern BYTE Condition236();
extern BYTE Condition143();
extern BYTE Condition671();
extern BYTE Condition71();
extern BYTE Condition154();
extern BYTE Condition157();
extern BYTE Condition212();
extern BYTE Condition156();
extern BYTE Condition155();
extern BYTE Condition158();
extern BYTE Condition398();
extern BYTE Condition399();
extern BYTE Condition670();
extern BYTE Condition669();
extern BYTE Condition89();
extern BYTE Condition206();
extern BYTE Condition207();
extern BYTE Condition209();
extern BYTE Condition203();
extern BYTE Condition210();
extern BYTE Condition204();
extern BYTE Condition211();
extern BYTE Condition205();
extern BYTE Condition208();
extern BYTE Condition573();
extern BYTE Condition75();
extern BYTE Condition687();
extern BYTE Condition439();
extern BYTE Condition550();
extern BYTE Condition547();
extern BYTE Condition530();
extern BYTE Condition531();
extern BYTE Condition588();
extern BYTE Condition516();
extern BYTE Condition589();
extern BYTE Condition238();
extern BYTE Condition577();
extern BYTE Condition578();
extern BYTE Condition551();
extern BYTE Condition557();
extern BYTE Condition683();
extern BYTE Condition684();
extern BYTE Condition515();
extern BYTE Condition694();
extern BYTE Condition688();
extern BYTE Condition685();
extern BYTE Condition686();
extern BYTE Condition693();
extern BYTE Condition520();
extern BYTE Condition556();
extern BYTE Condition558();
extern BYTE Condition555();
extern BYTE Condition576();
extern BYTE Condition575();
extern BYTE Condition190();


#endif  // ifndef OSD_ACT_H_DEFINED
