////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#ifndef OSD_GLPH_H_DEFINED
#define OSD_GLPH_H_DEFINED

// Glyph Table enum definition
typedef enum 
{
	GID_GlyphTable0,
	GID_GlyphTable1,
	GID_GlyphTable2,
	GID_GlyphTable3,
	GID_GlyphTable4,
	GID_GlyphTable5,
	GID_GlyphTable6,
	GID_GlyphTable7,
	GID_GlyphTable8,
	GID_GlyphTable9,
	GID_GlyphTable10,
	GID_GlyphTable11,
	GID_GlyphTable12,
	NUMBER_OF_GLYPH_TABLES
} GlyphTblSetEnum;

extern BYTE ROM gmc_NumberOfGlyphTabels;
#define RENDER_ENABLED		
extern BYTE ROM * ROM gmv_GlyphTblSet[];


#endif  // ifndef OSD_GLPH_H_DEFINED
