////////////////////////////////////////////////////////////////////////////////
//    Genesis Microchip, Inc.
// This file was generated by Genesis Workbench. PLEASE DO NOT EDIT MANUALLY
////////////////////////////////////////////////////////////////////////////////

#include "System\all.h"

ST_TRANSLATION_TABLE_ENTRY ROM TrTable_Port_VGABtn[36] =
{
	{
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_DOWN_RELEASE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_MENU_RELEASE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_ENTER_RELEASE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_SOURCE_RELEASE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		{ Key_None, 0x00 },
		OEK_KEY_LOGICAL_UP_RELEASE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_LEFT, 0x00 },
		OEK_KEY_LOGICAL_LEFT,
		15,
		10,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_RIGHT, 0x00 },
		OEK_KEY_LOGICAL_RIGHT,
		15,
		10,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x01 },
		OEK_KEY_LOGICAL_DOWN_AR1,
		15,
		1,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DOWN, 0x00 },
		OEK_KEY_LOGICAL_DOWN,
		15,
		10,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x0a },
		OEK_KEY_LOGICAL_MENU_DELAY,
		15,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MENU, 0x00 },
		OEK_KEY_LOGICAL_MENU,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_OK, 0x00 },
		OEK_KEY_LOGICAL_ENTER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP, 0x00 },
		OEK_KEY_LOGICAL_PIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SWAP, 0x00 },
		OEK_KEY_LOGICAL_SWAP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_SPLIT, 0x00 },
		OEK_KEY_LOGICAL_SPLIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_POWER, 0x00 },
		OEK_KEY_LOGICAL_POWER,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_YPbPr, 0x00 },
		OEK_KEY_LOGICAL_YPbPr,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_AV, 0x00 },
		OEK_KEY_LOGICAL_AV,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_AV2, 0x00 },
		OEK_KEY_LOGICAL_AV2,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_SOURCE, 0x00 },
		OEK_KEY_LOGICAL_PIP_SOURCE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_FREEZE, 0x00 },
		OEK_KEY_LOGICAL_FREEZE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PresetMode, 0x00 },
		OEK_KEY_LOGICAL_PreMode,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_INFO, 0x00 },
		OEK_KEY_LOGICAL_DISPLAY,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_MUTE, 0x00 },
		OEK_KEY_LOGICAL_MUTE,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_PIP_ASPECTRATIO, 0x00 },
		OEK_KEY_LOGICAL_ASPECTRATIOPIP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_DOWN, 0x00 },
		OEK_KEY_LOGICAL_VOL_DOWN,
		15,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VOLUME_UP, 0x00 },
		OEK_KEY_LOGICAL_VOL_UP,
		15,
		5,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_UP, 0x00 },
		OEK_KEY_LOGICAL_UP,
		15,
		10,
		0x01,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EXIT, 0x00 },
		OEK_KEY_LOGICAL_EXIT,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_AUTO, 0x00 },
		OEK_KEY_LOGICAL_AUTO,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DP, 0x00 },
		OEK_KEY_LOGICAL_DP,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_DVI, 0x00 },
		OEK_KEY_LOGICAL_DVI,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_HDMI, 0x00 },
		OEK_KEY_LOGICAL_HDMI,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_VGA, 0x00 },
		OEK_KEY_LOGICAL_VGA,
		0x00,
		0x00,
		0x00,
		TTEF_TableContinues
	},
	{
		{ Key_None, 0x00 },
		{ Key_KEY_PHYSICAL_EIGHT, 0x00 },
		OEK_KEY_LOGICAL_EIGHT,
		0x00,
		0x00,
		0x00,
		TTEF_TableEnds
	}
};

////////////////////////////////////////////////////////////////////////////////
//    Translation tables
////////////////////////////////////////////////////////////////////////////////

ST_TRANSLATION_TABLE_ENTRY ROM * ROM GlobalTranslTableSet[1] =
{
	TrTable_Port_VGABtn
};

BYTE ROM TrtblMaxEntries[1] =
{
	0x24
};

WORD ROM KEYPAD_DEBOUNCE_PERIOD = 20;

BYTE ROM IR_Values[58] =
{
	WBK_EXTRACT_CODE_BYTE(51), Key_KEY_PHYSICAL_AUTO,
	WBK_EXTRACT_CODE_BYTE(66), Key_KEY_PHYSICAL_AV,
	WBK_EXTRACT_CODE_BYTE(67), Key_KEY_PHYSICAL_AV2,
	WBK_EXTRACT_CODE_BYTE(29), Key_KEY_PHYSICAL_DOWN,
	WBK_EXTRACT_CODE_BYTE(64), Key_KEY_PHYSICAL_DP,
	WBK_EXTRACT_CODE_BYTE(62), Key_KEY_PHYSICAL_DVI,
	WBK_EXTRACT_CODE_BYTE(8), Key_KEY_PHYSICAL_EIGHT,
	WBK_EXTRACT_CODE_BYTE(24), Key_KEY_PHYSICAL_EXIT,
	WBK_EXTRACT_CODE_BYTE(20), Key_KEY_PHYSICAL_FREEZE,
	WBK_EXTRACT_CODE_BYTE(63), Key_KEY_PHYSICAL_HDMI,
	WBK_EXTRACT_CODE_BYTE(15), Key_KEY_PHYSICAL_INFO,
	WBK_EXTRACT_CODE_BYTE(25), Key_KEY_PHYSICAL_LEFT,
	WBK_EXTRACT_CODE_BYTE(22), Key_KEY_PHYSICAL_MENU,
	WBK_EXTRACT_CODE_BYTE(13), Key_KEY_PHYSICAL_MUTE,
	WBK_EXTRACT_CODE_BYTE(26), Key_KEY_PHYSICAL_OK,
	WBK_EXTRACT_CODE_BYTE(11), Key_KEY_PHYSICAL_PIP,
	WBK_EXTRACT_CODE_BYTE(58), Key_KEY_PHYSICAL_PIP_ASPECTRATIO,
	WBK_EXTRACT_CODE_BYTE(10), Key_KEY_PHYSICAL_PIP_SOURCE,
	WBK_EXTRACT_CODE_BYTE(12), Key_KEY_PHYSICAL_POWER,
	WBK_EXTRACT_CODE_BYTE(50), Key_KEY_PHYSICAL_PresetMode,
	WBK_EXTRACT_CODE_BYTE(27), Key_KEY_PHYSICAL_RIGHT,
	WBK_EXTRACT_CODE_BYTE(56), Key_KEY_PHYSICAL_SOURCE,
	WBK_EXTRACT_CODE_BYTE(36), Key_KEY_PHYSICAL_SPLIT,
	WBK_EXTRACT_CODE_BYTE(14), Key_KEY_PHYSICAL_SWAP,
	WBK_EXTRACT_CODE_BYTE(23), Key_KEY_PHYSICAL_UP,
	WBK_EXTRACT_CODE_BYTE(61), Key_KEY_PHYSICAL_VGA,
	WBK_EXTRACT_CODE_BYTE(17), Key_KEY_PHYSICAL_VOLUME_DOWN,
	WBK_EXTRACT_CODE_BYTE(16), Key_KEY_PHYSICAL_VOLUME_UP,
	WBK_EXTRACT_CODE_BYTE(65), Key_KEY_PHYSICAL_YPbPr
};

WBK_KEYPAD_DEFINITION ROM Keypad_IR =
{
	0x00,
	IR_Values,
	0x1d,
	GetIRValue,
	InitIRDriver,
	0x01,
	0x00
};

BYTE ROM ADC_2_Values[12] =
{
	WBK_EXTRACT_CODE_BYTE(193), Key_KEY_PHYSICAL_DOWN,
	WBK_EXTRACT_CODE_BYTE(112), Key_KEY_PHYSICAL_LEFT,
	WBK_EXTRACT_CODE_BYTE(211), Key_KEY_PHYSICAL_MENU,
	WBK_EXTRACT_CODE_BYTE(159), Key_KEY_PHYSICAL_OK,
	WBK_EXTRACT_CODE_BYTE(57), Key_KEY_PHYSICAL_RIGHT,
	WBK_EXTRACT_CODE_BYTE(85), Key_KEY_PHYSICAL_UP
};

WBK_KEYPAD_DEFINITION ROM Keypad_ADC_2 =
{
	0x01,
	ADC_2_Values,
	0x06,
	GetADCValue,
	InitADCDriver,
	0x01,
	0x08
};

BYTE ROM ADC_1_Values[10] =
{
	WBK_EXTRACT_CODE_BYTE(59), Key_KEY_PHYSICAL_AUTO,
	WBK_EXTRACT_CODE_BYTE(175), Key_KEY_PHYSICAL_PIP,
	WBK_EXTRACT_CODE_BYTE(29), Key_KEY_PHYSICAL_POWER,
	WBK_EXTRACT_CODE_BYTE(147), Key_KEY_PHYSICAL_SOURCE,
	WBK_EXTRACT_CODE_BYTE(204), Key_KEY_PHYSICAL_SWAP
};

WBK_KEYPAD_DEFINITION ROM Keypad_ADC_1 =
{
	0x00,
	ADC_1_Values,
	0x05,
	GetADCValue,
	InitADCDriver,
	0x01,
	0x08
};

WBK_KEYPAD_DEFINITION ROM* ROM WBK_Keypads[3] =
{
	&Keypad_IR,
	&Keypad_ADC_2,
	&Keypad_ADC_1
};

BYTE ROM WBK_NumberOfKeypads = WB_NUMBER_OF_INPUT_SOURCE;

BYTE ROM WBK_MultiplePortsValuesTranslation[1] =
{
	0
};

BYTE ROM WBK_NumberMultiplePortsValues = WBK_NUMBER_OF_MULTIPLE_PORTS_VALUES;

