/*
	.\Panel\colorMappingGamutMatrix.h
	Color Mapping Gamut Matrix data generated by Display Editor
	Panel CMO_1080P_M236H5_4K2K
	Gamma: 2.2
	Temperature: 6500K
 */

/******************************************************************************
Color Mapping Gamut Matrix for Gamma 2.2,6500K, 10 bits
Provided by Display Editor
******************************************************************************/

WORD ROM COLOR_MAPPING_GAMUT_MATRIX_AdobeRGB98_9300K_M236H5_4K2K[9]=
{
   // R, G, B
	576, 10, 2, 
	6, 733, 233, 
	25, 1, 788
}; //Size = 9

