/*
	.\Panel\colorMappingGamutMatrix.h
	Color Mapping Gamut Matrix data generated by Display Editor
	Panel CMO_1080P_M236H5_L02
	Gamma: 2.2
	Temperature: 6500K
 */

/******************************************************************************
Color Mapping Gamut Matrix for Gamma 2.2,6500K, 10 bits
Provided by Display Editor
******************************************************************************/

WORD ROM COLOR_MAPPING_GAMUT_MATRIX_sRGB_6500K_M236H5_L02[9]=
{
   // R, G, B
	799, 1, 8, 
	68, 1009, 10, 
	33, 1, 974	
}; //Size = 9

